### ISSUE TITLE
Got error at startup: KeyError: 'eth0:0'

### ISSUE THREAD

**Issue by pi11** [aristocratos/bpytop#1]
```
03/08/20 (12:17:12) | ERROR: Data collection thread failed with exception: 'eth0:0'
Traceback (most recent call last):
  File "./bpytop.py", line 2315, in _runner
    collector._collect()
  File "./bpytop.py", line 2719, in _collect
    cls._get_nics()
  File "./bpytop.py", line 2691, in _get_nics
    for nic in sorted(psutil.net_if_addrs(), key=lambda nic: (io_all[nic].bytes_recv + io_all[nic].bytes_sent), reverse=True):
  File "./bpytop.py", line 2691, in <lambda>
    for nic in sorted(psutil.net_if_addrs(), key=lambda nic: (io_all[nic].bytes_recv + io_all[nic].bytes_sent), reverse=True):
KeyError: 'eth0:0'
03/08/20 (12:17:12) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 
```

**Comment by aristocratos** [comment]
Would you mind running:
1. `python3 --version`
2. `bpytop -v`
3. `python3 -c "import psutil; print('\n'.join(psutil.net_io_counters(pernic=True)))"`
4. `python3 -c "import psutil; print('\n'.join(psutil.net_if_addrs()))"`

**Comment by aristocratos** [comment]
The exception should be handled properly in v1.0.1 just released but still don't know the cause of problem.

**Comment by pi11** [comment]
All this happens in tmux session:

user@s:~/soft/bpytop$ python3 --version
Python 3.7.3

user@s:~/soft/bpytop$ ./bpytop.py -v
bpytop version: 1.0.0
psutil version: 5.7.2

user@s:~/soft/bpytop$ python3 -c "import psutil; print('\n'.join(psutil.net_io_counters(pernic=True)))"                    
eth1 
eth0
lo 

user@s:~/soft/bpytop$ python3 -c "import psutil; print('\n'.join(psutil.net_if_addrs()))"                                                                           
lo               
eth0:0 
eth0 
eth1

**Comment by aristocratos** [comment]
Not quite sure what that "eth0:0" value is, but try new version. Should hopefully not crash now.

**Comment by pi11** [comment]
New version works fine, thank you

**Comment by aristocratos** [comment]
Just realized i don't need to iterate over psutil.net_if_addrs() at all. :)

**Comment by aristocratos** [comment]
No problem :P
