### ISSUE TITLE
[BUG] tree and info on a proc crashes

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/bpytop#10]
if i am in tree mode and select info on a proc it crashes or if i select info on a proc then go into tree view
error log says

03/08/20 (19:08:03) | ERROR: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2440, in _collect_temps
    cls.cpu_temp_high, cls.cpu_temp_crit = round(entry.high), round(entry.critical)
TypeError: type NoneType doesn't define __round__ method
03/08/20 (19:08:13) | ERROR: Data collection thread failed with exception: 'cmd'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2319, in _runner
    collector._collect()
  File "/usr/local/bin/bpytop", line 2934, in _collect
    cls.details["cmdline"] = cls.processes[c_pid]["cmd"]
KeyError: 'cmd'
03/08/20 (19:08:13) | WARNING: Exiting with errorcode (1). Runtime 0:00:13

**Comment by aristocratos** [comment]
Will be fixed in v1.0.3 later today.

**Comment by aristocratos** [comment]
v1.0.3 released
