### ISSUE TITLE
[BUG] Clock alignment is off, fix is easy

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#104]
Never noticed this before the new "stat" mode was available, but the clock is not centered. I'm assuming you intended for the clock to be as centered as possible. Really looks way off the way it is now, especially when the window is small. 

The fix is very simple. Search for this: 

```
((CpuBox.width-2)//2)-(clock_len//2)-5)
```

Change it to this: 

```
((CpuBox.width-2)//2)-(clock_len//2)-3)
```

That is all. Makes a big difference now that there is a (nearly) symmetrical pair of boxes to compare it to on the "stat" view mode. In the other modes it was almost impossible to tell it was misaligned. 

After this patch the clock is actually more accurately centered than the dividing line between the `mem` and `disk` boxes. But it all looks pretty good after the clock adjustment. 

Before and after (small views where it shows greatest affect): 

![bpytop_alignment_small](https://user-images.githubusercontent.com/64876997/92319810-b48f2880-efc8-11ea-84e2-ef6e4f207371.png)

Patched: 

![bpytop_alignment_small_patched](https://user-images.githubusercontent.com/64876997/92319818-bf49bd80-efc8-11ea-9532-e0ef9a345ac3.png)

**Comment by aristocratos** [comment]
FIxed in v1.0.25
