### ISSUE TITLE
[REQUEST] settings for collapse in tree mode

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/bpytop#107]
I really do not like how i have to manually un collapse things if i want to look 3 processes deep in tree mode
maybe also have an option to have certain processes un collapse by default so you can say un collapse kthread

**Comment by aristocratos** [comment]
I'm not sure of the usefulness of a filter for which processes to collapse, but I could certainly add the variable (that controls which depth the tree auto collapses on) to the options menu.

Will do in next update.

**Comment by aristocratos** [comment]
Added in v1.0.27
