### ISSUE TITLE
[REQUEST]  Update README to include MX Linux Installation

### ISSUE THREAD

**Issue by SwampRabbit** [aristocratos/bpytop#111]
**Is your feature request related to a problem? Please describe.**
Please add MX Linux to Installation section of README

**Describe the solution you'd like**
Available for MX Linux from MX Package Installer (check Stable and Test Repo tabs for different versions)

**Describe alternatives you've considered**
bpytop is currently in the MX Test Repo, but I believe it will be moved to Stable Main very soon.  http://mxrepo.com/mx/testrepo/pool/test/b/bpytop/  It seemed silly to do a PR to update the README, but I will if that is easier for you.

**Additional context**
I will be maintaining this amazing package in MX Linux for you.

Thank you for your consideration.

**Comment by aristocratos** [comment]
>  It seemed silly to do a PR to update the README, but I will if that is easier for you.

Please do, and I would encourage you to write a short install instruction too.

Or if it's less of a hassle for you, you can post a short description and install instruction in this thread and I will add it.

> I will be maintaining this amazing package in MX Linux for you.

Awesome :)
