### ISSUE TITLE
[BUG] [macOS] All core temps are the same (all report the CPU proximity temperature)

### ISSUE THREAD

**Issue by hacker1024** [aristocratos/bpytop#119]
**Describe the bug**

As [osx-cpu-temp only reports](https://github.com/lavoiesl/osx-cpu-temp/blob/af036f71876e4670a1a7a731d556fa6f96767b13/smc.h#L42) the [CPU proximity temperature](https://superuser.com/a/967056) (which I think is the heatsink temperature), all CPU core temperatures display the same value.

**To Reproduce**

* Open `bpytop` on macOS
* Observe the CPU temperature displays

**Expected behavior**

The temperatures should relate to their cores.

**Screenshots**

In this screenshot, you can see that the reported CPU temperatures are the same as the CPU proximity temperature reported by HWMonitorSMC2.

![image](https://user-images.githubusercontent.com/20849728/93046949-8aabc500-f69e-11ea-8b30-c2d9c1b8afcc.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.31
 - psutil version: 5.7.2
 - (OSX/FreeBSD) Os release version: Big Sur Developer Preview 6 (20A5354i)
 - Terminal used: iTerm2
 - Font used: MesloLGS NF
 - Python version: 3.8.5

**Additional context**

```
14/09/20 (15:30:24) | INFO: New instance of bpytop version 1.0.31 started with pid 10262
14/09/20 (15:30:24) | INFO: Loglevel set to DEBUG
14/09/20 (15:30:24) | DEBUG: Using psutil version 5.7.2
14/09/20 (15:30:24) | DEBUG: CMD: /usr/local/bin/bpytop --debug
14/09/20 (15:30:25) | DEBUG: Collect and draw completed in 0.143569 seconds
14/09/20 (15:30:26) | DEBUG: Init completed in 2.762380 seconds
14/09/20 (15:30:28) | INFO: Exiting. Runtime 0:00:05
```

**Comment by hacker1024** [comment]
As [HWMonitorSMC2 is open source](https://github.com/CloverHackyColor/HWMonitorSMC2), I can try and make a small utility that can output core temperatures (using its method of finding them), and submit a PR.

**Comment by aristocratos** [comment]
> As HWMonitorSMC2 is open source, I can try and make a small utility that can output core temperatures (using its method of finding them), and submit a PR.

That would be great! Do you think this is doable with pure python, using ctypes module or similar? Would like to avoid if possible to include actual C code needing compilation, especially when it will only be used for one particular platform.

Or do you intend on making a standalone utility that could be used to replace `osx-cpu-temp`?

Also, does HWMonitorSMC2 collect any stats for GPU? If it does, maybe its methods could be used to give OSX support for gpu monitoring in bpytop. See issue #26 for more info on that.

**Comment by aristocratos** [comment]
> I've just made a fork of osx-cpu-temp, modified to print core temperatures instead.

Nice work!

Do you plan on creating a homebrew formulae or something similar? Would be helpful since some people would likely shy away from having to manually compile a dependency, even if it is as simple as running make.

> HWMonitorSMC2 does report GPU stats, and it shouldn't be too hard to access them in the same way as the core temperatures.

Is this something you would be willing to work on? The stats needed to keep it on par with the internal functions for linux would be gpu usage, temperature, fan speed, memory usage, core clock, memory clock and gpu model name.

**Comment by aristocratos** [comment]
@hacker1024 
Added functionality for core temp reporting if `coretemp` is available in v1.0.32, but couldn't test it that well since my OSX vm doesn't report any core temperature. Let me know if it's not working.

See b4873584e6963605e871364019233efca62dec71 for the commit.

Will wait on adding any install instructions for coretemp until you are happy with the result.

**Comment by aristocratos** [comment]
@hacker1024 

Do you think you could include the package temp also? Right now osx-cpu-temp is still used for cpu package temp, which would actually be the proximity temp then. With package temp osx-cpu-temp could be completely replaced.

**Comment by hacker1024** [comment]
Thanks, the latest version works nicely (that was fast!). I'll add a package temperature argument as well.

As for the install method, I'll try and get this into the brew repo, and I'll submit a PR with instructions in the README when that's done.

**Comment by hacker1024** [comment]
Upon further inspection, the proximity sensor is different to the package sensor. The package sensor is not actually accessible via the SMC, and the proximity sensor can be quite different to the actual CPU temperature.

I'm instead using the CPU die sensor, which is much more accurate.

It can now be accessed in coretemp v1.1 with the `-p` flag.

**Comment by hacker1024** [comment]
Looks like my coretemp repo isn't popular enough to submit coretemp to the official repositories, so I've mad a tap instead.
#122.

**Comment by aristocratos** [comment]
Thank you for your work!
Changes made in v1.0.33 to exclusively use `coretemp` if it exists.

> >    HWMonitorSMC2 does report GPU stats, and it shouldn't be too hard to access them in the same way as the core temperatures.

> Is this something you would be willing to work on? The stats needed to keep it on par with the internal functions for linux would be gpu usage, temperature, fan speed, memory usage, core clock, memory clock and gpu model name.

Have you given any thought if this is something you would like to help with?

**Comment by hacker1024** [comment]
Have you given any thought if this is something you would like to help with?

I should be able to do everything other than the memory clock, which I don't think is exposed via the SMC.

I have a laptop with no dedicated GPU fan, so I might need a tester for that.

**Comment by aristocratos** [comment]
@hacker1024 
> I should be able to do everything other than the memory clock, which I don't think is exposed via the SMC.

Awesome, the memory clock is likely not that important to people not overclocking and I'm guessing gpu overclocking wouldn't be that common (if possible?) on "real" macs anyway.

> I have a laptop with no dedicated GPU fan, so I might need a tester for that.

Maybe @RedBearAK would be willing to test that out, if he have the hardware?

**Comment by RedBearAK** [comment]
@aristocratos @hacker1024 

What am I doing, now? 

I do have a MacBookPro8,3 and an iMac7,1 available, both running Mojave. Not sure if either one has something that could be called a "dedicated GPU fan" per se. Macs Fan Control shows the MBP fans as just "Left" and "Right" and the iMac fans show as "ODD" (optical drive), "HDD", and "CPU". 

I could run BpyTOP and coretemp on both. I'm just not sure how helpful that would be with what you're talking about.

**Comment by aristocratos** [comment]
@RedBearAK 

> I could run BpyTOP and coretemp on both. I'm just not sure how helpful that would be with what you're talking about.

I was more thinking you could test the tool @hacker1024 writes for gpu collection, but if you haven't got a dedicated gpu fan in any of your systems it's not necessary.

You could take a look at https://github.com/CloverHackyColor/HWMonitorSMC2 and see if it shows any fans that could be related to the gpu since he's using SMC for the new tool.
