### ISSUE TITLE
[REQUEST] Memory usage in megabytes instead of percents

### ISSUE THREAD

**Issue by avently** [aristocratos/bpytop#12]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to show memory usage in megabytes, only percents. I know that I can view in megabytes once I choose a process but it's not a solution when I want to see all processes' memory in MBs.

**Describe the solution you'd like**
I would like to see a new column that shows memory usage in MBs with ability to resort/remove/re-add existing columns such as memory usage in percents. This will also give a possibility to make min required width of a window lower than 80 but let's leave this task to another issue. For now sorting/removing/adding columns with ability to select memory in MBs would be awesome

**Describe alternatives you've considered**
There are no alternatives:)

I'm just using your application since today but it looks promissing! Thanks

**Comment by drazil100** [comment]
Maybe it could be a quick toggle. I think both have value. If space is a concern I am not exactly sure what value Color provides being a quick toggle instead of being controlled in the options.

**Comment by avently** [comment]
>  I am not exactly sure what value Color provides 

I don't know what `Color` means in this context. 
I'm not really want to have a `hard-to-develop toggle` in menu, even setting inside config file for manually editing is fine if it matters.

**Comment by avently** [comment]
Found button named `Colors`. Yes, it's probably can be safely removed from the main window as well as `Gradient`button

**Comment by drazil100** [comment]
Sorry I meant colors.

**Comment by aristocratos** [comment]
This is doable, but will use more cpu since the memory value I can get from psutil is in bytes and would have to be converted with my floating_humanizer() function to convert to KB, MB, GB etc (to not take up too much space). So would add an extra function call for every process on every update.

**Comment by avently** [comment]
> is in bytes and would have to be converted with my floating_humanizer() function to convert to KB, MB, GB 

I'm not an expert in Python but is it actually cost something meaningfull in CPU time? Based on my experience with other languages it should be instant (1ms maybe). Drawing will take more time than this. Also, even if it costs more CPU time and if no other solution, that's fine.

**Comment by aristocratos** [comment]
On a modern cpu it would probably not be too noticeable.

But the process iteration is what takes up maybe 50-75% of bpytops cpu usage, so adding a extra function call for every iteration will most likely have some effect, depending on the number of processes running.

But gonna try it out when I've got some time :)

**Comment by H1414** [comment]
ددل

**Comment by aristocratos** [comment]
@avently 
Added in v1.0.8

**Comment by massto** [comment]
Added in v 1.0.8

**Comment by avently** [comment]
works good, as always. Thank you, @aristocratos!

**Comment by aristocratos** [comment]
No problem :)

I found a workaround for my worry of cpu usage increase; it only has to run the extra function for the processes actually visible on screen.
