### ISSUE TITLE
[BUG] Crash after sending an interrupt

### ISSUE THREAD

**Issue by gorghino** [aristocratos/bpytop#120]
Fresh install to Elementary OS 5.1.7 Hera. 
Typing 'i' on libreoffice process killed bpytop.

[A clear and concise description of what the bug is.]

It doesn't seem to happen everytime. I retry to interrupt the same process on the list, but it worked the second time.

[Steps to reproduce the behavior:]

- Open bpytop
- Arrow down to the process
- Type 'i'

[A clear and concise description of what you expected to happen.]

The process should be interrupted

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: 1.0.31
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Elementary OS 5.1.7 Hera. Linux 4.15.0-117-generic
 - (OSX/FreeBSD) Os release version:
 - Terminal used: io.elementary.terminal
 - Font used: 'Roboto Mono 10'
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.6.9

**Additional context**

```
14/09/20 (16:43:34) | ERROR: local variable 'sig' referenced before assignment
Traceback (most recent call last):
  File "/home/gorgo/.local/lib/python3.6/site-packages/bpytop.py", line 4496, in process_keys
    os.kill(pid, sig)
UnboundLocalError: local variable 'sig' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gorgo/.local/lib/python3.6/site-packages/bpytop.py", line 4655, in main
    run()
  File "/home/gorgo/.local/lib/python3.6/site-packages/bpytop.py", line 4649, in run
    process_keys()
  File "/home/gorgo/.local/lib/python3.6/site-packages/bpytop.py", line 4498, in process_keys
    errlog.error(f'Exception when sending signal {sig} to pid {pid}')
UnboundLocalError: local variable 'sig' referenced before assignment
14/09/20 (16:43:35) | WARNING: Exiting with errorcode (1). Runtime 0:02:34 
```

**Comment by aristocratos** [comment]
@gorghino 
Fixed in v1.0.32
