### ISSUE TITLE
[BUG] Pentium CPU models just show as digit

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#127]
I have an old Pentium 4 laptop. The CPU shows up in BpyTOP currently as just "4". 

![cpu_pentium_bug](https://user-images.githubusercontent.com/64876997/93289605-3d595180-f78b-11ea-98a5-5037a62bf6dd.png)

`cat /proc/cpuinfo`

Result: `model name	: Intel(R) Pentium(R) 4 CPU 2.80GHz`

Secondary issue is if the CPU temp is not available, the CPU info box is too small to display more than seven characters for the CPU name. So if I force it to display "BlahBlahBlah" as the model name, BpyTOP will only show "BlahBla". Which leaves off the actual model number such as "III", "3" or "4". 

So my suggested patch for this uses a shortened version of "Pentium" to deal with the possibility of having no CPU temps being displayed. To show the full "Pentium 4" name would need some logic to check that the length of the CPU info box is sufficient to display all characters extracted from the model name. 

The patch is very simple. Add this just below the test for "Xeon": 

```
	elif "Pentium" in name:
		name = "Pent-" + nlist[nlist.index("CPU")-1]
```

After patch: 

```
	if "Xeon" in name and "CPU" in name:
		name = nlist[nlist.index("CPU")+1]
	elif "Pentium" in name:
		name = "Pent-" + nlist[nlist.index("CPU")-1]
	elif "Ryzen" in name:
		name = " ".join(nlist[nlist.index("Ryzen"):nlist.index("Ryzen")+3])
	elif "Duo" in name and "@" in name:
		name = " ".join(nlist[:nlist.index("@")])
	elif "CPU" in name and not nlist[0] == "CPU":
		name = nlist[nlist.index("CPU")-1]

	name = " ".join(name.split())
	return name.replace("Processor ", "").replace("CPU ", "").replace("(R)", "").replace("(TM)", "").replace("Intel ", "")

```

This produces "Pent-4" for the model name on my machine. More than adequate, unless you really want to spend the extra 15 minutes to figure out how to calculate the length of the CPU info box and display "Pentium 4" if there is enough room and compact it to "Pent-4" if there isn't.

**Comment by aristocratos** [comment]
I'll add detection if the characters preceding "CPU" is digits the full name will be returned. Also added a regex to remove "X.XXGHz" from the string. Which will result in better name representation overall and "model name : Intel(R) Pentium(R) 4 CPU 2.80GHz" will become "Pentium 4".

> So my suggested patch for this uses a shortened version of "Pentium" to deal with the possibility of having no CPU temps being displayed.

This however will not be added since the `get_cpu_name()` function is only run once at start and the cpu details box can change width at any time if the user toggles `show temp` in the options, or the sensors for some reason stops working. This would also need explicit logic for all possible names that would need to be shortened. And need added logic for re-running the `get_cpu_name()` function on any size changes. It gets to be a little too much coding just too show a name that isn't exactly incredibly informing (presumably people already know what cpu they've got).

This is the reason I added the `custom cpu name` variable in the options, if the user isn't happy with the name picked up, they can change it to whatever they see fit.

**Comment by RedBearAK** [comment]
Ah. Of course you are correct. I never felt like disabling the temps so I kind of forgot that was an option, and that would affect all CPU names longer than 7 characters without a lot more work. A conundrum. 

I'm still surprised there isn't a common library available to help extract a clean, short CPU name. 

So my machine would end up just showing "Pentium" unless I can get the temps working. Better than just saying "4". 

I know it's getting fairly unlikely at this point but you may want to consider making the regex something more like (best mock syntax I can muster after not doing any regex in years) `"[whitespace][0-9.]*[mMgG][hH][zZ]"`. In other words, any digits, a period, and either an M or G that comes between a whitespace character and "Hz", regardless of proper capitalization. This would cover the case of a machine low-powered or old enough to have a CPU speed reported in MHz. 

I can't say with certainty but since there is apparently no standard in how to format the model name it could be that even a few relatively modern CPUs might report as something like "2800MHz" rather than "2.80GHz", so this wouldn't necessarily only apply to really old systems or embedded devices.

**Comment by aristocratos** [comment]
@RedBearAK 
This is the regex I added `\d?\.?\d+GHz` will change it so the full replace block after the search will be:

``` python
name = name.replace("Processor", "").replace("CPU", "").replace("(R)", "").replace("(TM)", "").replace("Intel", "")
name = re.sub(r"\d?\.?\d+[mMgG][hH][zZ]", "", name)
name = " ".join(name.split())
```

**Comment by RedBearAK** [comment]
Looks great. That seems to cover all the possible examples I was thinking about. 

Tested with several sample inputs, printing the output to the command line, and it works well catching all the variations I could think of. 

I keep having this nagging feeling it would be more technically correct to move the whitespace-stripping join/split line to the very beginning where the full name is found, just before the "nlist" array is created, but I can't think of any good reason why it would make any difference. I mean, other than the array having fewer elements stored to begin with, I guess. Pretty meaningless since it works either way.

**Comment by aristocratos** [comment]
Added in v1.0.34

**Comment by RedBearAK** [comment]
@aristocratos 

Confirmed that 1.0.35 shows "Pentium" now instead of "4" on my machine. 

Closing issue.
