### ISSUE TITLE
[BUG] indication bars Sliding tops :-/

### ISSUE THREAD

**Issue by K4S1** [aristocratos/bpytop#129]
**Describe the bug**

Seems like process bars are are sliding

**To Reproduce**

Start program and wait.
After some time Seems like spikes are are out of sync, not 100% how to explain.
See screenshot :)

**Expected behavior**
Strait spikes ?

**Screenshots**

![image](https://user-images.githubusercontent.com/8589819/93596070-11bbae80-f9b9-11ea-8de8-dd6dbaf8d9e2.png)
![20200918-142118](https://user-images.githubusercontent.com/8589819/93596933-7b888800-f9ba-11ea-86a3-30a2c8f9bd2a.gif)

**Info (please complete the following information):**
--- ~ » fetch            
▉▉  | System ....... Arch rolling
  ▉▉| Packages ..... 1752 (pacman)
▉▉  | Uptime  ...... 6h 7m
  ▉▉| Resolution  .. 2560x1440, 2560x1440, 2560x1440
▉▉  |
  ▉▉| WM ........... KWin
▉▉  | Shell ........ zsh 5.8 
  ▉▉| Terminal ..... konsole
▉▉  | Term Font .... Noto Sans Mono 10
  ▉▉|
▉▉  | Kernel ....... 5.8.9-arch2-1
  ▉▉| Processor ....  i7-8650U  (8C)
▉▉  | Gpu .......... Corporation UHD Graphics 620
  ▉▉|
▉▉  | Birthday ..... Tue Aug 11 23:57:54 2020
  ▉▉| Memory ....... 10304MiB / 15887MiB
--- ~ » bpytop -v
bpytop version: 1.0.33
psutil version: 5.7.2
--- ~ » python3 --version
Python 3.8.5

**Additional context**
--- ~ » cat ~/.config/bpytop/error.log
18/09/20 (14:20:02) | INFO: New instance of bpytop version 1.0.33 started with pid 87463
18/09/20 (14:20:02) | INFO: Loglevel set to DEBUG
18/09/20 (14:20:02) | DEBUG: Using psutil version 5.7.2
18/09/20 (14:20:02) | DEBUG: CMD: /usr/bin/bpytop --debug
18/09/20 (14:20:05) | DEBUG: Collect and draw completed in 0.450750 seconds
18/09/20 (14:20:05) | DEBUG: Init completed in 3.055614 seconds
18/09/20 (14:25:04) | INFO: Exiting. Runtime 0:05:01 

--- ~ »

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by K4S1** [comment]
Update:
If I run in termite no issue.

Could may be my fint :/
▉▉  | System ....... Arch rolling
  ▉▉| Packages ..... 1752 (pacman)
▉▉  | Uptime  ...... 6h 21m
  ▉▉| Resolution  .. 2560x1440, 2560x1440, 2560x1440
▉▉  |
  ▉▉| WM ........... KWin
▉▉  | Shell ........ zsh 5.8 
  ▉▉| Terminal ..... termite
▉▉  | Term Font .... Monospace 11
  ▉▉|
▉▉  | Kernel ....... 5.8.9-arch2-1
  ▉▉| Processor ....  i7-8650U  (8C)
▉▉  | Gpu .......... Corporation UHD Graphics 620
  ▉▉|
▉▉  | Birthday ..... Tue Aug 11 23:57:54 2020
  ▉▉| Memory ....... 10565MiB / 15887MiB

Will test and update

**Comment by K4S1** [comment]
I'll guess it the Terminal emulator :-/
Have pushed monospace 11 on both 

![image](https://user-images.githubusercontent.com/8589819/93599449-6d3c6b00-f9be-11ea-89dc-ec5f159bd14d.png)
![image](https://user-images.githubusercontent.com/8589819/93599545-93faa180-f9be-11ea-9584-7d44cf7b3020.png)

**Comment by RedBearAK** [comment]
I've seen more than one previous report like this and the feedback from the dev was that there is a problem in some circumstances with the way Konsole renders some of the unicode braille characters BpyTOP uses. 

This kind of issue seems to be very specific to Konsole. 

Scan through the closed issues for related reports. For instance, issue #100. Read through that thread for possible solutions.

**Comment by aristocratos** [comment]
@K4S1 
https://github.com/aristocratos/bpytop#prerequisites :

> Notice

> If you are having problems with the characters in the graphs not looking like they do in the screenshots, it's likely a problem  with your systems configured fallback font not having support for braille characters.

> Se comments by @sgleizes [link](https://github.com/aristocratos/bpytop/issues/100#issuecomment-684036827) and @XenHat [link](https://github.com/aristocratos/bpytop/issues/100#issuecomment-691585587) in issue #100 for possible solutions.

**Comment by K4S1** [comment]
Thanks for your feedback :+1:

**Comment by K4S1** [comment]
Last update on this to Konsole.
when disable the "Bi-Directional text rendering"
![image](https://user-images.githubusercontent.com/8589819/96634467-d9422400-131a-11eb-877d-2cef32f314c0.png)

All seems cool in Konsole again :-) no more sliding bars

![image](https://user-images.githubusercontent.com/8589819/96635084-b5cba900-131b-11eb-9589-3ee7d3bbb2ac.png)

Thanks for the hint ;-P
