### ISSUE TITLE
[REQUEST] Remove min width and height requirements

### ISSUE THREAD

**Issue by avently** [aristocratos/bpytop#13]
**Is your feature request related to a problem? Please describe.**
For now I'm unable to make terminal workspace with width less than 80 (in what unit this size is?) and height less than 24. I'm pretty sure there shouldn't be any limitation because if something not fully visible it's up on a user. 

**Describe the solution you'd like**
The solution would be to make possible to sort/add/remove columns if you want to view only usaful info that can be viewed in small window. But the main goal is to remove limitation of min width/height.

**Describe alternatives you've considered**
No alternatives

**Additional context**
The min width/height requirements shows up when I try to make terminal workspace smaller. I'm aware that this way can give me a small picture of information but it's what I need to see actually

**Comment by aristocratos** [comment]
> (in what unit this size is?)
Characters

> the main goal is to remove limitation of min width/height.
This isn't possible without creating a lot of issues and possibly crashing because of the way I've coded it. And would require a lot of extra checks on all draw functions to not break.

> I'm unable to make terminal workspace with width less than 80 and height less than 24
What terminal/font size are you using where you can't have more than 80 characters in width?

Can look in to it when I've got some time, but not a priority right now.

**Comment by avently** [comment]
> What terminal/font size are you using where you can't have more than 80 characters in width?

I can have more but I can't have less because of the app's notice: "Width and height needs to be at least 80 x 24".
I use layout like this in my terminal:    |______||_|     
First part of the terminal's tab is a place for `less` command with logs from my app, second part of the tab is `htop`. It has a small part because I need only memory usage, process name and CPU usage. The logs, on the other hand, is more important thing and should be in as wide part of window as possible. So that's why I'm asking about removing limitation when you are at the start of development. Later will be harder to change such things if it wasn't planned initially.
