### ISSUE TITLE
[BUG] net -> Download -> Total does not continue to count

### ISSUE THREAD

**Issue by T200proX7** [aristocratos/bpytop#130]
BpyTop -> Net -> Download -> Total -> does not continue to count.

![2020-09-20_18-34-51](https://user-images.githubusercontent.com/57217666/93716572-d2d05900-fb70-11ea-8f29-34504159aa98.gif)

The interesting thing is, it counts for a minute like that, and after it increase from 71 to 72 .. 
it looks like that the the counting digit is a 10mb-step not a 100mb-step - and thats why it counts several time till the GB digit really has to change?

bpytop version: 1.0.33
psutil version: 5.7.2
Python 3.7.3
Linux jdebian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by aristocratos** [comment]
@T200proX7
Yup, was a decimal placement error in the `floating_humanizer()` function.
Fixed in v1.0.35

**Comment by T200proX7** [comment]
Great
