### ISSUE TITLE
[BUG] CPU Temperature Not Visible (Cut off)

### ISSUE THREAD

**Issue by scchearn** [aristocratos/bpytop#132]
**Describe the bug**

On CPU with 16 cores, the CPU temperature gets cut off. I guess it's because bpytop adds a third column and space is a bit tight. 

**To Reproduce**

Run bpytop on system with 16 core (or more) CPU.

**Expected behavior**

Visible CPU temperatures. 

**Screenshots**

![bpytop-cputemp](https://user-images.githubusercontent.com/4113674/93758279-cd2a5000-fc10-11ea-8125-d7b03cba8d7e.png)

I would gladly do with less CPU usage graph to make space for CPU temp.

**Info (please complete the following information):**
 - bpytop version: `1.0.35`
 - psutil version: `5.7.2`
 - (Linux) Linux distribution and version: `Manjaro Linux x86_64 5.7.19-2-MANJARO`
 - Terminal used: `bash 5.0.18`
 - Font used: `Roboto Mono Light`
 - Python version, `3.8.5`

**Comment by aristocratos** [comment]
@scchearn 
`bash 5.0.18` isn't a terminal but the shell you are running, need to know which terminal emulator.

From the issues you're having I would guess you are using `konsole`?

Looking at the screenshot I'm pretty sure this is a font problem related to #100, see the last comments for a possible solution.

**Comment by delta-one** [comment]
I'm having the same problem with Yakuake and MesloLGS NF. Switching fonts indeed solves the problem, though I don't really want to do that (Meslo is highly recommended for the oh-my-zsh theme I'm using).

![cpu2](https://user-images.githubusercontent.com/9049025/94086662-eb0fd480-fe0b-11ea-87db-24af6e55efca.png)

**Comment by aristocratos** [comment]
@delta-one 
You could patch the font you want to use using https://github.com/ryanoasis/nerd-fonts and use the font that worked as source to fill out any missing symbols. Should be a workaround for konsole/yakuake not rendering the fallback font correctly.

**Comment by delta-one** [comment]
Tried patching it myself, but installing the font-patcher is a fucking mess (incl. the python vs. python2 vs. python3 mess).

**Comment by g6avk** [comment]
Turning off "Bi-Directional text rendering" in konsole/yakuake fixed this for me. But I don't use any custom Fonts so mileage may vary.

**Comment by delta-one** [comment]
> Turning off "Bi-Directional text rendering" in konsole/yakuake fixed this for me. But I don't use any custom Fonts so mileage may vary.

That does the trick for me as well.

**Comment by aristocratos** [comment]
@g6avk 
> >   Turning off "Bi-Directional text rendering" in konsole/yakuake fixed this for me. But I don't use any custom Fonts so mileage may vary.

> That does the trick for me as well.

Great find, will add this to the readme as a possible fix for konsole/yakuake.

**Comment by scchearn** [comment]
@g6avk 

I can confirm that this works for my configuration too. Thank you.

![2020-09-30_09-40](https://user-images.githubusercontent.com/4113674/94651465-2bd28680-0301-11eb-98c4-e1ddf247cf70.png)

**Comment by harmannnn** [comment]
> Turning off "Bi-Directional text rendering" in konsole/yakuake fixed this for me. But I don't use any custom Fonts so mileage may vary.

where is this setting? I have been searching for hours... theres nothing on google about this Bi-Di text

**Comment by g6avk** [comment]
I have had Emails about finding this Bi-Directional text rendering setting.
konsole/yakuake - Manage Profiles>Edit>Advanced
