### ISSUE TITLE
[BUG]No such file or directory: '/sys/class/power_supply'

### ISSUE THREAD

**Issue by fenghaichun** [aristocratos/bpytop#134]
MacOS

  1 28/09/20 (16:31:13) | ERROR: Data collection thread failed with exception: [Errno 2] No such file or directory: '/sys/class/power_supply'
  2 Traceback (most recent call last):
  3   File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2581, in _runner
  4     collector._draw()
  5   File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 2817, in _draw
  6     CpuBox._draw_fg()
  7   File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1704, in _draw_fg
  8     if CONFIG.show_battery and cls.battery_activity():
  9   File "/usr/local/lib/python3.8/site-packages/bpytop.py", line 1640, in battery_activity
 10     for directory in os.listdir("/sys/class/power_supply"):
 11 FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/power_supply'
 12 28/09/20 (16:31:13) | WARNING: Exiting with errorcode (1). Runtime 0:00:02
 13
 14 28/09/20 (16:31:16) | WARNING: Exiting with errorcode (1). Runtime 0:00:05

**Comment by lwhsu** [comment]
Please check if #135 helps.

**Comment by aristocratos** [comment]
@lwhsu 
That should do it, forgot to add the check. Will be merged in next update later today.

**Comment by jtrees** [comment]
I get this message in an Ubuntu 18.04 VM.

```
linux version: 4.15.0
bpytop version: 1.0.50
psutil version: 5.7.3
```
