### ISSUE TITLE
[BUG] broken, misaligned interface lines

### ISSUE THREAD

**Issue by matkoniecz** [aristocratos/bpytop#142]
**Describe the bug**

GUI section lines are broken and misaligned and keep moving

**To Reproduce**

```
pip3 install bpytop --upgrade
bpytop
```

**Expected behavior**

GUI is not broken

**Screenshots**

See lines on the right side
![screen02](https://user-images.githubusercontent.com/899988/95683894-40aaf600-0bee-11eb-9cf5-27053e3883fe.png)

**Info (please complete the following information):**
 - bpytop version: `bpytop -v` `bpytop version: 1.0.42`
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) `psutil version: 5.7.2`
 - (Linux) Linux distribution and version: Lubuntu 20.04.1 LTS (? what is the difference between this line and next?)
 - (OSX/FreeBSD) Os release version: Lubuntu 20.04.1 LTS (? what is the difference between this line and next?)
 - Terminal used: QTerminal 0.14.1
 - Font used: Ubuntu Mono 14 pt (default for this terminal)
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

PS Thanks, thanks, thanks for listing required info with commands! (BTW, maybe adding `lsb_release -a` to mix for OS version would be useful?)

**Additional context**

bashtop has the same problem

contents of `~/.config/bpytop/error.log`

```
11/10/20 (18:24:27) | INFO: New instance of bpytop version 1.0.42 started with pid 12916
11/10/20 (18:24:27) | INFO: Loglevel set to DEBUG
11/10/20 (18:24:27) | DEBUG: Using psutil version 5.7.2
11/10/20 (18:24:27) | DEBUG: CMD: /home/mateusz/.local/bin/bpytop --debug
11/10/20 (18:24:31) | DEBUG: Collect and draw completed in 0.289529 seconds
11/10/20 (18:24:34) | DEBUG: Init completed in 6.986931 seconds
11/10/20 (18:24:38) | INFO: Exiting. Runtime 0:00:11 
```

**Comment by matkoniecz** [comment]
I would be happy to run commands/provide more info if that would be useful.

**Comment by matkoniecz** [comment]
EDIT: old title remained from bug report for snap version (Ubuntu recommends installing broken snap version), but I see from readme that it is not recommended install - I forgot to change the title

**Comment by aristocratos** [comment]
@matkoniecz 
Font issues is a terminal issue and not a bpytop issue.
You can try the solutions below, otherwise try another terminal.

From README.md https://github.com/aristocratos/bpytop#prerequisites

> Notice
> 
> If you are having problems with the characters in the graphs not looking like they do in the screenshots, it's likely a problem with your systems configured fallback font not having support for braille characters.
> 
> See comments by @sgleizes link and @XenHat link in issue #100 for possible solutions.
> 
> If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix.

**Comment by matkoniecz** [comment]
> If you are having problems with the characters in the graphs not looking like they do in the screenshots

Maybe list alignment issues also here and that all of them are assumed to be terminal bugs?

And maybe list some known compatible ones?

**Comment by aristocratos** [comment]
@matkoniecz 
> Maybe list alignment issues also here and that all of them are assumed to be terminal bugs?

Too be fair, in your screenshot there is multiple characters clipping into each other, I would think that's a fairly good indicator of a terminal problem.

I could add something along the lines of `characters clipping in to each other or box border misalignment is not a bug caused by bpytop, but a terminal problem or a fontconfig problem`, but I would really like to avoid adding more explanations for bugs not caused by bpytop, since that list could grow very big, and I would like redirect people to the correct place for a bug report rather then add explanations of workarounds that won't get the core issue fixed.

So I would encourage you to make a bug report at https://github.com/lxqt/qterminal and hopefully they'll do something about it.

**Comment by matkoniecz** [comment]
> I would think that's a fairly good indicator of a terminal problem.

In my case (low knowledge how complicated characters work in terminals) I assumed that it is a bug on side of application.

**Comment by aristocratos** [comment]
> In my case (low knowledge how complicated characters work in terminals) I assumed that it is a bug on side of application.

I will add a notice about what would likely constitute a terminal bug and what to do about it in the readme, should make it easier for people in the future.
