### ISSUE TITLE
[BUG] bad colors!

### ISSUE THREAD

**Issue by karimi12** [aristocratos/bpytop#145]
i use ubuntu 18 
colors for me is very bad i tested different themes but they aren`t good too
screenshot:
http://s16.picofile.com/file/8411025950/bb.PNG

bpytop version: 1.0.42
psutil version: 5.7.2
ubuntu 18
Python 3.6.9
 - Terminal used: Default (putty)
 - Font used: Default

**Comment by aristocratos** [comment]
@karimi12 
https://github.com/aristocratos/bpytop#prerequisites :

> ...
> For correct display, a terminal with support for:
> 
>     24-bit truecolor (See list of terminals with truecolor support)
>     Wide characters (Are sometimes problematic in web-based terminals)
>
