### ISSUE TITLE
Bring back shiftless control.

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#15]
I much preferred when all of the controls were all lowercase and if two actions shared a first letter a different letter of the second action was chosen. (E.g. **t**erminate and tre**e**) 

Call me lazy but I like pressing one key instead of 2.

```
Old   New   Action
 m     m    menu
 f     f    filter
 c    del   clear filter
 r     R    reverse
 e     T    tree
 t     t    terminate
 k     k    kill
 i     i    interrupt
 b     b    back network device
 n     n    next network device
       M    mini
       g    graph
       s    swap
       C    colors
       G    gradient
       P    per-core
       z    zero
```
After making this list I have a couple takeaways. 
1. I don't see why colors and gradient need a shortcut to toggle. Maybe other people are switching back and forth more than I think but these are more style preferences and are wasting screen real-estate. I am not particularly bothered by them requiring shift to activate if they do need shortcuts. 
2. Reverse, Colors, and Per-Core have no reason to require shift other than to match the formatting of the other surrounding actions. As stated above I don't think Colors and Gradient really need quick toggles so if they were removed that would only leave M and T as required capital letters to have the key match the first letter of the action.
3. switching between tree and not tree is something I do frequently and having to hold shift to toggle the option is going to be a bit annoying. I much preferred e for that option. If a convention has to be broken id prefer the convention that doesn't require me to push additional keys be broken.

I don't really know what you would do with mini. All of its letters are taken by other actions.

**Comment by drazil100** [comment]
Also an additional point against T for tree is it is too easy to accidentally press t for terminate. Mapping tree to e like in bashtop pretty much prevents the mistake from being possible if a user doesn't know its case sensitive.

**Comment by avently** [comment]
I agree with removing shortcuts for unused elements. Also I think that `menu` and `mini` should have swaped hot keys. Menu should have capital 'M' and mini version of the app should have small 'm', Because in real world no one should use menu often but mini and non-mini version is more useful. For example, I don't need large version 90% of time. It's useful for many purpouses, yes, but not all the time. So I'm switching between both version often. Would be better to have it as small `m`.

**Comment by drazil100** [comment]
I agree with the idea of mini being the quicker to access action. Thinking about it though I think menu's shortcut should probably just be escape. I mean escape already opens the menu in the current release but I don't see a need for it to have m also. That said giving it M wouldn't really hurt anything so.

By the way can we all just appreciate the irony that mini gets the bigger M xD

**Comment by aristocratos** [comment]
Good feedback! And I and can agree that adding shift modifier wasn't the best idea.
It was a last minute change before release.

> I don't see why colors and gradient need a shortcut to toggle.

Yeah, did get a bit cluttered, will probably be enough to have them in the options menu.

> Also I think that menu and mini should have swaped hot keys. Menu should have capital 'M' and mini version of the app should have small 'm',

Will do.

> By the way can we all just appreciate the irony that "mini" got the bigger M xD

Heh, not quite sure what I was thinking there, gonna blame lack of sleep :)

I can probably work in customizable hotkeys at some later point when the most urgent bugs has been fixed.

**Comment by aristocratos** [comment]
Changed in v1.0.3

**Comment by drazil100** [comment]
That could be nice though I never had a problem with the default key bindings before and suspect once shift is removed I won't need or even want to remap the keys. Plus having customizable hotkeys would mess with the whole faded letter is the key thing you have going (which is extremely intuitive)

**Comment by avently** [comment]
> Changed in v1.0.3

Thank you, looks good!

**Comment by drazil100** [comment]
This is way better! Thank you!
