### ISSUE TITLE
[BUG] Circus of colors

### ISSUE THREAD

**Issue by BeenHijacked** [aristocratos/bpytop#150]
**Describe the bug**

When I installed on macOS I got the worst looking UI I've ever seen. Is that normal?

**To Reproduce**

Install on 10.14.6

**Expected behavior**

To be able to read or see what is on the screen

**Screenshots**

![circustop](https://user-images.githubusercontent.com/60056422/96398786-8e40d900-1181-11eb-971b-8d37e76636c2.GIF)

**Info (please complete the following information):**
 - bpytop version: uninstalled
 - psutil version: uninstalled
 - (OSX/FreeBSD) 10.14.6
 - Terminal used: Terminal.app
 - Font used:
 - Python version: 3.6.10

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@BeenHijacked 
I'll bet reading the README had been faster than creating a bug report https://github.com/aristocratos/bpytop#prerequisites

**Comment by BeenHijacked** [comment]
There was no readme, I installed it from pip.

**Comment by aristocratos** [comment]
@BeenHijacked 
The readme is the first page on both github and pypi and it's also included in the pypi package.

It's not so much an issue of wasting my time but for people to not have to deal with issues easily fixed from the information available.
