### ISSUE TITLE
[BUG] PermissionError: [Errno 13] Permission denied: '/proc/diskstats' when running from snap

### ISSUE THREAD

**Issue by misieck** [aristocratos/bpytop#154]
Upon invocation bpytop starts, displays loading screen and promptly exits with the error message:
`Bpytop exited with errorcode (1). See /root/snap/bpytop/147/.config/bpytop/error.log for more information!`
The log file boils down to 
`PermissionError: [Errno 13] Permission denied: '/proc/diskstats'`
I can read /proc/diskstats as normal user (permission 444).

**To Reproduce**
 ```
snap install bpytop
bpytop
```

**Expected behavior**
bpytop starts in all its glory

**Info**
 - bpytop version: 1.0.42
 - psutil version:  5.7.2
 - PopOs 20.04, linux pop-os 5.4.0-7642-generic  # 46~ 1598628707~ 20.04~ 040157c-Ubuntu
 - Terminal used: bash
 - Font used:?
 - Python: 3.8.2
 - snap:    2.47.1
 - snapd:  2.47.1
 - series  16

**Additional context**

> 20/10/20 (22:04:37) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
> Traceback (most recent call last):
>   File "/snap/bpytop/147/usr/bin/bpytop", line 2597, in _runner
>     collector._collect()
>   File "/snap/bpytop/147/usr/bin/bpytop", line 2930, in _collect
>     io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
>   File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/__init__.py", line 2063, in disk_io_counters
>     rawdict = _psplatform.disk_io_counters(**kwargs)
>   File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1123, in disk_io_counters
>     for entry in gen:
>   File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1074, in read_procfs
>     with open_text("%s/diskstats" % get_procfs_path()) as f:
>   File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_common.py", line 727, in open_text
>     return open(fname, "rt", **kwargs)
> PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
> 20/10/20 (22:04:37) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by islamelnabarawy** [comment]
This tip from the README file fixed the issue for me:

> Give permissions

```
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe
```

**Comment by 0nyr** [comment]
I got the error too: 

24/10/20 (18:20:56) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/diskstats'
Traceback (most recent call last):
  File "/snap/bpytop/147/usr/bin/bpytop", line 2597, in _runner
    collector._collect()
  File "/snap/bpytop/147/usr/bin/bpytop", line 2930, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/__init__.py", line 2063, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1123, in disk_io_counters
    for entry in gen:
  File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1074, in read_procfs
    with open_text("%s/diskstats" % get_procfs_path()) as f:
  File "/snap/bpytop/147/usr/lib/python3/dist-packages/psutil/_common.py", line 727, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/diskstats'
24/10/20 (18:20:56) | WARNING: Exiting with errorcode (1). Runtime 0:00:02

**Comment by aristocratos** [comment]
@misieck @0nyr 
Read the install instructions:
https://snapcraft.io/install/bpytop/ubuntu
or
https://github.com/aristocratos/bpytop#snap-package

**Comment by comperem** [comment]
these steps seem like they should be part of the installation. it's not a bug, perhaps, but not simple to install the way snaps or .deb's should be.

**Comment by aristocratos** [comment]
@comperem 
That's something you should take up with @kz6fittycent, I didn't create the snap package, don't provide support for it or use snap myself.

**Comment by kz6fittycent** [comment]
Did you ensure that the connections were in place? 

```
snap info bpytop 
name:      bpytop
summary:   A Python-based resource monitor for your terminal
publisher: James Tigert (kz6fittycent)
store-url: https://snapcraft.io/bpytop
contact:   https://github.com/kz6fittycent/bpytop-snap
license:   Apache-2.0
description: |
  Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  Python port of bashtop
  
  * Easy to use, with a game inspired menu system.
  * Fast and "mostly" responsive UI with UP, DOWN keys process selection.
  * Function for showing detailed stats for selected process.
  * Ability to filter processes.
  * Easy switching between sorting options.
  * Send SIGTERM, SIGKILL, SIGINT to selected process.
  * UI menu for changing all config file options.
  * Auto scaling graph for network usage.
  * Shows message in menu if new version is available
  * Shows current read and write speeds for disks
  * Multiple data collection methods which can be switched if running on Linux
  
  **Once installed, run the following commands so the snap will function as intended:**
  
  `sudo snap connect bpytop:mount-observe`
  
  `sudo snap connect bpytop:network-control`
  
  `sudo snap connect bpytop:hardware-observe`
  
  `sudo snap connect bpytop:system-observe`
  
  `sudo snap connect bpytop:process-control`
  
  `sudo snap connect bpytop:physical-memory-observe`
  
  To run, just type (in your terminal): `bpytop`

```

**Comment by kz6fittycent** [comment]
> these steps seem like they should be part of the installation. it's not a bug, perhaps, but not simple to install the way snaps or .deb's should be.

Those connections require specific approvals for each. It can take months to get them. I've been trying on other snaps I've created and still don't have said approvals. At this point, it's more feasible for the end-user to run a few commands to get the connections in place.

**Comment by aristocratos** [comment]
@kz6fittycent 
Figured that was likely. Guess they need to manually review it, not sure who would actually be dumb enough to write malware in python though :)

**Comment by kz6fittycent** [comment]
> @kz6fittycent
> Figured that was likely. Guess they need to manually review it, not sure who would actually be dumb enough to write malware in python though :)

There was a guy who released a snap that was leveraging a hidden script. It was mining crypto...

He's permanently banned. That's what spurred the extra precautions; at least that is what I think spurred them.

**Comment by aristocratos** [comment]
@kz6fittycent 
> There was a guy who released a snap that was leveraging a hidden script. It was mining crypto...

Well there's always gonna be idiots. But doesn't seem like a tenable situation, I mean, wouldn't they need to review every update for any program they previously accepted? Otherwise someone could release a seemingly "good" program and then later when Canonical has given the OK, introduce malware code in an update.

**Comment by jfacemyer** [comment]
I've run into connect issues on other snaps - is it possible to put a message at the end of snap installation that lists things you probably want to connect, why, and how to do it?

**Comment by kz6fittycent** [comment]
I don't think so, I'll ask. But that's really what snap info is for.

**Comment by aristocratos** [comment]
@jfacemyer 
I don't think it's an unreasonable expectation that people read the instructions when installing software. If not before, then at least when they are experiencing problems.

I mean, a big chunk of the bug reports I've gotten could have been solved by reading the README.md

**Comment by kz6fittycent** [comment]
Just got the answer. It's a no.

**Comment by jfacemyer** [comment]
I realize this is true. But it's also true that a lot of times you install a software in a repo expecting it to "just work".

It's not like this is a problem with the software setup itself. If I installed with apt, I'm guessing this wouldn't be an issue, since it's not sandboxed like snaps are. Snap bills itself as a simple way to install software, but until you've hit the hitch, you don't understand that there's going to be one. It's literally unexpected that software installed through normal package managers will just work, and the same software installed by a different package manager will not just work.

Anyway, I'm not upset, or even criticizing you at all. If anything, it's more a criticism of snap, as there should be some sort of installation note system to notify when things won't work as expected (i.e. the same way they work everywhere else) upon installation.

**Comment by jaack65** [comment]
I tried running bpytop with Sudo bpytop and as a normal user. The first report here is Oct 20, 2020, and now it's April 1, 2021, more than 5 months.  Thought that running as root I would not encounter this permission error problem.

**Comment by kz6fittycent** [comment]
I'm assuming you're running the snap. This is all you need to do. 

```
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe
```

If you're still running into the error, you'll need to open a new issue and provide logs.

**Comment by LovesTha** [comment]
Improving the error and/or the end of install message to direct to the extra steps would be nice.

**Comment by kz6fittycent** [comment]
> Improving the error and/or the end of install message to direct to the extra steps would be nice.

you mean like `snap info bpytop`?

**Comment by LovesTha** [comment]
(As would a non snap package so it works on systems that snap doesn't work on (like where ~ isn't in /home) )

**Comment by LovesTha** [comment]
> > Improving the error and/or the end of install message to direct to the extra steps would be nice.
> 
> you mean like `snap info bpytop`?

Something other than reading an error hidden in a file to find something to google.
