### ISSUE TITLE
[REQUEST] change bpytop's process name from "python3" to "bpytop"

### ISSUE THREAD

**Issue by misho88** [aristocratos/bpytop#157]
**Is your feature request related to a problem? Please describe.**
I would like to see "bpytop" appear as "bpytop" in its own process list since the full argv isn't included when the terminal isn't very wide.

**Describe the solution you'd like**
I'd probably just change the shebang line to `#!/usr/bin/python3`. I can't imagine there's much of a use case where someone would both want to run this in a virtual environment and not start it as `$ python /path/to/bpytop`.

**Describe alternatives you've considered**
The "setproctitle" module can change the process title to anything. It seems like a bit of an overkill.

**Additional context**
N/A

**Comment by aristocratos** [comment]
@misho88 
I would suggest you resize your terminal instead of hardcoding the python path and making it less compatible. As example anyone manually installing on OSX and following the instructions for installing python3 with homebrew would be unable to start with just `bpytop`.
