### ISSUE TITLE
[BUG] Whitespace characters in process arguments causes rendering bug

### ISSUE THREAD

**Issue by jbenden** [aristocratos/bpytop#158]
**Describe the bug**

When displaying full process information, the process arguments field can contain whitespace characters. In turn, rendering a tab or newline causes broken output.

**To Reproduce**

It's easily seen on Void Linux, due to the runit init. Any of the runit programs will have whitespace in them.

**Expected behavior**

Strip all whitespace from the `cmd` variable around line 2445.

**Info (please complete the following information):**
 - bpytop version: `1.0.44`
 - psutil version: `5.7.0`
 - (Linux) Linux distribution and version: Void Linux, rolling release
 - Terminal used: kitty
 - Python version, `3.9.0`

**Comment by aristocratos** [comment]
@jbenden 
Should be fixed in v1.0.45

**Comment by jbenden** [comment]
Confirmed to be fixed.

Thanks!!!!
