### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShrirajHegde** [aristocratos/bpytop#159]
**Describe the bug**
pip version doesn't work in TTY
[A clear and concise description of what the bug is.]

**To Reproduce**
install with ```pip install bpytop``` and go to any TTY by ctrl+alt+f(n), try to to launch bpytop
[Steps to reproduce the behavior:]

**Expected behavior**
Launch bpytop 

Thinks bpytop doesn't exist.(comand not found)
[A clear and concise description of what you expected to happen.]

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: 1.0.44
 - psutil version: 5.7.2(version 5.7.0 or above is required)
 - (Linux) Linux distribution and version:Ubuntu 20.04
 - (OSX/FreeBSD) Os release version:
 - Terminal used:zsh and bash on TTY
 - Font used:
 - Python version, Python 3.8.5 (version 3.6 or above is required):

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@ShrirajHegde 
Sounds like you don't have the pip user binary path `~/.local/bin` properly added to your path.
Should work if you install with `sudo`.
Anyways, not a bug.
