### ISSUE TITLE
[BUG] Memory bar does not account for 100%

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#16]
**Describe the bug**
The right edge of the bar overlaps the 1 in "100%"

![Screenshot from 2020-08-04 08-09-56](https://user-images.githubusercontent.com/17794391/89298067-71891080-d62a-11ea-9f7b-24be12af54d3.png)

(double checked and this is a bashtop problem too)

Edit: I just checked and it seems to be a problem with my font choice (Ubuntu Mono). Do you have a recommended font?

**Comment by aristocratos** [comment]
Yeah, ubuntu mono can be weird with the sizing of certain symbols. I mostly use Envy Code R patched with Nerd font symbols. But any font that follows the specs in https://github.com/aristocratos/bpytop#prerequisites should work.
