### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhaoyidilei** [aristocratos/bpytop#160]
**Describe the bug**
When use SSH login my device, to start and run the code,  the display was not normal.

[A clear and concise description of what the bug is.]

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**
![53de05ff55b37e063c4e9cd09f510d4](https://user-images.githubusercontent.com/20200730/96992882-15fd5d80-155d-11eb-969c-e7982fcda683.png)
![e315dcbff4bda2da2b1818c7ab94cbc](https://user-images.githubusercontent.com/20200730/96992884-17c72100-155d-11eb-8dde-55bae05f24b2.png)
[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`  1.0.44
 - psutil version: `bpytop -v` (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version: Linux 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:
 - Python version, `python3 --version` (version 3.6 or above is required): 3.6.9

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@zhaoyidilei 
https://github.com/aristocratos/bpytop#prerequisites
