### ISSUE TITLE
[BUG] Division by zero error on startup

### ISSUE THREAD

**Issue by CountCypher** [aristocratos/bpytop#164]
**Describe the bug**

After launching the program and while it's doing the tasks on the splash screen it crashes.

**To Reproduce**

Launch the program.

**Expected behavior**

Not crashing while starting.

**Screenshots**

```
$ bpytop
Bpytop exited with errorcode (1). See /home/maddin/.config/bpytop/error.log for more information!

```
**Info:**
 - bpytop version: 1.0.42
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Debian 10 (Linux bananapi 4.19.62-sunxi #5.92 armv7l) 
 - (OSX/FreeBSD) Os release version: n.a.
 - Terminal used: bash
 - Font used: Overpass 11 (but this font seems to work fine with my bpytop installations on other machines)
 - Python version: 3.7.3

**Additional context**

contents of `~/.config/bpytop/error.log`:
```
25/10/20 (15:46:57) | ERROR: Data collection thread failed with exception: integer division or modulo by zero
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2598, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 2834, in _draw
    CpuBox._draw_fg()
  File "/usr/bin/bpytop", line 1756, in _draw_fg
    out += (f'{THEME.inactive_fg}   ^`  ^`  ^`  ^`  ^`{Mv.l(5)}{THEME.gradient["temp"][min_max(cpu.cpu_temp[0][-1], 0, cpu.cpu_tem$
ZeroDivisionError: integer division or modulo by zero
25/10/20 (15:46:57) | WARNING: Exiting with errorcode (1). Runtime 0:00:03
```

**Comment by aristocratos** [comment]
@CountCypher 
Firstly you'll need to update to latest version, currently 1.0.45.
Then post your error.log again if it's still crashing.

**Comment by CountCypher** [comment]
I've added Azlux's repository and upgraded to 1.0.45. Now everything works fine. Sorry for the trouble and thanks for the quick reply. :)

**Comment by aristocratos** [comment]
Np :)
