### ISSUE TITLE
[BUG] show_swap=True not working

### ISSUE THREAD

**Issue by TheCynicalLiger** [aristocratos/bpytop#167]
**Describe the bug**

Swap not showing under memory

**To Reproduce**

#* If swap memory should be shown in memory box.
show_swap=True

**Expected behavior**
this should be showing swap like bashtop does the swap does show in the disk though just not memory

**Screenshots**

![1603737745](https://user-images.githubusercontent.com/9284733/97214744-6a9e1400-17bb-11eb-9385-22ec1b128888.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.46
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Manjaro
 - Terminal used: kitty 
 - Font used: SauceCodePro Nerd Font Mono
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

**Additional context**

contents of `~/.config/bpytop/error.log`

```
26/10/20 (18:46:18) | INFO: New instance of bpytop version 1.0.46 started with pid 387726
26/10/20 (18:46:18) | INFO: Loglevel set to DEBUG
26/10/20 (18:46:18) | DEBUG: Using psutil version 5.7.2
26/10/20 (18:46:18) | DEBUG: CMD: /usr/bin/bpytop --debug
26/10/20 (18:46:19) | DEBUG: Collect and draw completed in 0.265864 seconds
26/10/20 (18:46:20) | DEBUG: Init completed in 2.388917 seconds
26/10/20 (18:46:23) | INFO: Exiting. Runtime 0:00:06 

```

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by TheCynicalLiger** [comment]
this is also an issue with the arch aur package bpytop-git so its not the release thats broken

**Comment by aristocratos** [comment]
@TheCynicalLiger 
Press `s` as in swap.

**Comment by TheCynicalLiger** [comment]
oh ok that works :+1:
