### ISSUE TITLE
[BUG] invalid Core(n) temperature value

### ISSUE THREAD

**Issue by grayich** [aristocratos/bpytop#173]
invalid Core temperature value

bpytop shows:
`CPU - 29°С`
`C1 - 29°С`
`C2 - 34°С` 
    

at the same time 
```
>>> psutil.sensors_temperatures()
{'atk0110': [shwtemp(label='CPU Temperature', current=29.0, high=60.0, critical=95.0), shwtemp(label='MB Temperature', current=28.0, high=45.0, critical=95.0)], 'coretemp': [shwtemp(label='Core 0', current=34.0, high=76.0, critical=100.0), shwtemp(label='Core 1', current=31.0, high=76.0, critical=100.0), shwtemp(label='Core 0', current=34.0, high=76.0, critical=100.0), shwtemp(label='Core 1', current=31.0, high=76.0, critical=100.0)]}
```
i.e. 
`'CPU Temperature', current=29°С`
`'Core 0', current=34°С`
`'Core 1', current=31°С`

turns out:
`CPU <  'CPU Temperature'`
`С1 < 'CPU Temperature'`
`C2 < 'Core 0'`
**Core 1 lost!**
___
bpytop version: 1.0.47
psutil version: 5.7.2

**Comment by aristocratos** [comment]
@grayich 
Fixed in v1.0.48
