### ISSUE TITLE
[REQUEST] allow synchronizing update intervals with the clock

### ISSUE THREAD

**Issue by SirNapkin1334** [aristocratos/bpytop#175]
**Is your feature request related to a problem? Please describe.**
Long time bashtop user, discovered bpytop about 20 minutes ago, and really linking it so far. However, I do have a few gripes with it, which I'll put into different issues. Anyways, the ability to synchronize the graph updates to the clock would be nice. I have my clock display in a manner very close to that of ISO 8601, including seconds, and I had the idea to set the interval time to 1000ms so that it updates whenever the seconds changes. Unfortunately, the interval seems to synchronize with when you open the program, meaning that while it updates every second, it doesn't update *on* the second, which just looks off.

**Describe the solution you'd like**
The ability to optionally, instead of using an interval, being able to make it synchronize on the clock for when the interval time in seconds is an integer. So, if `interval % 1000 == 0`, allow the option to synchronize it to the clock, so that it is updated when the seconds on the clock change. I suppose masochists could allow synchronizing it on other things, like the minute.

**Describe alternatives you've considered**
Honestly, I can't really think of anything else, this is a pretty narrow problem with an equally narrow solution.

**Additional context**
I think what I've said is pretty concise. If you need, I can post some media.

**Comment by aristocratos** [comment]
@SirNapkin1334 
I can add a sync if the update timer is excatly 1000ms, but note that this would result in seconds sometimes being skipped since the internal processing and interrupts will lag or speed up the timer at times.

**Comment by SirNapkin1334** [comment]
That would be nice, and worth it in my opinion. Thank you.

**Comment by aristocratos** [comment]
@SirNapkin1334 
Added in v1.0.48

**Comment by SirNapkin1334** [comment]
Works perfectly. Thanks!
