### ISSUE TITLE
[REQUEST] allow disabling the "graph merging" (don't know what to call it) feature and bring back the legacy bashtop style graph drawing

### ISSUE THREAD

**Issue by SirNapkin1334** [aristocratos/bpytop#176]
**Is your feature request related to a problem? Please describe.**
Sorry for the bad title, I just don't know how to describe it. In bashtop, whenever the graph is updated, all of the existing graph parts are shifted over by exactly one. In bpytop however, it makes better use of the braille symbols, making it that sometimes the columns are sort of "merged" together and use a different braille symbol. However, for me, and probably a lot of other people (I know it's at least 2 other people), the braille symbols don't work properly, just displaying as big blocks basically. Now, I don't have a problem with this (and am also too lazy to try to fix it), however it just doesn't look good when this graph merging happens, since you're basically just losing parts of the graph at random.

**Describe the solution you'd like**
The ability to toggle between this new graph merging and the legacy non-merging graph drawing styles.

**Describe alternatives you've considered**
I suppose if you wanted to you could try to put together a guide on how to fix the font issue, but that would probably be a lot of effort and require a lot of research, and would still doubtlessly not work for everyone, given the diversity of OSes that this program is made for.

**Additional context**
Now, let me say that I am ashamed of myself for this. I am deeply sorry for the phone recording of my screen, but the new nvidia drivers broke OBS recording, and it's 22:43 and I want to get this issue in before I go to sleep. Also I had to upload it to imgur because when I converted it to GIF (because Github doesn't like MOV), apparently the 3MB file was simply too far over github's 10MB file size limit (?????).

bpytop on the top, bashtop on the bottom.
[https://i.imgur.com/4o59tkh.mp4]()

**Comment by aristocratos** [comment]
@SirNapkin1334 
> ...the braille symbols don't work properly...
> (and am also too lazy to try to fix it)

I mean, it is mentioned in the readme prerequisites that a font with the braille characters is required.
There also is links to some fixes in the same section.

I can add some links to some fonts that have the braille characters included, but sorry, I'm not gonna spend my time coding to accommodate people who don't wanna spend their own time fixing issues on their own systems.

**Comment by aristocratos** [comment]
@SirNapkin1334 
Added link to https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Terminus/terminus-ttf-4.40.1 in https://github.com/aristocratos/bpytop#prerequisites
