### ISSUE TITLE
[BUG] Incorrect sorting by Mem% usage and maybe CPU usage

### ISSUE THREAD

**Issue by ergoz** [aristocratos/bpytop#18]
**Describe the bug**

Incorrect sorting by Mem% usage and maybe CPU usage

**To Reproduce**

Install latest version from git and run. Memory usage of process should be > 10% to see bug. I think that problem is in string sorting, not integer sorting.

**Expected behavior**

In attached screenshot process with pid 16518 should be first

![https://i.imgur.com/rSyDfBa.jpg](https://i.imgur.com/rSyDfBa.jpg)

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: 1.0.2
 - psutil version: 5.7.2
 - python3 --version - Python 3.7.8
 - uname -a
```
Linux localhost.localdomain 5.7.9-gentoo #2 SMP Wed Jul 22 00:10:11 MSK 2020 x86_64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz GenuineIntel GNU/Linux
```

**Comment by aristocratos** [comment]
Noticed I had string conversions on both memory and threads in the precompiled sorting expressions.

I'm not sure why I put them there though, but doesn't seem to break anything...

Fixed in v1.0.3
