### ISSUE TITLE
No "Shows current read and write speeds for disks" on macOS

### ISSUE THREAD

**Issue by florian-obradovic** [aristocratos/bpytop#180]
Hey, 
thx for this great tool.

I'm not sure if I'm doing something wrong but I can find the feature "Shows current read and write speeds for disks".

**Screenshots**
![image](https://user-images.githubusercontent.com/57985125/97790182-b808ef80-1bc6-11eb-9818-ec4ea1b1c67e.png)

**Info (please complete the following information):**
bpytop -v
bpytop version: 1.0.48
psutil version: 5.7.3

 - (OSX/FreeBSD) Os release version: 10.15.7 (19H2)
 - Terminal used: iterm
- python 3.9.0
**Additional context**

➜  ~ cat ~/.config/bpytop/error.log
31/10/20 (21:59:07) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2606, in _runner
    else: Draw.out()
  File "/usr/local/bin/bpytop", line 955, in out
    cls.now(out)
  File "/usr/local/bin/bpytop", line 903, in now
    print(*args, sep="", end="", flush=True)
OSError: [Errno 5] Input/output error
31/10/20 (21:59:07) | ERROR: Input thread failed with exception: (25, 'Inappropriate ioctl for device')
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 821, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 869, in _get_key
    input_key = ""
  File "/usr/local/bin/bpytop", line 662, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (25, 'Inappropriate ioctl for device')

**Comment by aristocratos** [comment]
@florian-obradovic 
![97790182-b808ef80-1bc6-11eb-9818-ec4ea1b1c67e](https://user-images.githubusercontent.com/59659483/97790282-9825fb80-1bc7-11eb-8011-4bdd994196a4.png)

**Comment by florian-obradovic** [comment]
Thx mate! I knew it, too blind.

**Comment by aristocratos** [comment]
:)
