### ISSUE TITLE
Fail to launch after update

### ISSUE THREAD

**Issue by denningsrogue** [aristocratos/bpytop#182]
After updating bpytop from 1.0.47 to 1.0.48, I get the following error:

31/10/20 (11:26:40) | ERROR: Data collection thread failed with exception: integer division or modulo by zero
Traceback (most recent call last):
File "/home/denningsrogue/.pyenv/versions/3.8.6/lib/python3.8/site-packages/bpytop.py", line 2600, in _runner
collector._draw()
File "/home/denningsrogue/.pyenv/versions/3.8.6/lib/python3.8/site-packages/bpytop.py", line 2864, in _draw
CpuBox._draw_fg()
File "/home/denningsrogue/.pyenv/versions/3.8.6/lib/python3.8/site-packages/bpytop.py", line 1752, in _draw_fg
out += (f'{THEME.inactive_fg} ⡀⡀⡀⡀⡀{Mv.l(5)}{THEME.gradient["temp"][min_max(cpu.cpu_temp[0][-1], 0, cpu.cpu_temp_crit) * 100 // cpu.cpu_temp_crit]}{Graphs.temps[0](None if cls.resized else cpu.cpu_temp[0][-1])}'
ZeroDivisionError: integer division or modulo by zero
31/10/20 (11:26:40) | WARNING: Exiting with errorcode (1). Runtime 0:00:04

This is happening on 3 of 3 machines running freebsd 12.2, 1 of 3 machines running Ubuntu 20.10 and 1 of 1 machines running Redhat 8.2.

**Comment by aristocratos** [comment]
Please follow the bug reporting template https://github.com/aristocratos/bpytop/issues/new?assignees=aristocratos&labels=bug&template=bug_report.md&title=%5BBUG%5D

**Comment by aristocratos** [comment]
@denningsrogue 
Should be fixed in v1.0.49
