### ISSUE TITLE
Program failes to exit completely on q or interrupt

### ISSUE THREAD

**Issue by ShrirajHegde** [aristocratos/bpytop#183]
Describe the bug

**Pressing "q" or "ctrl+c" fails to completely close the program**

[A clear and concise description of what the bug is.]

### Pressing "q" or "ctrl+c" fails to completely close the program, only TUI window gets closed, the process stays alive in the terminal (without TUI) 

**To Reproduce**
run bpytop (issue exists in 1.0.49 but I guess this has been happening since 47)
[Steps to reproduce the behavior:]
run bpytop then press q or ctrl+c
**Expected behavior**

pressing "q" or ctrl+c exits the program completely

**Screenshots**
after launching and pressing q (or ctrl+c)
![image](https://user-images.githubusercontent.com/66936172/97805931-0bd70f80-1c7f-11eb-8012-cd51318ada01.png)

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`  bpytop version: 1.0.49
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) psutil version: 5.7.3
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Zsh on terminator
 - Font used: MesloLGS
 - Python version, `python3 --version` (version 3.6 or above is required):Python 3.8.5

**Additional context**

contents of `~/.config/bpytop/error.log`
25/10/20 (16:05:51) | INFO: Loglevel set to INFO
25/10/20 (16:05:51) | INFO: Loglevel set to DEBUG
25/10/20 (16:05:53) | INFO: Loglevel set to INFO
01/11/20 (20:19:34) | INFO: New instance of bpytop version 1.0.49 started with pid 50725
01/11/20 (20:19:34) | INFO: Loglevel set to DEBUG
01/11/20 (20:19:34) | DEBUG: Using psutil version 5.7.3
01/11/20 (20:19:34) | DEBUG: CMD: /usr/local/bin/bpytop --debug
01/11/20 (20:19:34) | DEBUG: Collect and draw completed in 0.113417 seconds
01/11/20 (20:19:34) | DEBUG: Init completed in 0.125621 seconds
01/11/20 (20:19:36) | INFO: Exiting. Runtime 0:00:02 

01/11/20 (20:19:38) | INFO: Exiting. Runtime 0:00:04 

(try running bpytop with `--debug` flag if error.log is empty)

###  **Notice the double exit times (one is the q and another is force interrupt)**

**Comment by aristocratos** [comment]
@ShrirajHegde 
Does this happen this happen if you set "Update check" to "false" in the options or wait more than 5 seconds before quitting?

If not, it's the update checker that's waiting to timeout either due to no internet connection or slow internet connection. The update checker runs in a separate thread and will timeout after 5 seconds if connection fails.

**Comment by ShrirajHegde** [comment]
Yes, it's the update check(it was on), sorry for disturbing 😅

The process quits after like 10 seconds probably after getting a response from server.

**Comment by aristocratos** [comment]
No problem :)
