### ISSUE TITLE
[BUG] CPU package temp @ 1000°C

### ISSUE THREAD

**Issue by alexcoe** [aristocratos/bpytop#185]
**Describe the bug**

CPU temperature displays as 1000c 

**To Reproduce**

run bpytop

**Screenshots**

https://i.imgur.com/SLmIx5G.png

**Info (please complete the following information):**
 - bpytop version: 1.0.49
 - psutil version: 5.7.3
 
**Additional context**

>>> psutil.sensors_temperatures()
{'acpitz': [shwtemp(label='', current=8.3, high=31.3, critical=31.3)], 'coretemp': [shwtemp(label='Core 0', current=38.0, high=87.0, critical=103.0), shwtemp(label='Core 1', current=38.0, high=87.0, critical=103.0), shwtemp(label='Core 2', current=40.0, high=87.0, critical=103.0), shwtemp(label='Core 3', current=37.0, high=87.0, critical=103.0), shwtemp(label='Core 0', current=35.0, high=87.0, critical=103.0), shwtemp(label='Core 1', current=29.0, high=87.0, critical=103.0), shwtemp(label='Core 2', current=34.0, high=87.0, critical=103.0), shwtemp(label='Core 3', current=33.0, high=87.0, critical=103.0), shwtemp(label='Core 0', current=38.0, high=87.0, critical=103.0), shwtemp(label='Core 1', current=38.0, high=87.0, critical=103.0), shwtemp(label='Core 2', current=40.0, high=87.0, critical=103.0), shwtemp(label='Core 3', current=37.0, high=87.0, critical=103.0), shwtemp(label='Core 0', current=35.0, high=87.0, critical=103.0), shwtemp(label='Core 1', current=29.0, high=87.0, critical=103.0), shwtemp(label='Core 2', current=34.0, high=87.0, critical=103.0), shwtemp(label='Core 3', current=33.0, high=87.0, critical=103.0)]}
>>>

**Comment by aristocratos** [comment]
@alexcoe 
Fixed in v1.0.50
Should also hopefully pick up core temps for your secondary cpu now.
The CPU package temp will be calculated from the average of all cores if missing.

**Comment by alexcoe** [comment]
Brilliant, thank you.
