### ISSUE TITLE
[BUG] CPU Temps report 1000C - amazing :P

### ISSUE THREAD

**Issue by kz6fittycent** [aristocratos/bpytop#187]
**Describe the bug**
`bpytop` is reporting that my CPU is operating at 1000C. 

This is with the snap, so this COULD be an issue with the snap but unlikely. 

**To Reproduce**

Start `bpytop` and enable "Check Temp"

I've tried disabling "Check Temp" and then re-enabling and I get the same result. 

**Expected behavior**

Show correct temps. 

**Screenshots**

![Screenshot from 2020-11-05 09-35-49](https://user-images.githubusercontent.com/14829816/98262189-ee3dca80-1f4a-11eb-89d2-1d46f48cf55e.png)

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) 

```
snap info bpytop: 
tracking:     latest/stable
refresh-date: 2 days ago, at 20:27 CST
channels:
latest/stable:    1.0.49 2020-11-04 (159) 278kB -
installed: 1.0.49 (159) 278kB -
```
---

Info from bpytop's output: 
```
bpytop version: 1.0.49
psutil version: 5.7.3
```
 
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - Terminal used: Terminator
 - Font used: `Fira Mono Regular`
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

**Additional context**

contents of `~/.config/bpytop/error.log` - 

```
5/11/20 (09:43:43) | INFO: New instance of bpytop version 1.0.49 started with pid 297473
05/11/20 (09:43:43) | INFO: Loglevel set to DEBUG
05/11/20 (09:43:43) | DEBUG: Using psutil version 5.7.3
05/11/20 (09:43:43) | DEBUG: CMD: /snap/bpytop/159/usr/bin/bpytop --debug
05/11/20 (09:43:44) | DEBUG: Collect and draw completed in 0.038150 seconds
05/11/20 (09:43:45) | DEBUG: Init completed in 2.372883 seconds
05/11/20 (09:44:35) | INFO: Exiting. Runtime 0:00:52 
```

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@kz6fittycent 
This was fixed in 1.0.50
https://github.com/aristocratos/bpytop/issues/185

**Comment by kz6fittycent** [comment]
That's odd that snapcraft.io didn't pick up that trigger and build the new version. I've manually triggered a new build - will report back. Sorry I didn't see that fix.

**Comment by aristocratos** [comment]
@kz6fittycent 
Np, and 1000C value is just a placeholder value so no need to worry that your cpu is melting :)

**Comment by kz6fittycent** [comment]
While I've got you - do you want to add this to your your README? 
```
[![bpytop](https://snapcraft.io//bpytop/badge.svg)](https://snapcraft.io/bpytop) 
```

It'll show users which version is actually published in the snap store - and maybe cue you if I need to take action, as I've obviously missed your latest release...and so did the build service.

**Comment by kz6fittycent** [comment]
Yep, let's close this issue - the latest version is building now.

**Comment by aristocratos** [comment]
@kz6fittycent 
> While I've got you - do you want to add this to your your README?

Sure.

Is the builds triggered on any commit? Since the last commit pushed was just a README update and the "latest/edge" seems to have that commit id in the version.
Is it possible to always grab latest tag instead, since the latest tag will always be the latest released version and there might be commits not yet released yet pushed to the repository.

**Comment by kz6fittycent** [comment]
It's triggered by any commit against the branch it's tied to. There might be a way to force to only trigger on a specific tag but I've never seen "how" --documentation is a little lacking from the good folks at Canonical. I'll ask in the forum and see what they say. In any case, it's really not an issue as the build service is setup specifically for this use-case.

**Comment by aristocratos** [comment]
@kz6fittycent 
Ah ok, that might trigger a lot of unnecessary builds though.

Is there any way to customize the snapcraft badge? To get it something like: https://img.shields.io/badge/snap-v1.0.50-blue
That way I could put it at the top next to the pypi version badge.

**Comment by kz6fittycent** [comment]
Good question, they only provide 2 markdown versions in the publicize tab: 

[![bpytop](https://snapcraft.io/bpytop/badge.svg)](https://snapcraft.io/bpytop)
[![bpytop](https://snapcraft.io/bpytop/trending.svg?name=0)](https://snapcraft.io/bpytop) 

What did you do to make it look like that?

**Comment by kz6fittycent** [comment]
I'll add a feature request - this seems like it might be helpful to developers managing several deployments.

**Comment by aristocratos** [comment]
Hey, is it trending? :)

Guess it's just a static image generated.

> What did you do to make it look like that?

Just generated a manual badge at https://shields.io/

**Comment by kz6fittycent** [comment]
`bashtop` is smashing it: Weekly active devices - 13,295

`bpytop` is running around 5400 installations globally. It was featured in the Snapcraft store on the front page - so was `bashtop`

I've asked them to provide that badge for devs - we'll see if they do it.

**Comment by aristocratos** [comment]
Oh nice, had no idea :D

Added the badge to README.md
