### ISSUE TITLE
[BUG] CPU temp readings shift to the right, hiding the number.

### ISSUE THREAD

**Issue by kevinsmia1939** [aristocratos/bpytop#188]
**Describe the bug**

CPU temp readings shift to the right, hiding the number.

**To Reproduce**

Just start bpytop

**Expected behavior**
The temp number should not shift to the right.

**Screenshots**

https://imgur.com/01yctqO

**Info (please complete the following information):**
bpytop version: 1.0.49
psutil version: 5.7.2

Operating System: openSUSE Tumbleweed 20201030
KDE Plasma Version: 5.20.2
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.9.1-1-default
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

Terminal used: Konsole 20.08.2
Font used: Hack (also tried monospace, same issue)
Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

**Comment by aristocratos** [comment]
@kevinsmia1939 
https://github.com/aristocratos/bpytop#prerequisites

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939
> https://github.com/aristocratos/bpytop#prerequisites

Turn off Bi-Directional text rendering fix it, thanks.

**Comment by aristocratos** [comment]
No problem :)
