### ISSUE TITLE
[REQUEST] Temperature in fahrenheit 

### ISSUE THREAD

**Issue by wrtechnopath** [aristocratos/bpytop#191]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To be able to use an option to display temperatures in fahrenheit

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aristocratos** [comment]
@wrtechnopath 
Why?

**Comment by wrtechnopath** [comment]
I don't use metric often

**Comment by aristocratos** [comment]
@wrtechnopath 
Centigrade is the standard for measuring temperatures in computing unless you're working with quantum computers in which case you might be using Kelvin instead.

So unless you have a better reason than "I don't use metric often" or other people show an interest in this, it's unlikely it will be implemented.

**Comment by yochananmarqos** [comment]
How about because over 300 million people use Fahrenheit in the United States?

**Comment by aristocratos** [comment]
@yochananmarqos 
So you shouldn't have a problem to find a python programmer that agrees with this point and can submit a pull request with all the needed changes then?

**Comment by yochananmarqos** [comment]
@aristocratos Touché.

**Comment by aristocratos** [comment]
@yochananmarqos 
Look, I can reopen the issue if it's something you feel strongly about? But it will still be at the bottom of my priority list, so your hope would be that someone else takes it upon themself.

**Comment by virtadpt** [comment]
I've got some conversion code already, let me see.

**Comment by yochananmarqos** [comment]
@virtadpt Have you had a chance to take a look?

**Comment by aristocratos** [comment]
@yochananmarqos 
Actually forgot to reopen this, anyways will add options for Celsius, Fahrenheit and Kelvin in next update, might go crazy and also add the Rankine scale :)

**Comment by aristocratos** [comment]
@yochananmarqos @wrtechnopath 
Added in v1.0.63
