### ISSUE TITLE
[BUG] Garbled Text and colours on screen

### ISSUE THREAD

**Issue by roysubs** [aristocratos/bpytop#196]
**Describe the bug**

Garbled output compared to the screenshots that I have seen.

**To Reproduce**

Minimal CentOS, connect via putty, sudo yum install bpytop.

**Expected behavior**

I have installed bashtop or bpytop (on a minimal CentOS install) but I just get a jumbled mess of colour blocks on the screen. I've made sure to do sudo yum upgrade and rebooted, but still garbled output. htop / mc work fine (I guess they use ncurses?). Can someone advise on what I could maybe look at to get bashtop / bpytop working? Maybe I'm missing some essential packages, or a Putty setting is required to get apps like these to render properly?

**Screenshots**

I will add one.

**Info (please complete the following information):**
 - bpytop version: bpytop version: 1.0.44 psutil version: 5.6.3
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) I see that I'm on 5.6.3, but how do I update? I tried pip install -upgrade psutil and still I am on 5.6.3
 - (Linux) Linux distribution and version: CentOS 8
 - Terminal used: Putty
 - Font used: Consolas
 - Python version, 3.6.8 (version 3.6 or above is required):

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by Ds886** [comment]
I am not sure what was the original output.

I've installed a clean install of CentOS 8.2 minimal  with some sizes it seems OK
![bpytop](https://user-images.githubusercontent.com/2217864/99005698-eb923500-2549-11eb-88c1-fe5b25f552aa.jpg)

But with larger it appears like the CPU and it's graph is not scaling to the window's size compared to videos which would hurt usability in case I would have use it.
![bpytoplarger](https://user-images.githubusercontent.com/2217864/99006009-796e2000-254a-11eb-9152-24c8ece487ae.jpg)

I was able to replicate some weird artifacting on Konsole just for reference but not testing here the case above.
bpytop version: 1.0.50
psutil version: 5.7.3
same font as in the description but saw it on other fonts

![bpytopload](https://user-images.githubusercontent.com/2217864/99007307-9c99cf00-254c-11eb-8e4f-624321e80648.jpg)
![bpytopstarting](https://user-images.githubusercontent.com/2217864/99007312-9dcafc00-254c-11eb-8b9f-7780578621ad.jpg)

It looked more glaring in motion

**Comment by roysubs** [comment]
Thanks for looking. Indeed that's what I was wanting to see (and have seen on other systems).
I didn't see a button to upload an image but I see that it's paste aware, very good.

For this system, here is the loading screen:
![image](https://user-images.githubusercontent.com/16388699/99039057-eb645a80-2586-11eb-88bc-2e310cd6d5a0.png)

And here is the main screen:
![image](https://user-images.githubusercontent.com/16388699/99038572-fd91c900-2585-11eb-802e-ae6865e6b8bf.png)

Can you advise on how I can properly install psutil?
I tried **pip3 install --upgrade psutil** 

Is there another way to get **psutil** ?

Looks like something is missing that is blocking this, but bpytop works perfectly on another system that I have (also via Putty).

```
$ pip3 install --upgrade psutil
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz
Installing collected packages: psutil
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3xftyk1u/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0600kmr2-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3xftyk1u/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0600kmr2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3xftyk1u/psutil/

```

**Comment by CodeLongAndProsper90** [comment]
This might be that your terminal only supports basic ANSI, what does this output:
```awk
awk 'BEGIN{                                                                                                                                                                                                                         ─╯
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
And this:
```
for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done
```

**Comment by Ds886** [comment]
could be an issue  also with the color configuration in the .Xresources based on your screenshots 
there is some test for it with the following util
https://askubuntu.com/questions/821157/print-a-256-color-test-pattern-in-the-terminal
I really like mobaxterm as an ssh client not user about the support of Microsoft terminal for colors. now windows support ssh natively so i guess it open quite a lot

**Comment by roysubs** [comment]
First script shows this:

awk: cmd. line:1: BEGIN{                                                                                                                                                                                                                         ─╯
awk: cmd. line:1:                                                                                                                                                                                                                                ^ invalid char '▒' in expression
awk: cmd. line:1: BEGIN{                                                                                                                                                                                                                         ─╯
awk: cmd. line:1:                                                                                                                                                                                                                                ^ syntax error

![image](https://user-images.githubusercontent.com/16388699/99457852-eeb36980-292b-11eb-8ba4-aa67d2bd9c53.png)

Second script shows this:

![image](https://user-images.githubusercontent.com/16388699/99457948-11458280-292c-11eb-8ee0-3e8f77e12b59.png)

I'm using Putty, you think that Putty has issues here. Good idea to try Kitty though.

oh ... I just went back to trying bpytop and the problem has resolved itself. I have no idea how or why, the problem was there for over a week across multiple reboots. I'm happy it's working, but sad that never found out the cause. Maybe running your scripts fixed it, or maybe some other package that I installed provided libraries that it used.

**Comment by CodeLongAndProsper90** [comment]
The first bit was a copypaste error, remove those. But the problem was, I think, that putty didn't support true color

**Comment by Altimitrus** [comment]
use  key "-lc"

**Comment by prolifick1** [comment]
> use key "-lc"

this solution worked for me. Many people are recommending to install tmux just to run bpytop off it

**Comment by LeanderFischer** [comment]
> use key "-lc"

Yes, using `--low-color` works like a charm for me, too, thanks!
