### ISSUE TITLE
[REQUEST] accurate CPU speed on macOS

### ISSUE THREAD

**Issue by juanejot** [aristocratos/bpytop#198]
I don't know if this will require an external solution such as the good one for CPU temperatures, but the CPU speed for the current PyPi build (at least from 1.0.46 through 1.0.50) of bpytop on macOS (10.15.y through 11.x.y, pip3 installed via brew) has always been stuck at the processor's base frequency, not whatever frequency at which the CPU may currently be running.  The same PyPi build on Ubuntu 20.04 or 20.10 works as expected, always accurately reflecting the current CPU frequency, on the same hardware (either OS bare metal, not virtualized).

**Comment by aristocratos** [comment]
@juanejot 
From https://psutil.readthedocs.io/en/latest/#psutil.cpu_freq :
> On Linux current frequency reports the real-time value, on all other platforms it represents the nominal “fixed” value.

Open a request in https://github.com/giampaolo/psutil for real-time updates on OSX.

**Comment by juanejot** [comment]
Thanks. Unfortunately, it looks like only users who have contributed to psutil in the past can post issues. Good to know from his documentation that it's an expected behavior, anyway.  I wonder if he'll address cpu_freq on macOS in a future update, as it looks like he unified cpu_freq to work properly on all (known) Linux distros as of his 4.1.0 release.

Thanks again!

**Comment by aristocratos** [comment]
@juanejot
> Unfortunately, it looks like only users who have contributed to psutil in the past can post issues.

That's hopefully just temporary.

> Good to know from his documentation that it's an expected behavior, anyway.

I'm guessing this is for a good reason on OSX and BSD, like there not being any easy and/or reliable way of retrieving that info.
And I don't think I can investigate this very well either since I don't have a real mac (wouldn't wanna trust hardware info on an virtualized system).

**Comment by juanejot** [comment]
There is also the added wrinkle that while macOS is running on bare metal, it is not necessarily running on a Mac. *cough, Hack.* But I can imagine that that just opens its own can of worms, so I'll just thank you for your correspondence so far, and will watch with interest the development of both bpytop and psutil!
