### ISSUE TITLE
[REQUEST] Add power consumption monitoring

### ISSUE THREAD

**Issue by bphd** [aristocratos/bpytop#199]
It's maybe the less useful for people so it should appear the last when you size up the window, but I find it definitely useful and not so difficult to create

**Comment by aristocratos** [comment]
This is a really vague request, assuming you mean power consumption for laptops see https://psutil.readthedocs.io/en/latest/#psutil.sensors_battery for what stats are available.

**Comment by bphd** [comment]
Why only for laptops? On desktop, you could measure if your overclock and whatever else pump a lot, like a sort of very simple benchmarking
With some key values and measure over time with a plot it can be cool, isn't it?

**Comment by aristocratos** [comment]
> you could measure if your overclock and whatever else pump a lot, like a sort of very simple benchmarking

And how would you do that?

Again, available stats are in https://psutil.readthedocs.io/en/latest if you want custom functionality you're gonna have to write it yourself or at least reference any open source program that does this.
