### ISSUE TITLE
Text moving around and cut off on the right margin

### ISSUE THREAD

**Issue by ioogithub** [aristocratos/bpytop#207]
**Describe the bug**

Two formatting issues:
1. The second digit of the temperature is always cut off for the upper right core (i.e. instead of "43" I see all the temperatures as "4"

2. The digits under CPU% are dancing around. They should be right aligned but they move 1-3 spaces. The issue seems to be related to the graph which is drawn just to the left of them. When there are history dots the digits are pushed to the left, when there isn't they move to the right.

**To Reproduce**

All I did was install the app and open it for the first time. These two issues are present when the window is maximized or when it is minimizes.

**Expected behavior**
The information displayed should be stable, not moving around inside the boxes.

**Info (please complete the following information):**
 - bpytop version:1.0.50
 - psutil version: 5.7.3
 - (Linux) Linux distribution and version: KDE Neon 5.20.3
 - (OSX/FreeBSD) Os release version: Linux
 - Terminal used: Konsole
 - Font used: Hack 11pt
 - Python version, 3.8.5

**Additional context**
All of the left aligned boxes seem to render the information fine. It is anything right aligned where the text dances around and does not stay in place or is cut off.

Resizing the window has no effect as the formatting seems fixed inside the sub-sections.

**Comment by aristocratos** [comment]
@ioogithub 
https://github.com/aristocratos/bpytop#notice-text-rendering-issues
