### ISSUE TITLE
[BUG] Network tab not working on MacOs

### ISSUE THREAD

**Issue by Seluj78** [aristocratos/bpytop#209]
**Describe the bug**

The network square doesn't display anything

**To Reproduce**

- Be on MacOS 10.14.6
- Use iterm
- pip3 install bpytop
- run it

**Screenshots**

![Screenshot 2020-12-09 at 23 53 25](https://user-images.githubusercontent.com/4641317/101698430-bd850f80-3a79-11eb-9910-d77d68699680.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.50
 - psutil version: 5.7.3
 - (OSX/FreeBSD) Os release version: 10.14.6
 - Terminal used: Iterm
 - Font used: ?
 - Python version: 3.9.0

**Additional context**

contents of `~/.config/bpytop/error.log` : 

```
09/12/20 (23:54:31) | INFO: New instance of bpytop version 1.0.50 started with pid 8457
09/12/20 (23:54:31) | INFO: Loglevel set to DEBUG
09/12/20 (23:54:31) | DEBUG: Using psutil version 5.7.3
09/12/20 (23:54:31) | DEBUG: CMD: /usr/local/bin/bpytop --debug
09/12/20 (23:54:33) | DEBUG: Collect and draw completed in 0.096400 seconds
09/12/20 (23:54:35) | DEBUG: Init completed in 3.155746 seconds
09/12/20 (23:54:42) | INFO: Exiting. Runtime 0:00:11
```

**Comment by aristocratos** [comment]
@Seluj78
Are you monitoring the correct network interface? 
If so, try running with `sudo`, OSX can finicky with the privileges for system monitoring.

**Comment by Seluj78** [comment]
Indeed, `sudo` seems to do the trick ! Thanks!
