### ISSUE TITLE
[BUG] tree + info + filter = crash

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/bpytop#21]
if i use tree and check information on something then use the filter seems to crash
`04/08/20 (17:52:49) | ERROR: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2449, in _collect_temps
    cls.cpu_temp_high, cls.cpu_temp_crit = round(entry.high), round(entry.critical)
TypeError: type NoneType doesn't define __round__ method
04/08/20 (17:53:02) | ERROR: Data collection thread failed with exception: __init__() missing 1 required positional argument: 'pid'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2328, in _runner
    collector._collect()
  File "/usr/local/bin/bpytop", line 2931, in _collect
    if not c_pid in cls.processes: raise psutil.NoSuchProcess
TypeError: __init__() missing 1 required positional argument: 'pid'
`

**Comment by drazil100** [comment]
Seems tree is not a requirement. The bug is caused when you try to type a filter while the info pane is open.

**Comment by bgkillas** [comment]
seems i got it wrong
tree actually makes it better it seems
the problem seems to be if the process is not displayed in the proc list and that process info bar is opened it crashes

**Comment by bgkillas** [comment]
looking at the error log it makes sense 
"TypeError: __init__() missing 1 required positional argument: 'pid'"
it wasent expecting to lose the pid ig since its not being killed its just not being shown something

**Comment by drazil100** [comment]
I did additional testing. If the process you have the info open on is closed externally it also crashes.

**Comment by aristocratos** [comment]
This happens because I'm reusing values from the regular process list in the info box and if the filtering excludes the process in the info box it crashes...

Have added a check to re-fetch any missing values , will be in next update later today.

**Comment by aristocratos** [comment]
> "TypeError: init() missing 1 required positional argument: 'pid'"

That was actually caused by me not including the pid when raising an exception for a killed process, which proved to be bad thinking even if had written it correct, since the process wasn't killed but just filtered out...

**Comment by aristocratos** [comment]
Also noticed another mistake in temperature collection from your error.log, although not critical, but will also be fixed in next update.

**Comment by aristocratos** [comment]
Fixed in v1.0.4

**Comment by bgkillas** [comment]
dident seem to fix it for me
what i did both tree and non tree
select say Web Content (firefox) hit enter for info hit f to search then type anything besides "Web Content" or what ever process name you chose

**Comment by aristocratos** [comment]
I meant

Fixed in v1.0.5

:)

**Comment by bgkillas** [comment]
ah yes of course
