### ISSUE TITLE
ERROR: Data collection thread failed with exception: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by haxardagron** [aristocratos/bpytop#212]
Getting this issue on my MacBook Air M1. It was running fine for a few hours initially after a fresh restore, but stops immediately with this log output when run for some time after a fresh OS install:

/Users/hax/.config/bpytop/error.log content:

```
16/12/20 (00:15:07) | ERROR: Data collection thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "./bpytop.py", line 2599, in _runner
    collector._collect()
  File "./bpytop.py", line 3259, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + (["memory_info"] if CONFIG.proc_mem_bytes else []), err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 1437, in process_iter
    yield add(pid)
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 1414, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 523, in as_dict
    ret = meth()
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 622, in name
    cmdline = self.cmdline()
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/__init__.py", line 675, in cmdline
    return self._proc.cmdline()
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/hax/Library/Python/3.8/lib/python/site-packages/psutil/_psosx.py", line 429, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
16/12/20 (00:15:07) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 
```

Reproduction:

- Download zip or clone through git onto a Apple Silicon system
- Upgrade pip, and install psutil
- run bpytop directly from the directory from either bash or zsh
- wait until it errors out with (it happened while I wasn't looking)
- It will no longer run and error out during load

bpytop version: 1.0.50
psutil version: 5.7.3
Darwin Melchior.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
Mac OS 11.1 
iTerm and Terminal used with Monaco 12 and 16 pt
Python 3.8.2

**Comment by aristocratos** [comment]
@haxardagron 
`psutil` has only support for x86 OSX right now, until that changes the same goes for bpytop.
It might work if you install x86 version of python3 and run bpytop with rosetta 2.

I'll be getting a Mac Mini M1 by the end of the week, so can experiment and write a guide if it works well under rosetta.

**Comment by haxardagron** [comment]
Aha I suspected something like that. 

In case you will need a fresh install, there's an error when resetting to defaults, and I needed to use the Apple Configurator tool for it: https://support.apple.com/en-us/HT211983 Hopefully it doesn't do this but just in case.

**Comment by aristocratos** [comment]
@haxardagron 
The issues are fixed in latest version of `psutil` (5.8.0).
Try upgrading psutil with `sudo pip3 install psutil --upgrade` and it should work for you.

**Comment by haxardagron** [comment]
Excellent its working fine now!

**Comment by Raty01** [comment]
stop

**Comment by ucodefusion** [comment]
I got the same error when i was using django tag, and use print statement before return .. 
`
@register.simple_tag
def get_setting2(key,return_data):
    try:
        if(return_data == 'image'):
    
            setting = GlobalSetting.objects.get(identifier=key)
            file_path = getattr(setting, return_data, 'None1')
            if file_path: 
                print(str(file_path))
                return "/media/" + str(file_path)
 
  
    except Exception as e:
        sys.stderr.write(f"Error printing to output: {e}\n")
        return key`
