### ISSUE TITLE
[BUG] Startup failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by BlueskyFR** [aristocratos/bpytop#213]
**Describe the bug**

After installation on Ubuntu from Azlux's repository, Bpytop fails to launch showing the following message (adding --debug does not change anything):
![image](https://user-images.githubusercontent.com/25421460/102368362-0d546100-3fbb-11eb-9e48-1c280de6ca19.png)

**To Reproduce**

```bash
# On Ubuntu 20.04 LTS
echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list
wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
sudo apt update
sudo apt install bpytop -y
bpytop
```

**Expected behavior**

Bpytop should launch without issues.

**Info (please complete the following information):**
 - bpytop version: `1.0.50`
 - psutil version: `5.7.3`
 - (Linux) Linux distribution and version: Ubuntu 20.04 LTS
 - Terminal used: Alacritty
 - Font used: idk, did not change it
 - Python version, `3.8.5`

**Additional context**

contents of `~/.config/bpytop/error.log`:
```
16/12/20 (16:15:42) | INFO: New instance of bpytop version 1.0.50 started with pid 2617161
16/12/20 (16:15:42) | INFO: Loglevel set to DEBUG
16/12/20 (16:15:42) | DEBUG: Using psutil version 5.7.3
16/12/20 (16:15:42) | DEBUG: CMD: /usr/local/bin/bpytop --debug
16/12/20 (16:15:42) | INFO: Config file malformatted or missing, will be recreated on exit!
16/12/20 (16:16:25) | INFO: New instance of bpytop version 1.0.50 started with pid 2617566
16/12/20 (16:16:25) | INFO: Loglevel set to DEBUG
16/12/20 (16:16:25) | DEBUG: Using psutil version 5.7.3
16/12/20 (16:16:25) | DEBUG: CMD: /usr/local/bin/bpytop --debug
16/12/20 (16:16:25) | INFO: Config file malformatted or missing, will be recreated on exit!
```

**Comment by aristocratos** [comment]
@BlueskyFR 
https://github.com/aristocratos/bpytop#prerequisites

> Also needs a UTF8 locale and a font that covers:
> 
>     Unicode Block “Braille Patterns” U+2800 - U+28FF
>     Unicode Block “Geometric Shapes” U+25A0 - U+25FF
>     Unicode Block "Box Drawing" and "Block Elements" U+2500 - U+259F
> 

If you are using a UTF-8 locale, then something is messed up in your python3 installation since it fails to encode unicode characters.

**Comment by BlueskyFR** [comment]
> @BlueskyFR 
> https://github.com/aristocratos/bpytop#prerequisites
> 
> > Also needs a UTF8 locale and a font that covers:
> > 
> >     Unicode Block “Braille Patterns” U+2800 - U+28FF
> >     Unicode Block “Geometric Shapes” U+25A0 - U+25FF
> >     Unicode Block "Box Drawing" and "Block Elements" U+2500 - U+259F
> > 
> 
> If you are using a UTF-8 locale, then something is messed up in your python3 installation since it fails to encode unicode characters.

It does not come from my font since I can successfully use bpytop while connected to other ssh servers on which I installed bpytop via conda

**Comment by aristocratos** [comment]
@BlueskyFR 
Font and Locale isn't the same thing. The error you are getting is because python3 is trying to use "latin-1" instead of "utf-8" to encode utf-8 characters.
If you run `locale` and the locale used for `LANG` doesn't end in `.UTF-8` you aren't using a unicode locale which is required to run bpytop.
The reason it works over ssh is probably because the remote system sets a unicode locale when connecting.
