### ISSUE TITLE
[REQUEST] Display IP address alongside / instead of interface name

### ISSUE THREAD

**Issue by delatbabel** [aristocratos/bpytop#218]
**Is your feature request related to a problem? Please describe.**
I have been looking for a resource monitor to use on multiple VM hosts, both local (virtualbox) and remote. I rarely need to log into the console on these hosts, so something that runs from the command line like bpytop works well for me. However one of the first pieces of information I need in order to be able to access the host after it starts is the IP address. This is the one piece of important information that bpytop doesn't show me.

**Describe the solution you'd like**
In the **net** section, alongside or in place of the interface name, show the IP address. In fact I rarely need the interface name, I just need its IP address. So for example replace the label in the header of the **net** section that says `<b en0 n>` with `<b 192.168.99.99 n>`.

**Describe alternatives you've considered**
I am not very conversant with Python but I guess I could start reading the docs of psutils to see if I could do this myself.

**Additional context**
N/A

**Comment by UmarJ** [comment]
You can get the interface address using `psutil.net_if_addrs()['<interface_name>'][0].address`, but I'm not sure if replacing the header label would be the best place for it.

**Comment by aristocratos** [comment]
@delatbabel
Added in v1.0.60
