### ISSUE TITLE
[REQUEST] Improving MacOS / Homebrew installation readme

### ISSUE THREAD

**Issue by andou** [aristocratos/bpytop#220]
Hi there,

please add in the documentation of [README.md](https://github.com/aristocratos/bpytop/blob/master/README.md) the command to actually [install the tool using homebrew on MacOS](https://github.com/aristocratos/bpytop/blob/master/README.md#dependencies-installation-osx):
```
brew install bpytop
``` 

Bests,
A

**Comment by aristocratos** [comment]
Added instructions for homebrew and macports.
