### ISSUE TITLE
temp issue with fresh install

### ISSUE THREAD

**Issue by Incedis** [aristocratos/bpytop#226]
Fresh install of bpytop with python. For the context, I have been using the app for a while with no issue. 
Now the temp is displaying weird temp. See picture attached. In contrast, sensors is displaying the correct temp. 

![image](https://user-images.githubusercontent.com/4778573/103439848-c617d280-4c40-11eb-824b-d8290c1b5538.png)

**Comment by aristocratos** [comment]
@Incedis 
There is a reason the bug report template exists. Luckily I can barely glimpse from your screenshot that you are using Konsole.

This is a issue with text misalignment and not a sensor issue.

From README.md https://github.com/aristocratos/bpytop#notice-text-rendering-issues
> If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix.
