### ISSUE TITLE
[BUG] CPU core usage percentage sometimes not visible

### ISSUE THREAD

**Issue by AndreiSva** [aristocratos/bpytop#228]
**Describe the bug**
The CPU core usage percentage sometimes gets covered up by the percent character making it hard to read or completely invisible. 

**To Reproduce**
Open bpytop on a computer with a high core count.

**Expected behavior**
All percentages should be visible on all processors.

**Screenshots**
![Screenshot_20210102_114625](https://user-images.githubusercontent.com/51296839/103465430-2f0a5380-4cf0-11eb-9379-c020205f57ee.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.51
 - psutil version: `5.7.3
 - (Linux) Linux distribution and version: Manjaro Linux (rolling release)
 - Terminal used: Konsole
 - Font used: Noto Mono
 - Python version, `python3 --version` (version 3.6 or above is required): 3.9.1

**Comment by aristocratos** [comment]
@AndreiSva 

https://github.com/aristocratos/bpytop#prerequisites

> If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix.

I don't get why people won't bother to read the README.md but will take the time to make a bug report.
I'm not trying to be rude, but this isn't the first time this exact issue has been reported and I'm not quite sure how to get people to read the README.

**Comment by AndreiSva** [comment]
Understood, I'll make sure to read the README next time haha.
