### ISSUE TITLE
[REQUEST] Arguments in tree view

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#23]
It would be really nice especially with mini mode and proc colors if the arguments didn't just completely go away. If you are worried about real estate it could maybe be a mini mode only thing.

At the BARE minimum it would be nice to be able to filter based on arguments even if the arguments aren't showing though. As it is right now I can filter out bpytop when not in tree view but the moment I enable tree view I lose the ability to find bpytop by filtering "bpytop"

**Comment by aristocratos** [comment]
I've added argument filtering, but I'm not sure about adding the arguments to the tree view. It gets really cluttered since the arguments string are usually really long and there aren't any columns to divide the view with before the Threads column. 

And I would rather have that view more clean to actually see the tree structure.

**Comment by aristocratos** [comment]
I gonna look in to it when I've got time, but need to redo a couple of calculations to get the widths right in that case.

**Comment by drazil100** [comment]
You have a point and I do like the look presently. Honestly just being able to filter by the arguments in tree view is enough since I can open the info on a process to see the arguments in the very rare cases where that might be necessary

**Comment by aristocratos** [comment]
Added tree argument filtering in v1.0.4

**Comment by drazil100** [comment]
Thanks! Ill leave this issue open in case you want to experiment with actually showing the arguments in tree view down the road but I am satisfied with this as is in 1.0.4 :+1:

**Comment by aristocratos** [comment]
No problem :)

Yeah, I was thinking of maybe adding a shorter snippet of the arguments enclosed in parenthesis after the name or something along those lines.

**Comment by aristocratos** [comment]
@drazil100 
Added name of the binary in parenthesis if not same as reported program name in v1.0.16

Should at least be a little help to figure out what is what when the names aren't helpful.
