### ISSUE TITLE
[REQUEST] Disk IO speed graph?

### ISSUE THREAD

**Issue by Ekleog** [aristocratos/bpytop#235]
**Is your feature request related to a problem? Please describe.**
`bpytop` already shows the disk total usage as well as the disk IO speed in small arrow pointing up/down evolving numbers.

However, while I do not really care about disk usage (it almost never changes), I do care about following IO graphs (it can help understanding while the computer is slow, if IO is saturated)

**Describe the solution you'd like**
Make it possible to replace the big graphs that show disk usage with small arrows for speed on top, by graphs like for cpu/mem/network that show disk IO speed with small numbers on top that show disk usage. Either making this configurable or the only choice depending on how you feel about it.

**Describe alternatives you've considered**
Do nothing

**Additional context**
I'm not sure there's much more I could say, apart from the fact that bpytop already looks great to me! I'm just saying this because I feel like it is the only feature missing from it for my personal usage :) 

Thank you for doing bpytop!

**Comment by aristocratos** [comment]
@Ekleog 
That's a good idea!
Could add an [io] toggle to the disks box, that switches to two graphs (for every disk) for read and write that adapts to the size of the box. And if there isn't room they can be merged in to 1 graph for combined read/write speed (per disk).

The problem would be for disks/partitions/systems that doesn't provide io stats through `psutil`.
Could possibly "create" io stats by comparing current disk usage between updates (wouldn't take into account disk caching etc, but would be better than nothing.)

Will take a look at it when I've got some time.

**Comment by Ekleog** [comment]
Great, thank you!

**Comment by aristocratos** [comment]
@Ekleog 
Added in v1.0.58

**Comment by Ekleog** [comment]
Awesome, thank you!
