### ISSUE TITLE
Package not found in Archlinux while installing using Pacman

### ISSUE THREAD

**Issue by sparkingdark** [aristocratos/bpytop#237]
**Describe the bug**

Bug is while I execute `pacman -S bpytop` it showed package not found.

Os - garuda linux
kernel: 5.10

**Comment by aristocratos** [comment]
@sparkingdark 
What would possibly constitute this as a bug in bpytop?

Contact the maintainer for your distribution if it's not working properly!

The package is definitely present in the Arch repository.
https://archlinux.org/packages/community/any/bpytop/
