### ISSUE TITLE
[BUG] bpytop crashes when clicking around with the mouse

### ISSUE THREAD

**Issue by ovizii** [aristocratos/bpytop#240]
**Describe the bug**

I start bpytop with bpytop -lc press "h" for help, click the mouse, it crashes

**To Reproduce**

Install bpytop from this debian repository: https://packages.azlux.fr/ start bpytop with bpytop -lc and click around with the mouse

**Expected behavior**

I start bpytop with bpytop -lc , click the mouse as much as I like and it does not crash

**Logs**

cat /root/.config/bpytop/error.log
```
13/01/21 (16:07:09) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x9a in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 866, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 4: invalid start byte
13/01/21 (16:07:10) | WARNING: Exiting with errorcode (1). Runtime 0:00:16

13/01/21 (16:07:21) | ERROR: Input thread failed with exception: 'utf-8' codec can't decode byte 0x9c in position 4: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 866, in _get_key
    input_key += sys.stdin.read(1)                                              #* Read 1 key safely with blocking on
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 4: invalid start byte
13/01/21 (16:07:21) | WARNING: Exiting with errorcode (1). Runtime 0:00:08
```

**Info (please complete the following information):**
bpytop -v
```
bpytop version: 1.0.59
psutil version: 5.8.0

```
lsb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
 - Terminal used: iTerm 2 on OSX
 - Font used: no idea how to find out
python3 --version
`Python 3.7.3`

**Comment by aristocratos** [comment]
@ovizii 
> Font used: no idea how to find out

`Preferences -> Profile -> Text -> Font`

You will need to check under `Preferences -> Profile -> Terminal -> Terminal Emulation` that `Character encoding:` is set to `Unicode (UTF-8)` and that `Enable mouse reporting` and both `Report mouse...` checkboxes is enabled.

If you still get the same error, try upgrading your python version.

There is also no need to start with `bpytop -lc` in iTerm 2 since it has truecolor support unless you are using a very outdated version? In which case that's probably the reason for the main issue.

**Comment by ovizii** [comment]
Thanks for the detailed help. 

Font seems to be monaco: 
![image](https://user-images.githubusercontent.com/837902/104478212-4c79d000-55c2-11eb-99fd-284057a01eda.png)

Seems alright:
![image](https://user-images.githubusercontent.com/837902/104478149-3835d300-55c2-11eb-9ae8-afdf8ca7a608.png)

I started with "-lc" because without it looks like this and there is nothing I can read :-/(
![image](https://user-images.githubusercontent.com/837902/104478334-729f7000-55c2-11eb-8e14-91a1edade6de.png)

I am using the latest python3 version which ships with Debian buster. Which one is recommended?

python3 -V
`Python 3.7.3`

**Comment by aristocratos** [comment]
@ovizii 
> This is no big deal if you can't figure it out, I was just giving bpytop a go to see if its more useful to me than htop.

It's an locale error, iTerm 2 is expecting UTF-8 encoded text and your remote machine is not encoding in UTF-8.

You'll need to check that your remote machine has a UTF-8 locale and generate one if not.
Easily done by:
1. Editing `/etc/locale.gen`and uncommenting a locale that ends in UTF-8
2. Run `locale-gen`
3. Run `locale -a` and check that new locale shows up in the list and copy the name
4. Edit `/etc/default/locale` and set `LANG=` <paste> 

If it still doesn't work it could be an issue in your openssh server config that the locale isn't passed correctly.

**Comment by aristocratos** [comment]
@ovizii 
The crash itself can probably be fixed by inserting
`sys.stdin.reconfigure(errors="ignore")` at line 33 in bpytop.py
But that won't fix the issues with the colors and the mouse will not work.

**Comment by ovizii** [comment]
Thanks for the help. inside /etc/locale.gen this one is uncommented: en_US.UTF-8 UTF-8 I uncommented de_DE.UTF-8 too and generated the locales again, followed your instructions, even logged off and on again, same problem. 

I checked my sshd config and this option is set:

```
# Allow client to pass locale environment variables
AcceptEnv LANG LC_*
```
I'll close this thread as its clearly out of scope to support this, after all its not a problem with bpytop. If I figure it out, I'll update the thread just in case someone else stumbles upon the same problem.

**Comment by ovizii** [comment]
So after googling locale problems in connection with iTerm2 I found a solution for Debian:

edit /etc/ssh/sshd_config and disallow setting of locales by clients:

`AcceptEnv no`

it was previously set to: 
`AcceptEnv LANG LC_*`

Now bpytop works perfectly, even without the "-lc" and using the mouse works as well without any crashes!

**Comment by aristocratos** [comment]
@ovizii 
Awesome! Renaming this so it's easier to find for anyone with similar problems.
