### ISSUE TITLE
[BUG] Latest version not downloaded using the Python way

### ISSUE THREAD

**Issue by Jiab77** [aristocratos/bpytop#248]
**Describe the bug**

Each time I'm running `bpytop` it creates a notification saying that I'm not using the latest one and provide a link to this project on github.

I'm currently running the version `1.0.54` so the notification is correct but when running this command to install the latest version:

```bash
pip3 install bpytop --upgrade
```

It does not upgrade to version `1.0.59` which is the current latest one. So the notification keeps popping up...

**To Reproduce**

1. Close the current running `bpytop` process
2. Start `bpytop` again
3. Notification will be displayed
4. Close `bpytop` again
5. Run the given install command from the documentation: `pip3 install bpytop --upgrade`
6. Start `bpytop` again
7. The version is still the same

**Expected behavior**

When running `pip3 install bpytop --upgrade` I'm expecting to get the latest version `1.0.59` and not keeping the same version `1.0.54`.

**Screenshots**

![image](https://user-images.githubusercontent.com/9881407/104844217-35432700-58cf-11eb-88be-c7d42820b42c.png)

> Notifications

![image](https://user-images.githubusercontent.com/9881407/104844268-910db000-58cf-11eb-8eaf-3d080b978f28.png)

> Terminal

**Info (please complete the following information):**
 - bpytop version: `1.0.54`
 - psutil version: `5.8.0` (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version: Pop_OS! 18.04
 - (OSX/FreeBSD) Os release version: 
 - Terminal used: Tilix `1.7.7`
 - Font used:
 - Python version, `3.6.9` (version 3.6 or above is required):

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

```
17/01/21 (14:17:42) | INFO: New instance of bpytop version 1.0.54 started with pid 11712
17/01/21 (14:17:42) | INFO: Loglevel set to DEBUG
17/01/21 (14:17:42) | DEBUG: Using psutil version 5.8.0
17/01/21 (14:17:42) | DEBUG: CMD: /home/[REDACTED]/.local/bin/bpytop --debug
17/01/21 (14:17:43) | DEBUG: Collect and draw completed in 0.118331 seconds
17/01/21 (14:17:44) | DEBUG: Init completed in 2.382866 seconds
17/01/21 (14:17:49) | INFO: Exiting. Runtime 0:00:07 
```

**Comment by aristocratos** [comment]
@Jiab77 
How is this a `bpytop` bug?

Try clearing the pip cache or run with pip with `--no-cache-dir` flag, check user network privileges, try installing with sudo, etc.

This issue is on you system and definitively not related to any bug in `bpytop`.

**Comment by Jiab77** [comment]
@aristocratos, understood and then you were right to change labels and invalidate it but maybe you should just add something like an `FAQ` section in the `README` to cover this kind of things?

I've read the instructions again and none of your commands are mentioning the mandatory use of `sudo` when using the Python way to install `bpytop` and while `pip` gives the possibility to install locally or globally, then if `bpytop` has to be installed globally it should be mentioned somewhere.

And in this case I would have run:

```
sudo -H pip3 install bpytop --upgrade
```

Instead of simply running:

```
pip3 install bpytop --upgrade
```

As explained.

Also I've selected `[BUG]` because it was not a `Feature` as presented when creating a new issue. I'm sorry for the misunderstanding.

I really like `bpytop` and I'm pretty much impressed by your work. Thanks anyway for your advices, I'll try them.

**Comment by Jiab77** [comment]
@aristocratos, I've tried your advice, while using `sudo -H` there is package conflict with existing `psutil` package installed globally and can't be removed / upgraded. And without `sudo` and the `no-cache-dir` argument, `pip` is only installing the version `1.0.54` but not the version `1.0.59`. So I guess you're right and it is more related to the Python package or something similar.

So I gave up with Python and `pip` and used this way: https://github.com/aristocratos/bpytop#manual-installation-linux-osx-and-freebsd

This solved the issue.

**Comment by aristocratos** [comment]
@Jiab77 
> if bpytop has to be installed globally it should be mentioned somewhere.

It doesn't.

> maybe you should just add something like an FAQ section in the README to cover this kind of things?

There is https://github.com/aristocratos/bpytop/discussions where general questions can be asked.

> Also I've selected [BUG] because it was not a Feature as presented when creating a new issue. I'm sorry for the misunderstanding.

I can't say if it's a bug or not, but this issue is with `pip` and not `bpytop`, so if you want to report a bug, report it at https://github.com/pypa/pip

The reason it's marked `invalid` is because I don't have any power over how `pip` is coded or any in-depth knowledge of the workings of `pip`. Troubleshooting questions should be aimed at the maintainers of `pip`.
This is the same reason I redirect anybody reporting issues with displaying `bpytop` in their particular terminal to the creators of the terminal they are using.

> So I gave up with Python and pip and used this way: https://github.com/aristocratos/bpytop#manual-installation-linux-osx-and-freebsd
> 
> This solved the issue.

Great to hear!
