### ISSUE TITLE
[REQUEST] Allow disabling the I/O metric for disks

### ISSUE THREAD

**Issue by TheComputerGuy96** [aristocratos/bpytop#249]
**Is your feature request related to a problem? Please describe.**
The I/O metric (aka the "I/O:" line) takes up extra space and it's not needed in my case

**Describe the solution you'd like**
A setting in options to disable the I/O metric

**Describe alternatives you've considered**
Downgrading bpytop might be an option, but then I might lose certain features/bug fixes (and support for newer versions of Python if it becomes too old)

I want to keep things simple, so maintaining my own package with the metric removed isn't an option

**Additional context**
![Screenshot from 2021-01-18 20-46-25](https://user-images.githubusercontent.com/19169000/104953036-4faffa00-59ce-11eb-92bc-01fc8a0c549a.png)

**Comment by aristocratos** [comment]
@TheComputerGuy96 
Sure, can add a toggle for the IO graph in the options menu.

**Comment by aristocratos** [comment]
@TheComputerGuy96 
Added in v1.0.60
