### ISSUE TITLE
[BUG] The CPU temperatures are constantly shifted to the right.

### ISSUE THREAD

**Issue by AndyLavr** [aristocratos/bpytop#254]
**Describe the bug**

The CPU temperatures are constantly shifted to the right.

Start bpytop v1.0.61

[Screenshots](https://pasteboard.co/JLopZ02.jpg)

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`

bpytop version: 1.0.61

 - psutil version: `bpytop -v` (version 5.7.0 or above is required)

psutil version: 5.8.0 

 - (Linux) Linux distribution and version:

 Ubuntu

  - Terminal used:

KDE konsole 20.12.1

 - Python version, `python3 --version` (version 3.6 or above is required):

Python 3.9.1+

**Additional context**

$ cat ~/.config/bpytop/error.log
26/01/21 (10:41:25) | INFO: New instance of bpytop version 1.0.61 started with pid 906215
26/01/21 (10:41:25) | INFO: Loglevel set to DEBUG
26/01/21 (10:41:25) | DEBUG: Using psutil version 5.8.0
26/01/21 (10:41:25) | DEBUG: CMD: /usr/bin/bpytop --debug
26/01/21 (10:41:27) | DEBUG: Collect and draw completed in 0.364209 seconds
26/01/21 (10:41:29) | DEBUG: Init completed in 3.940391 seconds

**Comment by aristocratos** [comment]
@AndyLavr 
Read the README, in particular the section called "Prerequisites (Read this if you are having issues!)".

Also bash is not a terminal, but considering your issue I'm gonna guess your running konsole.

**Comment by AndyLavr** [comment]
> Also bash is not a terminal, but considering your issue I'm gonna guess your running konsole.

KDE konsole 20.12.1

**Comment by AndyLavr** [comment]
Disabled Bi-Directional text rendering solved the problem. Thank you!
