### ISSUE TITLE
[BUG] OSX iterm2 throw exception when start 

### ISSUE THREAD

**Issue by simon-xia** [aristocratos/bpytop#255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

![image](https://user-images.githubusercontent.com/6264665/106134592-b210b380-61a1-11eb-8a87-3bfda761af36.png)

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`
 - psutil version: `bpytop -v` (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version:
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:
 - Python version, `python3 --version` (version 3.6 or above is required):

```
➜  ~ bpytop -v
bpytop version: 1.0.61
psutil version: 5.8.0
```

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
@simon-xia 
Looks like font/utf-8 issue on your system.
See https://github.com/aristocratos/bpytop#prerequisites for the font requirements.
