### ISSUE TITLE
[BUG] core temp missing on some cores on ryzen 3900X

### ISSUE THREAD

**Issue by ErwinJunge** [aristocratos/bpytop#258]
**Describe the bug**

On my ryzen 3900X, some cores aren't showing the core temp.
![2021-02-08-223212_grim](https://user-images.githubusercontent.com/339691/107284316-e4ea5f80-6a5d-11eb-8c04-8fb31de2c074.png)

**To Reproduce**

Open bpytop. Notice missing temps.

**Expected behavior**

Open bpytop. See temps on all cores.

PR incoming.

**Comment by craigccfl** [comment]
Arch 5.15.2 Ryzen 3950x, something changed 

![image](https://user-images.githubusercontent.com/38798834/142771615-56fe118d-f782-4bf9-833e-9de41d1412bb.png)

Method #259 not changing result.

**Comment by craigccfl** [comment]
Fixed the issue, don't know if it is related or not, install zenpower-dkms (aur), reboot and it started working again. The other item that may have fixed it. reran lmsensors-detect and overwrote the config.  

All good now. 

![image](https://user-images.githubusercontent.com/38798834/142772821-669af6ea-588f-430d-9320-6c63314939b5.png)
