### ISSUE TITLE
[BUG] Failed to install bpytop via apt (Ubuntu 20.04)

### ISSUE THREAD

**Issue by jamestansx** [aristocratos/bpytop#260]
**Describe the bug**

I was unable to install bpytop via apt command:
`sudo apt install bpytop`

**To Reproduce**

1. Run command `sudo apt update`
2. Run command `sudo apt install bpytop`

**Expected behavior**

The installation process should start without error.

Instead, it shows `E: Unable to locate package bpytop`

**Screenshots**
![image](https://user-images.githubusercontent.com/45304579/107796292-a4a81b80-6d94-11eb-84d4-67c340d07b4f.png)

**Info (please complete the following information):**
 - (Linux) Linux distribution and version: Ubuntu 20.04 WSL
 - Terminal used: Windows Terminal
 - Font used:  FiraCode Nerd Font
 - Python version: 3.8.5

**Additional context**

**Comment by aristocratos** [comment]
@jamestansx
Not really sure why you expected it to work when it isn't available in the official Ubuntu repository, something you would've noticed if read the README.md

Look at the install instructions if you need help installing.
