### ISSUE TITLE
[BUG] bpytop looks weird with URxvt

### ISSUE THREAD

**Issue by Hund** [aristocratos/bpytop#264]
bpytop looks weird with URxvt. Changing the theme or using `-lc` just makes it look weird in other combinations.

![2021-02-14-125214_1920x1080_scrot](https://user-images.githubusercontent.com/320498/107876139-7295d700-6ec4-11eb-9669-684ecae206e8.png)

- bpytop version: 1.0.61
- Linux distribution and version: Gentoo
- Terminal used: URxvt
- Font used: Terminus
- Python version: 3.8.6

**Comment by aristocratos** [comment]
@Hund 
As has been mentioned many times before and is apparant from the README, if BpyTOP isn't rendering correctly in your terminal, complain to the creator of the terminal.

I can't change how your terminal works, if it fails to even render 256-color escape codes, I would strongly suggest you switch to another terminal.

**Comment by Hund** [comment]
It's not my terminal emulators fault that you push it with more than the standard 16 colours.

Thanks for the reply though, I guess I'll just have to uninstall this "modern" piece of software.

**Comment by aristocratos** [comment]
@Hund 
> It's not my terminal emulators fault that you push it with more than the standard 16 colours.

No, I would say it's your fault for trying to run a program that requires more than 16 colors in a terminal that can't handle it.
It's not 1995, the standard for terminals have been 256-colors for over 20 years and most terminals have full 24-bit support these days.

> I guess I'll just have to uninstall this "modern" piece of software.

That's probably for the best if you don't want to upgrade away from a terminal that hasn't been updated in the last 10 years.
