### ISSUE TITLE
[REQUEST] Implement one-dot minimum for CPU graph? 

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#267]
The one-dot minimum implemented for the network graph is great. 

Previous machines I've used BPyTOP on had such low processing power that there was never a time when the CPU usage went below 2-4%. So before I got my current machine I never really saw "gaps" in the CPU graph. But now with a Ryzen 3500U I'm at times seeing a CPU graph that is mostly blank, with no dots appearing even though the collective CPU activity is always showing at least 1% at all times. 

Suggestion: Implement the one-dot minimum for the CPU graph also, for any activity percentage close enough to be rounded up to 1% (on the numeric CPU activity display). 

Maybe make it optional for those who like to see the big gaps. But I think some users would like the gaps to mean "basically no CPU activity".

**Comment by RedBearAK** [comment]
This is pretty weird since KDE has historically been considered a very "heavy" DE compared to DEs like XFCE, MATE, or Cinnamon. Yet on a fresh install of KDE Neon I am finally seeing (for the first time) significant time slices where the main CPU activity is actually rounded down to "0%". It makes perfect sense the main CPU graph would show "nothing" during those time slices. But the main graph also shows nothing when the activity is shown as "1%". Yet the individual core graphs at the same time show a single dot anytime they show numerically at least 1% activity, even though technically each individual vertical dot on the core graph would be... about 15% or so? No, the braille characters are four dots tall, so the first dot represents anything from just above zero to 25%. 

So intuitively it just doesn't make sense that the main CPU graph remains blank during the time slices when overall CPU activity hits 1% or more, if the core graphs are going to show a dot for anything above zero. A one-dot minimum for the main CPU graph would make the main graph and the core graphs feel more in sync with each other.

**Comment by aristocratos** [comment]
@RedBearAK 
Added in v1.0.63
> Changelog
> * Added: Options for choosing temperature scale and readded support for negative celsius temps
> * Changed: Cpu values above 0 will always register on the graphs

**Comment by RedBearAK** [comment]
Haven’t been able to get the main CPU activity down to 0% again yet so I see no gaps, but from now on it will be very clear what a gap in the graph actually means. Fantastic. That was very fast work. 

Negative temp support? Have the liquid nitrogen overclockers been complaining they can’t monitor their progress properly? LOL. 

I see no reason not to close this now.
