### ISSUE TITLE
[REQUEST] Package for OpenSuse 15.1/OpenSuse 15.2 

### ISSUE THREAD

**Issue by marcoczen** [aristocratos/bpytop#273]
**Describe the solution you'd like**
Guys... possible to provide a package for OpenSuse 15.1/15.2 ? 

Pls do consider ... Thanks

**Comment by aristocratos** [comment]
@marcoczen 
This will likely happen faster if you directly message a distribution packager for OpenSuse.

**Comment by marcoczen** [comment]
Hi .. I have been unssuceful with that.
Thanks.
Closed.
