### ISSUE TITLE
[BUG][Macos] I can't see the cpi temperatures

### ISSUE THREAD

**Issue by lorenzomonta** [aristocratos/bpytop#274]
**Describe the bug**

I just installed Byptop and coretemp via homebrew, unfortunately I can't see the cpu temperatures. Can you help me understand why?
thanks

**Info (please complete the following information):**
 - bpytop version: 1.0.63
 - psutil version: 5.8.0
 - (OSX/FreeBSD) Os release version: Big Sur 11.1 (Intel version)
 - Terminal used: iTerm2
 - Font used: MesloLGS-NF-Regular 13
 - Python version, `python3 --version` (version 3.6 or above is required): 3.7.8

**Screen**
![Schermata 2021-03-08 alle 11 42 59](https://user-images.githubusercontent.com/48455647/110310988-77e9cb80-8003-11eb-923a-b2eb42caee95.png)

**Comment by aristocratos** [comment]
@lorenzomonta 

What output do you get when running `coretemp`?

**Comment by lorenzomonta** [comment]
I installed coretemp using homebrew, how I can run coretemp?
or test that coretemp is up and running?

**Comment by aristocratos** [comment]
@lorenzomonta 
You run `coretemp` in a terminal.

**Comment by aristocratos** [comment]
@lorenzomonta 
If it's not working try manually compiling and installing following the instructions at https://github.com/hacker1024/coretemp

If it's still not working, install `osx-cpu-temp` using brew, you won't get the temps for the individual cores, but it will show overall CPU temp.

**Comment by lorenzomonta** [comment]
From which directory should I run coretemp?

**Comment by lorenzomonta** [comment]
> @lorenzomonta
> 
> What output do you get when running `coretemp`?

this is the output "The specified core (0) does not exist."
But if i run brew list I can see coretemp correctlly installed

**Comment by lorenzomonta** [comment]
I've opened the issues: https://github.com/hacker1024/coretemp/issues/2
They said that the next coretemp releas will resolve this problem.
Thank you @aristocratos for you reply
