### ISSUE TITLE
[REQUEST] bpy slow start

### ISSUE THREAD

**Issue by mikdmst1** [aristocratos/bpytop#275]
in bashtop site u write "use bpytop - it faster"
bashtop start 1 sec,
bpytop start 3 sec.
who faster, what version we must use? do u process develop bashtop today?

thx for good progs!

**Comment by aristocratos** [comment]
@mikdmst1 
The init screen for bpytop can be turned off in the options menu.
"Faster" in this case doesn't mean how fast something starts, but how many CPU cycles the program needs to perform a task.
