### ISSUE TITLE
[BUG] Disks exclude filter not working in snap installations (i.e. exclude=/boot/efi)

### ISSUE THREAD

**Issue by bentolor** [aristocratos/bpytop#276]
**Describe the bug**

I'm trying to clean up my disk view. Besides suffering from #190 (so seeing a `dhcp` entry) i also fail to exclude i.e. efi though my Disks filter is `exclude=/boot/efi`

**To Reproduce**

1.Snap install
2. Set Disks filter to `exclude=/boot/efi`

**Expected behavior**

Disks filtered out

**Screenshots**
![image](https://user-images.githubusercontent.com/588260/111026642-8fea9200-83eb-11eb-84c6-26862bc007a6.png)
![image](https://user-images.githubusercontent.com/588260/111026652-a5f85280-83eb-11eb-89d0-6a0d8a51b34d.png)

```
$ cat snap/bpytop/current/.config/bpytop/bpytop.conf | grep disks_filter
#* Begin line with "exclude=" to change to exclude filter, oterwise defaults to "most include" filter. Example: disks_filter="exclude=/boot, /home/user"
disks_filter="exclude=/boot/efi"
$ mount | grep efi
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on /boot/efi type vfat (…)
```

**Info (please complete the following information):**
bpytop version: 1.0.63
psutil version: 5.8.0
Ubuntu 20.04
Python 3.8.5

**Additional context**

` snap/bpytop/current/.config/bpytop/error.log`

```
13/03/21 (11:04:24) | INFO: New instance of bpytop version 1.0.63 started with pid 2491444
13/03/21 (11:04:24) | INFO: Loglevel set to DEBUG
13/03/21 (11:04:24) | DEBUG: Using psutil version 5.8.0
13/03/21 (11:04:24) | DEBUG: CMD: /snap/bpytop/211/usr/bin/bpytop --debug
13/03/21 (11:04:24) | DEBUG: Collect and draw completed in 0.128413 seconds
13/03/21 (11:04:24) | DEBUG: Init completed in 0.165450 seconds
13/03/21 (11:04:25) | INFO: Exiting. Runtime 0:00:02 

```

**Comment by aristocratos** [comment]
@bentolor 

> I'm trying to clean up my disk view. Besides suffering from #190 (so seeing a dhcp entry)

The only advice to fix that issue for now would be to use another install method than snap, like pip instead.

> i also fail to exclude i.e. efi though my Disks filter is exclude=/boot/efi

I'm pretty sure that's because you have two separate disks_filter sections in the config.
If you change:
```
disks_filter="exclude=/boot, /home/user"
disks_filter="exclude=/boot/efi"
```

to:

```disks_filter="exclude=/boot, /home/user, /boot/efi"```

it will likely work.

**Comment by bentolor** [comment]
Hi @aristocratos, thanks for your support and fast reply.

Sorry – I mislead you: This is a copy & paste error. I shortened the lines wrongly. Here the correct output:

```
$ cat snap/bpytop/current/.config/bpytop/bpytop.conf | grep disks_filter
#* Begin line with "exclude=" to change to exclude filter, oterwise defaults to "most include" filter. Example: disks_filter="exclude=/boot, /home/user"
disks_filter="exclude=/boot/efi"
```

I never manually touched the config file.

**Comment by aristocratos** [comment]
@bentolor 
> Sorry – I mislead you: This is a copy & paste error.

Ah, ok :)

But I think it's likely this could also be caused of running in the snap environment.

You could test it by just running `wget https://github.com/aristocratos/bpytop/raw/master/bpytop.py && python3 bpytop.py`
You will need to re-enter the filter in the options though, since the snap uses it's own config file.

**Comment by bentolor** [comment]
Hi – I just did the same on my own: Yes. It works in a pip3 installation :(

Oh my dear – they should really dump that snap into trash…Only slow startup times, excess disk usage, loss of user data (uninstalling just purged my config. Glad I'm using ZFS with hourly snapshots, ), …
