### ISSUE TITLE
[BUG] Font is not rendering, has odd glyphs

### ISSUE THREAD

**Issue by doncullen** [aristocratos/bpytop#277]
**Describe the bug**

Font is not rendering, has odd glyphs

**To Reproduce**

Install it and run it

**Expected behavior**

Expected it to match screenshots on repo

**Screenshots**

[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/2024899/111041953-70aa2f80-8400-11eb-9f24-d8e0ea4a6376.png)

**Info (please complete the following information):**
 - bpytop version: bpytop version: 1.0.63
 - psutil version: psutil version: 5.8
 - (Linux) Linux distribution and version: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Terminal used: Windows command prompt over OpenSSH
 - Font used: No clue, left it at default
 - Python version, `python3 --version` (version 3.6 or above is required):  3.8.5

**Comment by aristocratos** [comment]
@doncullen 
Use a compatible font and/or terminal, this would be clear if you read the README.md, specifically https://github.com/aristocratos/bpytop#prerequisites
