### ISSUE TITLE
[BUG] 0.0% in info when you cant see the process

### ISSUE THREAD

**Issue by bgkillas** [aristocratos/bpytop#28]
sourta related to https://github.com/aristocratos/bpytop/issues/21 ig
if you select something hit info then search for something thats not it repots cpu as 0.0%
![image](https://user-images.githubusercontent.com/55570525/89463123-763de980-d73c-11ea-97c9-e1664500d8f6.png)

i should prob use this
bpytop version: 1.0.5
psutil version: 5.7.2

    (Linux) Linux distribution and version: arch linux
    Terminal used: alacritty
    Font used: noto sans mono 14
    Python version, Python 3.8.5

**Comment by aristocratos** [comment]
Fixed in v1.0.6
