### ISSUE TITLE
[BUG] IO Graph Speed has no effect

### ISSUE THREAD

**Issue by laktak** [aristocratos/bpytop#288]
**Describe the bug**

The IO Graph Speed option has no effect.

**To Reproduce**

```
disks_filter="/"
io_graph_speeds="/:100"
```
I also tried the `/dev/sda1` syntax and `root`. The drive is shown as `root` not `/`?

**Expected behavior**

The scale should change so that 100% == 100MiB/s

or it should show an error/warning. At the moment it does nothing.

**Info (please complete the following information):**
 - bpytop version: bpytop version: 1.0.63
 - psutil version: psutil version: 5.8.0

 - (Linux) Linux distribution and version: arch
 - Terminal used: alacritty
 - Font used:
 - Python version, Python 3.9.2

**Additional context**

contents of `~/.config/bpytop/error.log`

08/04/21 (14:30:50) | INFO: New instance of bpytop version 1.0.63 started with pid 136815
08/04/21 (14:30:50) | INFO: Loglevel set to DEBUG
08/04/21 (14:30:50) | DEBUG: Using psutil version 5.8.0
08/04/21 (14:30:50) | DEBUG: CMD: /home/foo/.local/bin/bpytop --debug
08/04/21 (14:30:50) | DEBUG: Collect and draw completed in 0.047125 seconds
08/04/21 (14:30:50) | DEBUG: Init completed in 0.101990 seconds
08/04/21 (14:30:56) | INFO: Exiting. Runtime 0:00:06

**Comment by aristocratos** [comment]
@laktak 

> disks_filter="/"
> io_graph_speeds="/:100"

`/` is the mountpoint, the device name should be a `/dev/...` device.

> I also tried the /dev/sda1 syntax and root.

Are you running encryption on your disk or raid? In that case `/dev/sda1` is likely not the correct mount device.

You can check the device name psutil recognizes for your `/` mount with `python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions())"` should be the first entry.

**Comment by laktak** [comment]
> python3 -c "import psutil, pprint; pprint.pprint(psutil.disk_partitions())"

Thank you, that did help. I think what confused me is that the disk filter uses mount points but here you need device names.

Also for USB devices the device name changes every time ... the default IO graph speed can't yet be changed in the options, correct?

Anyways, thank you for such a great tool!
