### ISSUE TITLE
[BUG] Network Clicking not functional for back

### ISSUE THREAD

**Issue by Dulanic** [aristocratos/bpytop#297]
**Describe the bug**

You can click n for next under net, but clicking b does not go back. Typing b does work.

**To Reproduce**

1. Lauch bpytop
2. Click n> at the top right of net.
![image](https://user-images.githubusercontent.com/2948206/116428309-673b2200-a80a-11eb-87a1-b1f9269616bb.png)
3. Click <b next to network name.

**Expected behavior**

<b should move back like n> goes to next.

**Screenshots**

Video: https://streamable.com/u1na0d

**Info (please complete the following information):**
bpytop version: 1.0.64
psutil version: 5.8.0
 - (Linux) Linux distribution and version: Ubuntu Server 20.04
 - (OSX/FreeBSD) Os release version:
 - Terminal used: WSL2 using ssh to server.
 - Font used:
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.9.0+
 -

**Additional context**

contents of `~/.config/bpytop/error.log`
28/04/21 (10:17:47) | INFO: New instance of bpytop version 1.0.64 started with pid 967533
28/04/21 (10:17:47) | INFO: Loglevel set to DEBUG
28/04/21 (10:17:47) | DEBUG: Using psutil version 5.8.0
28/04/21 (10:17:47) | DEBUG: CMD: /usr/local/bin/bpytop --debug
28/04/21 (10:17:47) | DEBUG: Collect and draw completed in 0.195616 seconds
28/04/21 (10:17:47) | DEBUG: Init completed in 0.216572 seconds
28/04/21 (10:17:56) | INFO: Exiting. Runtime 0:00:09

**Comment by aristocratos** [comment]
@Dulanic 
Seems like I forgot to add a flag to recalculate the position of the `b` button when changing network interface. The mouse still interacts for the old position of the `b` button.

Will fix in the next update.

**Comment by Dulanic** [comment]
@aristocratos Thanks! I figured it was something easy. No biggie, I doubt I'd even use it much, just noticed it.

**Comment by aristocratos** [comment]
@Dulanic 
Fixed in v1.0.65
