### ISSUE TITLE
[REQUEST] Should I use your fork of psutil to build the bpytop snap?

### ISSUE THREAD

**Issue by kz6fittycent** [aristocratos/bpytop#298]
Not so much a feature request, as it is a way to track the conversation regarding the snap builds going forward.

Couple of things:

1. I got the approval for auto-connecting interfaces for the snap! So hopefully that will mean no more issues saying the snap doesn't work....
2. Should I use your fork of `psutil` to build the snap? It's still showing `dhcp` as `/`, as well as some other oddness. 

Thanks, and I hope that the first item is some good news for you.

**Comment by aristocratos** [comment]
@kz6fittycent 
1. That's great :)
2. No, I only use my fork when working on pull requests for the original or testing stuff.
There is however a bug affecting systems with alot of cores in psutil 5.8.0 and earlier, so you could possibly build from the official git version until 5.8.1 is released to get the fix.

I've just started on a C++ version of bpytop, gonna write all the system info collection from scratch, so it's gonna be a long while before that's ready, but should be fast :)

**Comment by kz6fittycent** [comment]
Oh NICE! I'll keep a lookout for that one. `bctop` gonna be the name? Or `ctop`? 

Anyway, the snap is using the `git` [version](https://github.com/giampaolo/psutil), so we're good there.

**Comment by aristocratos** [comment]
`ctop` is already taken, but was thinking just `btop` to keep it simple and since it will still be based on the design concept and core functionality of bashtop.

**Comment by kz6fittycent** [comment]
I like it. There are lot of possibilities. `cop`, `bop`, `plop` (because of C++; focus on the plus-plus). Anyway, I'll likely create a snap for it too. 

What I can do, if you want, is fork the repo, create the snap, do a PR, and get you setup for ownership in forum.snapcraft.io. 

If not, no biggie, I'll just plug along the way we've been going.
