### ISSUE TITLE
[BUG] CPU usage and temperature are not shown properly

### ISSUE THREAD

**Issue by Cois19** [aristocratos/bpytop#299]
**Describe the bug**

The numbers showing CPU usage and temperature are not displayed correctly, they are blocked by their own percentage.

**To Reproduce**

Run bpytop

**Expected behavior**

CPU usage and temperature are displayed properly.

**Screenshots**

![Screenshot_20210502_211141](https://user-images.githubusercontent.com/44765243/116814350-1a00dc80-ab8b-11eb-9a8b-037f1ce7b1eb.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.65
 - psutil version: 5.8.0
 - (Linux) Linux distribution and version: Kubuntu 21.04 with kernel 5.10.33-051033-generic
 - Terminal used: Konsole Terminal
 - Font used: Noto Sans
 - Python version, 3.9.4

**Additional context**

02/05/21 (04:34:59) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bpytop.py", line 933, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
02/05/21 (13:19:26) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bpytop.py", line 933, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
02/05/21 (21:17:28) | INFO: New instance of bpytop version 1.0.65 started with pid 30150
02/05/21 (21:17:28) | INFO: Loglevel set to DEBUG
02/05/21 (21:17:28) | DEBUG: Using psutil version 5.8.0
02/05/21 (21:17:28) | DEBUG: CMD: /usr/local/bin/bpytop --debug
02/05/21 (21:17:28) | INFO: Config file malformatted or missing, will be recreated on exit!
02/05/21 (21:17:28) | DEBUG: Collect and draw completed in 0.079336 seconds
02/05/21 (21:17:28) | DEBUG: Init completed in 0.103943 seconds

**Comment by aristocratos** [comment]
@Cois19 

See the highlighted part from the section of the README.MD called "Prerequisites (Read this if you are having issues!)":

> Notice (Text rendering issues)
> 
> If you are having problems with the characters in the graphs not looking like they do in the screenshots, it's likely a problem with your systems configured fallback font not having support for braille characters.
> 
> See Terminess Powerline for an example of a font that includes the braille symbols.
> 
> See comments by @sgleizes link and @XenHat link in issue #100 for possible solutions.
> 
> **_If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix._**
> 
> Characters clipping in to each other or text/border misalignments is not bugs caused by bpytop, but most likely a fontconfig or terminal problem where the braille characters making up the graphs aren't rendered correctly. Look to the creators of the terminal emulator you use to fix these issues if the previous mentioned fixes don't work for you.
