### ISSUE TITLE
[Bug] Crash after killing a Process (using key "k")

### ISSUE THREAD

**Issue by roidal** [aristocratos/bpytop#30]
Log:

Traceback (most recent call last):
  File "bpytop.py", line 2611, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '  11       0 sr0 9 0 4 10 0 0 0 0 0 16 10 0 0 0 0 0 0\n'

**Comment by aristocratos** [comment]
You need to follow the bug template.

The log you posted is an issue unrelated to killing processes and had error handling added in version 1.0.1.

**Comment by roidal** [comment]
- bpytop version: 1.0.3
 - **psutil version: 5.6.7**
 - (Linux) Linux distribution and version: Fedora 32; kernel 5.7.11-200.fc32.x86_64
 - Terminal used: KDE Konsole
 - Python version: 3.8.5

Sorry, my fault, seems like my psutil is too old.

**Comment by aristocratos** [comment]
That shouldn't make any difference when killing processes though, since psutil isn't used for sending signals.

Whould you mind trying to reproduce the crash when running `bpytop --debug` and then posting the error.log?

**Comment by roidal** [comment]
Looks like it happens if you kill a process while having the (detailed) info-window of that process open.

Log with `--debug` enabled:
[error.log](https://github.com/aristocratos/bpytop/files/5036378/error.log)
