### ISSUE TITLE
[BUG] Kill and Terminate buttons do nothing.

### ISSUE THREAD

**Issue by 0ae** [aristocratos/bpytop#300]
**Describe the bug**

Whenever I open up bpytop, the `kill` (k) & `terminate` (t) buttons have never worked for me, even though they work **completely fine on htop and bashtop for me**

**To Reproduce**

Honestly, I don't know, this has been plaguing me since always for no reason

**Expected behavior**
Startup bpytop, & then be able to kill a process.

**Screenshots**

https://media.discordapp.net/attachments/814786416663068763/838512685418151956/unknown.png (htop)

https://media.discordapp.net/attachments/814786416663068763/838512764280111154/unknown.png (bashtop)

https://media.discordapp.net/attachments/814786416663068763/838512764280111154/unknown.png (bpytop)

**Info (please complete the following information):**
 - bpytop version: 1.0.65
 - psutil version: 5.7.3
 - (Linux) Linux distribution and version: Gentoo Linux
 - Terminal used: ST ( suckless/simple terminal)
 - Font used: SauceCodePro Nerd Font
 - Python version: 3.8.8

**Additional context**

I've always had this issue since I switched to Linux

Arch Linux -> Void -> Gentoo Linux, Distro hopping has never fixed this issue for me.

``
02/05/21 (22:18:02) | INFO: New instance of bpytop version 1.0.65 started with pid 481 
02/05/21 (22:18:02) | INFO: Loglevel set to DEBUG 
02/05/21 (22:18:02) | DEBUG: Using psutil version 5.7.3 
02/05/21 (22:18:02) | DEBUG: CMD: /home/byte/.local/bin/bpytop --debug 
02/05/21 (22:18:04) | DEBUG: Collect and draw completed in 0.464469 seconds 
02/05/21 (22:18:05) | DEBUG: Init completed in 2.534933 seconds 
02/05/21 (22:18:13) | INFO: Exiting. Runtime 0:00:11  
``

I installed it via the `pip` method & added it to my `PATH` & got the `psutil` via `portage` by doing `emerge --ask dev-python/psutil`

Apologies incase this isn't enough info to try and diagnose any issue.

If I can somehow provide more info, please tell me!

**Comment by aristocratos** [comment]
@0ae 
>  the kill (k) & terminate (t) buttons 

You are using `shift + k` and `shift + t` as in uppercase `K`, `T` right?
And are the owner of the process you are killing or running `sudo`?

**Comment by 0ae** [comment]
> @0ae
> 
> > the kill (k) & terminate (t) buttons
> 
> You are using `shift + k` and `shift + t` as in uppercase `K`, `T` right?
> And are the owner of the process you are killing or running `sudo`?

Jeez, that was the cause.


Apologies, I never ran it with `shift + k` & `shift + t`. 

(Although it'd be neat to possibly add a feature to do it with `k` & `t` & then ask for confirmation to end it first :P)

**Comment by aristocratos** [comment]
@0ae
No worries :)

The lowercase k and t are used by other functions.
You can press shift + h or ESC and help for all hotkeys.

**Comment by 0ae** [comment]
> @0ae
> No worries :)
> 
> The lowercase k and t are used by other functions.
> You can press shift + h or ESC and help for all hotkeys.

Cheers for telling me all this.

I didn't know anything about this.


Also, thanks for even creating bpytop :)
