### ISSUE TITLE
[BUG] CPU Graph sub-box pushes values under unit symbols

### ISSUE THREAD

**Issue by shinenelson** [aristocratos/bpytop#303]
**Describe the bug**

The CPU Graph sub-box which shows the load and temperature of each CPU thread pushes the integer values under the unit symbols. It starts off properly, but as the graph is being plotted, the value keeps getting pushed to the right until a whole digit is overlapped with the unit symbol.

I did some digging into the code and I suspect the `Mv.l` method call in https://github.com/aristocratos/bpytop/blob/228cc945d5ec949f88dae7730ca9ef279070f0cd/bpytop.py#L1968 I tried to fix it myself, but I could not ( hence, the issue and not pull request ).

**To Reproduce**

Run `bpytop` normally and leave it for 10-15 seconds until the CPU threads graph starts populating. Observe the values being pushed to the right as the graph moves towards the left.

**Expected behavior**

The values remain stationary.

**Screenshots**

![image](https://user-images.githubusercontent.com/4771718/117437015-40d55f00-af4d-11eb-83bc-5aa360bd35da.png)

**System Info**
 - bpytop version: `1.0.65`
 - psutil version: `5.8.0`
 - (Linux) Linux distribution and version: **KDE Neon 5.21**
 - Terminal used: **Konsole**
 - Python version: `3.8.5`

**Additional context**

This bug affects https://github.com/aristocratos/bashtop in the same as well. Let me know if a new issue needs to be opened there for tracking purposes.

**Comment by aristocratos** [comment]
@shinenelson

That's not what's happening here at all.

As also written under Prerequisites in README.md:

> If text are misaligned and you are using Konsole or Yakuake, turning off "Bi-Directional text rendering" is a possible fix.

**Comment by shinenelson** [comment]
Thank you for the prompt response.

I am sorry for not reading the manual. You are right, the
'Bi-Directional text rendering' was the culprit after all.

I am sorry for this false-positive issue. I will close this issue now.

**Comment by chopeen** [comment]
If you cannot find this setting in Konsole, click `Edit Current Profile` and it's under `Advanced`.
