### ISSUE TITLE
Xresources support 

### ISSUE THREAD

**Issue by siduck76** [aristocratos/bpytop#304]
it would be nice if bpytop supported terminal colors too , like taking colors from xresources and set it as a theme . I use a custom onedark but there's no theme for it .

![image](https://user-images.githubusercontent.com/59060246/117606817-4ebaf800-b178-11eb-9fbb-d20eba07b19f.png)

where as other cli system monitors take colors from terminal colors!

![image](https://user-images.githubusercontent.com/59060246/117606860-66927c00-b178-11eb-967e-df6598e5695c.png)

**Comment by aristocratos** [comment]
@siduck76 
bpytop uses 24bit color and need 24bit color values to generate the gradients for graphs and meters. It can convert those colors down to a 256 color palette but it still needs 24bit as input.

> I use a custom onedark but there's no theme for it .

Why don't you create one?

Generating from xresources are not really feasible.

**Comment by siduck76** [comment]
yeah I think so , can we use output of some commands in the theme file? Im able to get colors from xresources by a script. 

example  : 
![image](https://user-images.githubusercontent.com/59060246/117614932-a6f8f680-b186-11eb-95b1-ca70a4bbc63a.png)

getxres is a small script : 

![image](https://user-images.githubusercontent.com/59060246/117614988-bd9f4d80-b186-11eb-8ef5-1581f4b12850.png)

**Comment by duchengyao** [comment]
Which cli monitor is in the second picture?
Thanks. @siduck76

**Comment by siduck76** [comment]
> Which cli monitor is in the second picture?
> Thanks. @siduck76 

Bottom
