### ISSUE TITLE
[BUG] Full Custom CPU Name Not Displaying

### ISSUE THREAD

**Issue by jimmybrancaccio** [aristocratos/bpytop#314]
**Describe the bug**

After setting a custom CPU name, it is only partially displayed on a certain system. Other systems with bpytop seem to display the custom name without issue. In the system not working, I have set the custom name to 'Xeon E5-2690 v2' which is only 19 characters. I think I read somewhere (probably in a GitHub issue here) that up to 19 characters will be displayed.

I wonder if this is due to the size of this "box" since there's only 2 cores and no temperature information displayed. I believe there's no temperature information due tot he fact that this is a VM.

If I don't do a custom CPU name, only 'Xeon is displayed'. From `cat /pro/cpuinfo`:

```
model name	: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
```

**To Reproduce**

Set the custom CPU name to 'Xeon E5-2690 v2'. Go back to the full mode display in bpytop and observe the CPU name.

**Expected behavior**

I would expect the full custom CPU name would be displayed - up to 19 characters if what I read is correct.

**Screenshots**

<img width="742" alt="Screen Shot 2021-05-29 at 09 12 32" src="https://user-images.githubusercontent.com/405585/120073472-08add180-c05e-11eb-87f3-7b1a724e0e47.png">

<img width="845" alt="Screen Shot 2021-05-29 at 09 10 44" src="https://user-images.githubusercontent.com/405585/120073432-e4ea8b80-c05d-11eb-9c0d-86ffd50a9df5.png">

**Info (please complete the following information):**
 - bpytop version:

```
# bpytop -v
bpytop version: 1.0.65
psutil version: 5.8.0
```

 - (Linux) Linux distribution and version: Ubuntu 20.04.2
 - Terminal used: Terminal.app (macOS 11.3)
 - Font used: Hack Nerd Font Regular Complete
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

Nothing really too interesting here:

```
29/05/21 (09:16:04) | INFO: New instance of bpytop version 1.0.65 started with pid 257792
29/05/21 (09:16:04) | INFO: Loglevel set to DEBUG
29/05/21 (09:16:04) | DEBUG: Using psutil version 5.8.0
29/05/21 (09:16:04) | DEBUG: CMD: /usr/local/bin/bpytop --debug
29/05/21 (09:16:05) | DEBUG: Collect and draw completed in 0.071234 seconds
29/05/21 (09:16:05) | DEBUG: Init completed in 0.129859 seconds
29/05/21 (09:16:08) | INFO: Exiting. Runtime 0:00:04
```

**Comment by aristocratos** [comment]
@jimmybrancaccio 
No, it's not a bug that text won't fit in the space available in the box title aren't shown...

**Comment by jimmybrancaccio** [comment]
@aristocratos So it's a feature then? 🤔
