### ISSUE TITLE
[REQUEST] Tree mode processes with sort 

### ISSUE THREAD

**Issue by ryx2** [aristocratos/bpytop#32]
When filtering processes by tree mode, is it possible to sort by the memory or cpu of the parent process? For example chrome always spawns like 20 different processes, would it be possible in tree mode to group all of their memory and cpu consumption together?

**Comment by aristocratos** [comment]
Can look in to it, but it's a bit tricky with the recursive nature of how the tree is created.

But could possibly implement something like every process with a depth greater than 3 being collapsed by default with a combined cpu and mem, and having a hotkey to expand all children of the process.

**Comment by ryx2** [comment]
i like your collapseability idea. 

I think I have some idea implementations. 

right before the lines:

		```
cy = 1
		for n, (pid, items) in enumerate(proc.processes.items(), start=1):
			if n < cls.start: continue
			l_count += 1
```

before for loop, init a dict. have keys as pid, value is bool, where bool is if pid is root. all pids start as true. 
loop thru all processes and if pid has child pid, set dict for pid key false. if key is already false, skip. Then maybe another dict to track all the root processes memory, key is pid value is mem. 

want me to make a pull req for you

**Comment by aristocratos** [comment]
> want me to make a pull req for yo

That's alright, I think I'll make the needed changes to the ProcCollector class directly since it's already iterating over all processes with children, and add any extra attributes to the processes dict. That way the draw function stays the same regardless of tree or no tree.

**Comment by aristocratos** [comment]
@ryx2 
Added collapse/expand functionality for tree view in v1.0.16

**Comment by ryx2** [comment]
awesome

**Comment by ryx2** [comment]
@aristocratos I see the [-] buttons next to the chrome processes, but how do I collapse them? 

also the cpu / memory within the tree isn't summed!

**Comment by aristocratos** [comment]
Using spacebar or by clicking the button called "collapse" at the bottom.

The cpu, mem and threads are only summed up when collapsed.

**Comment by ryx2** [comment]
Ah, I see that it is spacebar. You need to mention that somewhere on the interface like the rest of the shortcuts

**Comment by aristocratos** [comment]
Well, it says "spc" beside the text, also says so in the help menu.
