### ISSUE TITLE
[BUG] CPU temps occluded. 

### ISSUE THREAD

**Issue by evertvorster** [aristocratos/bpytop#342]
**Describe the bug**
The CPU temperature is hidden behind the degrees C character

[A clear and concise description of what the bug is.]

**To Reproduce**
Just run it on my system? It may be because it's degrees C instead of Farenheit. 
I see the same thing on bashtop... 

**Expected behavior**
I would like to see all of the temperature?

**Screenshots**
![Screenshot_20210817_083216_bpytop_temp](https://user-images.githubusercontent.com/12045269/129676529-4e9ed7fd-8feb-4b89-bd2e-13371cb1e77c.jpg)

**Info (please complete the following information):**
bpytop version: 1.0.67
psutil version: 5.8.0
 - (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version: Arch Linux, fully up to date 2021-08-16
 - Terminal used: Konsole, Yakauke
 - Font used: Hack 10pt
 - Python version, Python 3.9.6

**Comment by Willy-JL** [comment]
+1, also having this issue
however for me also cpu percentages are occluded, both in cpu section and proc section
![image](https://user-images.githubusercontent.com/49810075/130626137-337660e8-b145-4638-906c-aea0bc9e90d1.png)

**Comment by aristocratos** [comment]
@evertvorster @Willy-JL 
https://github.com/aristocratos/bpytop/blob/master/README.md#notice-text-rendering-issues ...

**Comment by Willy-JL** [comment]
disabling the bi-directional rendering in konsole fixed it for me, thanks!
