### ISSUE TITLE
pidof bpytop

### ISSUE THREAD

**Issue by CSpencerND** [aristocratos/bpytop#348]
I'm trying to call bpytop in a script but I need to check if it's running.
`pidof bpytop`, and `pgrep bpytop`, return nothing.
I also want to kill it if it's already running but `killall bpytop` returns `no process found`
Example code of what I'm trying to do.
`ps aux | grep /usr/bin/bpytop && { killall bpytop && exit; } || { setsid -f "$TERMINAL" -e bpytop }`

**Comment by alexcoe** [comment]
ps ax | grep 'bpytop' | grep -v grep | awk '{print $1}'

**Comment by CSpencerND** [comment]
> ps ax | grep 'bpytop' | grep -v grep | awk '{print $1}'

Wow. Thanks a bunch. I never would've thought of that.
