### ISSUE TITLE
[BUG] Bpytop shows that app uses more than 100% of CPU

### ISSUE THREAD

**Issue by Cherro59** [aristocratos/bpytop#354]
Bpytop shows that programs use more than 100% of CPU. I installed BpyTOP via pip. OS Zorin OS 16, kernel 5.8, python 3.8
![изображение](https://user-images.githubusercontent.com/73524699/135762719-6e4ad4be-dc9f-43fe-9f5e-4f1016cffe43.png)

**Comment by aristocratos** [comment]
@Cherro59 
See `proc_per_core` in the options menu.
