### ISSUE TITLE
Garbled colors in bpytop via mosh

### ISSUE THREAD

**Issue by jakobbg** [aristocratos/bpytop#360]
This is a complex issue...

1. Launch tmux on MacOS M1 11.6 (20G165)
2. ssh from MacOS M1 to FreeBSD 13.0-RELEASE-p4
3. mosh from FreeBSD to Ubuntu 20.04.3 LTS (Focal Fossa)
4. run bpytop (10.0.61) and experience garbled colors

If I replace step 3 with "ssh from FreeBSD to Ubuntu", the colors in bpytop renders nice

Nice colors (using ssh):
![image](https://user-images.githubusercontent.com/142172/137723871-c2289ebe-e003-4a22-9f83-3a235313b5b1.png)

Garbled colors (using mosh):
![image](https://user-images.githubusercontent.com/142172/137723632-817f1c3b-ef4b-463f-8016-5188e1ae094f.png)

Will gladly provide more debug info upon request! :-D

**Comment by jakobbg** [comment]
Will do. Thanks for the quick reply!

**Comment by JackLau1222** [comment]
i have a same issue
when i use the native shell `Terminal` on MacOS M1 Pro
<img width="927" alt="image" src="https://github.com/aristocratos/bpytop/assets/131463945/2b213f43-825f-4665-9efa-c7c5ca553d44">
but if i use the 3rd terminal `iTerm`, it's work well
<img width="962" alt="image" src="https://github.com/aristocratos/bpytop/assets/131463945/13158afe-9804-4ce3-b21d-dd40cdcb97f8">

and the shell is always zsh
