### ISSUE TITLE
bug in UI grid in Manjaro Linux

### ISSUE THREAD

**Issue by ibrahemesam** [aristocratos/bpytop#363]
I cant get the temperature of CPU cores because its place in UI is too narrow.
I don't get this bug either in Linux mint or Kubuntu, but it happens in Manjaro.
My OS is Manjaro Linux KDE.
![ggg](https://user-images.githubusercontent.com/43931249/142894101-10102bbd-aaf2-41e1-b414-7dce98992b11.png)

**Comment by aristocratos** [comment]
@ibrahemesam 
https://github.com/aristocratos/btop#prerequisites
