### ISSUE TITLE
CPU temp bugged

### ISSUE THREAD

**Issue by big-mak** [aristocratos/bpytop#365]
Depending on window size, CPU temp will either not show at all or show partly as in the attached ss. When starting, temp will start visible and slide out of view as the graph builds.
![2021-11-28_10-22](https://user-images.githubusercontent.com/82375998/143764069-0eb6e5c3-0554-4516-8ea6-ca6b1bcbd902.png)

video: https://imgur.com/a/Sod7WAN

**Comment by aristocratos** [comment]
@big-mak 
#363
