### ISSUE TITLE
[BUG] Core temperatures and usage and CPU usage graph displaying incorrectly

### ISSUE THREAD

**Issue by HoodedDeath** [aristocratos/bpytop#369]
**Describe the bug**

The CPU temperature columns are cut off and only showing the left-most digit of temperature. The CPU core percentages are being cut off, digit visible is a '1' when a core is being used 100%. The CPU usage graph is distorted and missing some sections at times.

**To Reproduce**

I've only observed this behavior when running bpytop on a display connected to a Gentoo system (TTY or terminal emulator, same behavior). Tested using ssh from my Arch system into my Gentoo system, and this behavior is not displayed on the Arch side.

**Expected behavior**

Normal columns formatting, as I've seen on any other distro I've used this on

**Screenshots**

Screenshot of the buggy behavior
![bpytop-bug-crop](https://user-images.githubusercontent.com/37732447/145169761-e818cb38-cebe-49a2-8145-0f1eab3e6d92.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.67
 - psutil version: 5.7.3
 - (Linux) Linux distribution and version: Gentoo
 - Terminal used: Observed in TTY, KDE Konsole, and Yakuake
 - Font used: Observed using 'Hack' and 'Monospace' fonts
 - Python version: 3.9.7

**Additional context**

'~/.config/bpytop/error.log' is empty, even after running `bpytop --debug`. Although, it seems that option flags are not working for me, as `bpytop -v` launches like normal instead of displaying versions (might be a setup mistake on my end, not sure).

**Comment by aristocratos** [comment]
@HoodedDeath 
https://github.com/aristocratos/bpytop#notice-text-rendering-issues

**Comment by HoodedDeath** [comment]
My bad. I hadn't realized that section was in the readme. Turning off "Bi-Directional text rendering" fixed it.
