### ISSUE TITLE
[BUG] UI becomes misaligned with use

### ISSUE THREAD

**Issue by fonnesbeck** [aristocratos/bpytop#37]
**Describe the bug**

When bpytop has been running for a few minutes, the text and borders become misaligned and the app becomes hard to read. Here is a screen shot:

![image](https://user-images.githubusercontent.com/81476/89692461-61468f00-d8d1-11ea-852c-7c43d7f1cf13.png)

**Info (please complete the following information):**
- bpytop version: 1.0.7
- psutil version: 5.7.0
 - (Linux) Linux distribution and version: Debian 9 in ChromeOS via Crostiini
 - Terminal used: Crostini terminal on Chrome
 - Python version, 3.7.7

**Comment by aristocratos** [comment]
[README.md#Prerequisites](https://github.com/aristocratos/bpytop#prerequisites)

> Linux, Mac Os X and FreeBSD
> 
> For correct display, a terminal with support for:
> 
>     24-bit truecolor (See list of terminals with truecolor support)
>     Wide characters (Are sometimes problematic in web-based terminals)
> 
> Also needs a UTF8 locale and a font that covers:
> 
>     Unicode Block “Braille Patterns” U+2800 - U+28FF
>     Unicode Block “Geometric Shapes” U+25A0 - U+25FF
>     Unicode Block "Box Drawing" and "Block Elements" U+2500 - U+259F
>

**Comment by aristocratos** [comment]
All text fields have width limits and the screen is not rendered line for line. So the only possible causes for a complete line being misaligned is a font issue or a terminal issue.

For similar error report in bashtop, see https://github.com/aristocratos/bashtop/issues/159

I'm pretty certain it's the Unicode Block “Braille Patterns” U+2800 - U+28FF that doesn't render correctly in your terminal.

**Comment by fonnesbeck** [comment]
OK, thanks. I know it does support 24-bit truecolor, I will look into the others.

**Comment by boppy** [comment]
I've had the same problem with the terminal emulator I used. Switching to the awesome and fully hackable [kitty](https://sw.kovidgoyal.net/kitty/) helped me out and reminded me to check for alternatives of often used software from time to time ;)

**Comment by fonnesbeck** [comment]
@boppy Thanks! I've installed kitty and it works great.
