### ISSUE TITLE
[BUG] [Ubuntu LTS 20.04] Unable to install bpytop because of the unavailability of latest version of python3-psutil

### ISSUE THREAD

**Issue by armujahid** [aristocratos/bpytop#377]
**Describe the bug**
Unable to install bpytop because of unavailability of latest version of python3-psutil

```
❯ sudo apt search bpytop
Sorting... Done
Full Text Search... Done
bpytop/stable,stable 1.0.68 all
  Linux/OSX/FreeBSD resource monitor that shows usage and stats for processor, memory, disks, network and processes.

❯ sudo apt install bpytop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bpytop : Depends: python3-psutil (>= 5.7.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**To Reproduce**

1. add Azlux's repository
2. run `sudo apt update && sudo apt install bpytop`

**Expected behavior**

it should install just fine.

**Info (please complete the following information):**
 - bpytop version: `bpytop -v`
 - psutil version: `bpytop -v` (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version: Ubuntu 20.04.3
 - Terminal used: zsh/bash
 - Font used:
 - Python version: 3.8.10

**Additional context**
```
❯ sudo apt search python3-psutil
Sorting... Done
Full Text Search... Done
python3-psutil/focal 5.5.1-1ubuntu4 amd64
  module providing convenience functions for managing processes (Python3)

python3-psutil-dbg/focal 5.5.1-1ubuntu4 amd64
  module providing convenience functions for managing processes (Python3 debug)

```

**Comment by janxkoci** [comment]
BTW I use `bpytop` even on 18.04 thanks to `conda`:

```bash
conda install -c conda-forge bpytop
```

I use `conda` for my science packages, it's a cross-platform package manager that works without root/sudo (designed for HPCs). But it [seems](https://pypi.org/project/bpytop/) `bpytop` is also available with `pip`, have you tried that?

**Comment by ROMVoid95** [comment]
@armujahid 
Before I even saw the installation method via APT, I used the pip install with the following

on my Ubuntu 20.04.4 LTS server instance

```bash
sudo apt install gcc python3-dev python3-pip
pip install --no-binary :all: psutil
pip3 install bpytop --upgrade
```

I know the pip command for psutil used pip but since these are the exact commands that produced a working install i went ahead and did not change them regardless of the pain my OCD is feeling right now, hope this helps.

**Comment by aristocratos** [comment]
@armujahid @janxkoci 
From [README.md#Installation](https://github.com/aristocratos/bpytop#installation):
> I only maintain the PyPi package, so will not take responsibility for issues caused by any other install method!

If there is an issue with a package that isn't the PIP package, you'll will have to contact the maintainer for the repository directly, it's unlikely that they will notice any issues posted here.

**Comment by armujahid** [comment]
Thanks. Closing this issue.
