### ISSUE TITLE
[REQUEST] Pause the Program

### ISSUE THREAD

**Issue by RyannDaGreat** [aristocratos/bpytop#381]
**Is your feature request related to a problem? Please describe.**
I tried to kill a process, in this case Vivaldi, but instead I killed my Python ML training process. There was a network spike, and by the time my keystroke was sent over it turned out the process taking most CPU at the moment was no longer Vivaldi, but instead Python. 

In addition, sometimes processes open and close quickly and it's would be nice to go in and analyze them by freezing time.

**Describe the solution you'd like**
I'd like the ability to pause the program, so that I can safely select and kill processes without worrying about lag spikes, or missing because I'm too slow. I'd like to press shift+P to pause the movement of all graphs and process CPU updates etc, so I can freeze time and go and kill any processes. We could press shift+P again to toggle time back on again.

**Describe alternatives you've considered**
Technically, I could go into the settings and slow everything down. But this solution isn't ideal, because after I kill the process I want to see the graph moving again.

**Additional context**

**Comment by UmarJ** [comment]
You can press `Enter` to select a process and then Terminate/Kill/Interrupt it.

**Comment by RyannDaGreat** [comment]
@UmarJ Thank you, that totally works for my use case!
