### ISSUE TITLE
"rawdict = _psplatform.disk_io_counters()" raises ValueError "not sure how to interpret line"

### ISSUE THREAD

**Issue by ri0t** [aristocratos/bpytop#4]
Upon startup, i see the intro screen (r'ly?) and it quickly bails out with:
> 03/08/20 (16:21:32) | ERROR: Data collection thread failed with exception: not sure how to interpret line '   8       0 sda 61540896 14301543 2070222521 18032078 107627996 33672188 4122914856 94277324 0 74681256 32698424 0 0 0 0\n'
Traceback (most recent call last):
  File "./bpytop.py", line 2315, in _runner
    collector._collect()
  File "./bpytop.py", line 2578, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 2013, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1081, in disk_io_counters
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 61540896 14301543 2070222521 18032078 107627996 33672188 4122914856 94277324 0 74681256 32698424 0 0 0 0\n'
03/08/20 (16:21:32) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 

Need any more data?

**Comment by aristocratos** [comment]
> intro screen (r'ly?)

It can be disabled :)

I'm pretty sure you've got an outdated psutil version. You can check which version you got by running `bpytop -v`, it shows both bpytop version and psutil version.

Psutil versions below 5.7.0 crashes during `psutil.disk_io_counters()` command if you're running linux kernel 5.

I'm guessing you are running ubuntu/debian or a derivative there of? They likely have an outdated version in the distribution packages.

You can try updating psutil in that case with `sudo python3 -m pip install psutil --upgrade`.

**Comment by ri0t** [comment]
Uh, yeah, i could.

> Version table:
     5.7.2-1 -10 
        -10 http://httpredir.debian.org/debian sid/main amd64 Packages
     5.5.1-1 500 
        500 http://httpredir.debian.org/debian buster/main amd64 Packages
     5.0.1-1 500 
        500 http://httpredir.debian.org/debian stretch/main amd64 Packages

I think, you should catch that exception and either ignore it (disables functionality?) or put a warning in front - or use a workaround.

If i were to install this in a virtual environment, i would gladly pip-install --upgrade psutil :grinning:

**Comment by aristocratos** [comment]
Well, the dependencies in the readme does list:

> **[psutil python module](https://github.com/giampaolo/psutil)** (v5.7.0 or later)

But you're right, will add an exception catch and log to error.log since it's not fatal and would only result in disk read/write speeds not being reported.

**Comment by aristocratos** [comment]
Exception handling added in v1.0.1
