### ISSUE TITLE
disply color problem screen[BUG]

### ISSUE THREAD

**Issue by Ludo-code** [aristocratos/bpytop#400]
**Describe the bug**

When trying to use bpytop with the screen command he have some trouble with color sheme And with the different command. In addition, the first screen is on ssh and screen command and the second on only ssh.

**To Reproduce**

Create a screen session with screen -S yourname -d -m bpytop

 to connect into screen -x yourname

and the result is : 

![image](https://github.com/aristocratos/bpytop/assets/56892223/343ec45a-22d6-49f1-831c-87427ac2c33f)

**Expected behavior**

The display must be like this : 

![image](https://github.com/aristocratos/bpytop/assets/56892223/19320599-6f2c-40f9-a441-14185d56aa93)

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - bpytop version: 1.0.68
 - psutil version: 5.9.2
 - (Linux) Linux distribution and version: Fedora 38
 - (OSX/FreeBSD) Os release version: 6.3.6-200.fc38.x86_64
 - Terminal used: Windows terminal with ssh
 - Font used: Cascadia Mono
 - Python version, `python3 --version` (version 3.6 or above is required): 3.11.3

**Additional context**

contents of `~/.config/bpytop/error.log`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by or-dodson** [comment]
I was having the same issue as you initially. I tried searching around a bit, and I found [this question][https://apple.stackexchange.com/questions/362889/color-problem-in-terminal-mojave] on apple stackexchange. I installed iterm, and bpytop displays properly on it. If this is the same issue, then the lack of True Color support in terminal.app is to blame.

**Comment by Ludo-code** [comment]
Thanks you for your reply it's working after some change according of our reply.
