### ISSUE TITLE
Allow installation without admin privileges [REQUEST]

### ISSUE THREAD

**Issue by josephcslater** [aristocratos/bpytop#41]
Not all potential users have administrative privileges due to institutional restrictions. 

I use this on my personal machine, but cannot on work because of it restrictions (they would need to insteall each and every update for me!

Can this be designed in such a way that it can be used by only a single user without admin privileges?

**Comment by aristocratos** [comment]
There's nothing stopping you installing anywhere you want.

I you want to install with the Makefile use the PREFIX variable to set location. `PREFIX=/home/user/programs make install`

Easier might be to just make a alias to `bpytop.py` from the cloned directory in your shell config file. Then you can update the git repository and not need to reinstall anything.

To have access to the themes without copying to /usr/share they need to be placed in ~/.config/bpytop/themes

**Comment by jessica02200** [comment]
Thank you I would love to download this
