### ISSUE TITLE
need a little help

### ISSUE THREAD

**Issue by Nicon4454** [aristocratos/bpytop#419]
Hello i am not sure what is wrong. i know it is on my end and not a problem with bpytop but i am at a loss
can someone help me figure out how to fix this.
i am using ubuntu 22.04LTS connecting using kitty/putty
![Screenshot 2024-05-22 211856](https://github.com/aristocratos/bpytop/assets/3824774/099de787-1ea9-4f99-98e4-db9d34f49733)

**Comment by Nicon4454** [comment]
Really no one can help me with this?

**Comment by neonrust** [comment]
Tried any other terminals? I have no idea if kitty/putty supports all the "trickery" btop is up to for the rendering.

**Comment by aristocratos** [comment]
@Nicon4454 
Read the README.md and help yourself https://github.com/aristocratos/bpytop#prerequisites
