### ISSUE TITLE
Network graph zooms way out during internet speed test

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#50]
While playing around with #49 yesterday I was able to make a few observations about how the network graph actually functions. During internet speed tests I noticed that the graphs would zoom way out for some reason.
![Screenshot from 2020-08-10 10-38-59](https://user-images.githubusercontent.com/17794391/89802422-1f972d80-daf7-11ea-94f6-2a06d2fd34c7.png)

Given that bpytop doesn't know what your actual top speed is and only knows what it has recorded it makes sense that it should zoom out but this may be a tad excessive of a zoom-out. Whats even odder about it is it happens several seconds after the data has stopped and then it zooms way in again the next zoom adjustment.

**Comment by aristocratos** [comment]
I'm guessing you toggled "auto" some time during the speed test? Right now the "auto" toggle forces the "lower" variable to be triggered to rescale the graphs when toggling. That however means that the value will be set to 3 * last highest value.

So right now if the speed is more than "max min value" / 3 when you toggle, the graphs while scale over current "max min". Need to rework the toggle to have it's own separate rescaling to resolve it.

**Comment by drazil100** [comment]
I was intentionally using "auto" for this test. This is more an observation than anything which is why I chose not to label it as bug or feature request. 

3 * on a max value seems a little excessive in my opinion as you end up losing out on a lot of detail. When zooming in on the small stuff 3 * makes way more sense. It might be a good idea to scale it by different amounts based on how close the value you are scaling against is to the recorded top speed. Maybe something like 3 * at 0 speed to 1.5 * or less at top speed. This would give it plenty of room to expand while zoomed in without losing nearly as much detail while zoomed out.

**Comment by drazil100** [comment]
Oh I just looked at what you said in #29 on how auto works. Rather than +20% on a raise and *3 on a lower it would probably be best to do 1.2* top speed and *3 at bottom speed and linear interpolate between those 2 scale factors.

**Comment by aristocratos** [comment]
Not sure if I feel that's necessary, the 3x is only triggered if values consistently has been below 10% of current max and the +20% if it consistently has been over 100%.

But a rework of the rescaling while toggling "auto" is needed.

**Comment by aristocratos** [comment]
I could probably just force the value to be the manual value when turning auto off, it can still rescale up if needed, but the toggle in itself shouldn't rescale to any other value than the user set one.

**Comment by aristocratos** [comment]
I could also enable the user to set value the "raise" and "lower" will trigger at. Right now it's hardcoded to 5.

**Comment by drazil100** [comment]
I think the raise and lower counter value is fine and you should avoid bogging down the options menu with TOO many options (you don't want to become plasma's settings). I agree with the reexamination of manual's scaling too that has been a little funky.

Ultimately though I think something could be done about this.
![Screenshot from 2020-08-10 13-15-39](https://user-images.githubusercontent.com/17794391/89816255-d8676780-db0b-11ea-91f1-4201b01592cb.png)
![Screenshot from 2020-08-10 13-15-45](https://user-images.githubusercontent.com/17794391/89816262-ddc4b200-db0b-11ea-8912-674e915a4e71.png)
![Screenshot from 2020-08-10 13-16-01](https://user-images.githubusercontent.com/17794391/89816276-e2896600-db0b-11ea-8416-914258837cc4.png)
![Screenshot from 2020-08-10 13-16-12](https://user-images.githubusercontent.com/17794391/89816290-e74e1a00-db0b-11ea-8f43-a55a92fab973.png)
There is no reason it should zoom out that much before it zooms back in.

**Comment by drazil100** [comment]
Anyway I have shared my thoughts on the subject. It honestly works just fine overall so if this doesn't get addressed I won't complain. Just wanted to share my observations and thoughts :P

**Comment by aristocratos** [comment]
Huh, just noticed it happening too when running a speedtest. It's likely I messed something up when adding the manual setting. Because it seems "raise" gets triggered a second time even though the speeds are lowering...

**Comment by drazil100** [comment]
Ok so this IS a bug. Probably should have tagged it as such when I posted the issue but I wasn't sure xD

**Comment by aristocratos** [comment]
Yeah, but I'm not quiet sure what's going wrong. Don't have time to trace it now, but that function needs some refactoring anyways, so gonna rewrite it when I've got some time.

**Comment by drazil100** [comment]
> I could probably just force the value to be the manual value when turning auto off, it can still rescale up if needed, but the toggle in itself shouldn't rescale to any other value than the user set one.

After playing around with it for a few days I kinda agree. Since there is a quick toggle in place to switch to auto I think manual probably has way more value if it is completely fixed (even if the data extends outside the viewable range).

**Comment by aristocratos** [comment]
Fixed in v1.0.15

**Comment by drazil100** [comment]
You have done fantastic work. Not just here but everywhere. Thanks for everything you have done bpytop is amazing :+1:

**Comment by aristocratos** [comment]
Thank you :)

And thanks for helping make bpytop better!

Let me know when you've got your theme ready and I'll add it to the repository if you want.

**Comment by drazil100** [comment]
I was thinking of submitting it by pull request. I plan to wait a bit to submit it until I am confident i'm done tweaking it. Still trying to figure out a name. Nightshift is my working title and while its probably generic enough thats what apple calls their blue light filter so even if its legally fine it kinda bothers me. If you have any thoughts on a name im open to suggestions (though can't promise ill go with it if I find something I like better).

Here is how it looks currently.
![Screenshot from 2020-08-15 18-34-48](https://user-images.githubusercontent.com/17794391/90323369-fd057a00-df25-11ea-9339-cf082bd1d157.png)

**Comment by aristocratos** [comment]
If you wanna keep the name inspired by "Nightshift" but not the same, maybe something like "Blueshift"?

**Comment by drazil100** [comment]
I am more attached to the night portion of the name than the shift potion. Original working title was blue and orange but went towards nightshift since the cpu gradient is kinda like a color temperature gradient and it has a bit of a city lights vibe to it. I am also investigating space themed names for the same color temperature reasons as its also similar to the colors stars can be. But that kinda loses the city lights thing.
