### ISSUE TITLE
bpytop crashes when using left/right errors repeatedly on OSX

### ISSUE THREAD

**Issue by trekie86** [aristocratos/bpytop#51]
Just installed bpytop and followed the procedures to add all of the required dependencies. When using the program, it seems fine for a bit until I use the left/right arrows to manipulate the process tree. Then it suddenly crashes. The excerpt from the error log is below:

`10/08/20 (11:22:33) | ERROR: Data collection thread failed with exception: '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 2365, in _runner
    collector._collect()
  File "/usr/local/bin/bpytop", line 2947, in _collect
    for p in sorted(psutil.process_iter(cls.p_values + ["memory_info"] if CONFIG.proc_mem_bytes else [], err), key=lambda p: eval(sort_cmd), reverse=reverse):
TypeError: '<' not supported between instances of 'float' and 'str'
10/08/20 (11:22:35) | WARNING: Exiting with errorcode (1). Runtime 0:01:30`

**Comment by aristocratos** [comment]
Ok, now I remember why I had a string conversion there and probably shouldn't have removed it to fix a sorting error :)

Gonna look into it.

**Comment by aristocratos** [comment]
Fixed in v1.0.11
