### ISSUE TITLE
[BUG] CPU box linebreaks on small terminals

### ISSUE THREAD

**Issue by inkeso** [aristocratos/bpytop#53]
**Describe the bug**

If the terminal window is small (80x24-26) and the core-count is 12, the avg. load breaks to next line:
![12core](https://user-images.githubusercontent.com/6339109/89829928-ae3d9600-db5b-11ea-937d-762d70fc1004.png)

**To Reproduce**

Start bpytop in a 80x25 window on a system with 12 cores.

**Expected behavior**

Something like how it looks, if terminal-size is 27 lines or more (Or CPU count is lower).
Or probably just with the avg Load omitted, if it doesn't fit well.

**Info**
 - bpytop version: 1.0.10
 - psutil version: 5.7.2
 - Linux distribution and version: arch with kernel 5.4.55-1-lts
 - Terminal used: xterm 358
 - Font used: 6x13U (bitmap)
 - Python version: 3.8.5

**Comment by aristocratos** [comment]
Fixed in v1.0.11
