### ISSUE TITLE
[REQUEST] Please brighten and move the uptime indicator

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#54]
![Screen Shot 2020-08-10 at 1 31 25 PM](https://user-images.githubusercontent.com/64876997/89833744-09489c00-db0e-11ea-83a2-770d1d48ba58.png)

I have a lot of fairly old laptops and screens on which I've been using both bashtop and now bpytop. They don't have the best contrast anymore, even the ones that started out as a world-class Apple IPS panel. So for a long time I kept wondering why there was a weird glitch in the bottom left CPU graph. 

In other words, the font color of the uptime indicator is so dark that until I squinted at it up close on a better monitor, **I couldn't tell there was anything there but a group of black squares interfering with the CPU graph rendering**. 

Please consider making the uptime indicator at least as bright as the colored characters that indicate keyboard shortcuts. 

Also, it would really be nice to see the uptime move up into the "menu bar" area. Right next to the update interval display would be a great place for it. It would help balance all the words that are now on the left side and would no longer mar the CPU graph. It looks really ugly during a stress test. 

The upload/download speed indicators in the corner of the network graph are suffering from the same problem. They're just too dark for anyone who doesn't have a high-contrast screen.

**Comment by drazil100** [comment]
Please brighten up all of these labels. The network range labels are also hard to read.

**Comment by RedBearAK** [comment]
I have to add to this that all the words at the bottom right under the process list are also completely unreadable on my 2007 MacBook. Everything to the right of where it says "select". 

It's really as if there's nothing there. 

This is in Linux Mint 20, XFCE, Xfce Terminal. And the screen has actually been calibrated to be the best it can be, and it still looks pretty good actually. But those dark letters are invisible. Not just dim. Invisible. 

Changing the theme to "default black" helps a lot, but they are still much dimmer than they should be.

**Comment by drazil100** [comment]
I fault those less cause when they they only matter when you are selecting a process in which case the light up. The other labels are always hard to read.

**Comment by RedBearAK** [comment]
That's true, they highlight when you select a process, but the dim version should just be the color of the gray highlighted shortcut key letters. Otherwise it just looks like something's missing. 

> I suspect if he fixes one they will all be updated at the same time though.

Hope so. All these dark characters are really the only visual flaw in the whole app.

**Comment by aristocratos** [comment]
All the text elements mentioned is set by the theme variable "inactive_fg" in the default theme set to #404040 or rgb(64, 64, 64). If you use the default theme the background is transparent, so if your background is close to #404040 the text would be less readable.

There is two solutions to this:
1. Change theme to "default_black" which sets the background colour to #000000.
2. Make a copy of "default_black" (remove main_bg value if you want transparent) and adjust "inactive_fg" to a lighter colour.

**Comment by drazil100** [comment]
I use default_black personally already. My screen is just REALLY terrible. I end up losing a lot of my darker colors to the gamma adjustment I need to do to have remotely accurate colors. I'd show you but I don't know how I could possibly capture it with a camera. 

I get that's a me problem for buying a laptop with a terrible screen but I don't think it would be too unreasonable to brighten up that color a bit. 

Playing around with it #606060 seems pretty reasonable. Still darker than hi_fg but not so dark it's difficult to read. (This is for default_black by the way haven't tried messing with default)

**Comment by drazil100** [comment]
Playing around with making my own theme and I am starting to see why that color was set so dark. It is also the same color used for the background of the not graph percentage bars for memory and disk usage.

**Comment by aristocratos** [comment]
> (By the way I don't know how this looks on an actually good display yet I haven't tried)

Changing the default values to accommodate for having a bad monitor doesn't feel like a good move. But if you're up for making a more "high contrast" version of the default theme, I'll gladly put it in with the rest of the themes in the repo.

**Comment by RedBearAK** [comment]
> Changing the default values to accommodate for having a bad monitor doesn't feel like a good move. But if you're up for making a more "high contrast" version of the default theme, I'll gladly put it in with the rest of the themes in the repo.

As an end user I strongly disagree with this. There will always be many more monitors in existence with imperfect contrast than there ever will be with excellent high contrast. Even the best monitors always fade a bit over time. All we are really asking is for the default theme to be more readable on the **average** monitor. Most of the monitors I am dealing with would not be called "bad" by most people. 

It would make much more sense to have a good default theme that is at least readable everywhere, and then an optional lower contrast theme for anyone who wants to tone things down on a high contrast HDR display.

**Comment by drazil100** [comment]
Thats a reasonably argument. It is on me for not researching the monitor of my machine before buying it. Still I think this is a bit of an accessibility issue that some people can't read or have difficulty reading these labels.

@RedBearAK What would you change it to? (just curious)

**Comment by aristocratos** [comment]
> There will always be many more monitors in existence with imperfect contrast than there ever will be with excellent high contrast

Sure, but I would argue that any monitor that can't properly distinguish between (0, 0, 0) and (64, 64, 64) are a lot worse than average. Of course the transparent background on the default theme could be an issue, which I could change to be true black by default.

**Comment by aristocratos** [comment]
Come to think of it, I could add a toggle for transparent background regardless of what theme that's being used.

**Comment by drazil100** [comment]
Thats an interesting idea. Though I always choose default_black anyway.

**Comment by aristocratos** [comment]
Color brightness increased in v1.0.14

**Comment by drazil100** [comment]
This is way more readable <3

**Comment by aristocratos** [comment]
I only changed the values for the default theme, "default_black.theme", "monokai.theme" and "gruvbox_dark.theme" any other theme has to be manually adjusted for brighter "graph_text" color.
