### ISSUE TITLE
[REQUEST] Give the background of percentage bars their own color in the theme.

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#56]
As mentioned in #54 the labels for uptime and network ranges are too dark however they can't reasonably be brightened up without also brightening up the backgrounds of percentage bars.

As a result I am forced to make a choice between this where the labels are hard to read...
![Screenshot from 2020-08-11 05-32-53](https://user-images.githubusercontent.com/17794391/89887568-2b84fd00-db94-11ea-91c4-901661b77e88.png)

and something else where the bars backgrounds are much brighter that doesn't look as good but I can actually read the text.

**Comment by aristocratos** [comment]
The uptime and network current max values was a late addition and I reused the "inactive_fg" color for them.

I could create a seperate color for them instead, maybe something like "graph_text" since they only appear over graphs. And if the "graph_text" color value is missing from the current theme it would default to "inactive_fg" color.

**Comment by drazil100** [comment]
Honestly that would probably be a reasonable solution. The problem as I see it is you are using inactive_fg as both a foreground color that needs to stand out against a dark background and a background color that needs to stand out against the bright percentage bar colors. You can't increase the contrast of one without decreasing the contrast of the other.

**Comment by drazil100** [comment]
![Screenshot from 2020-08-11 22-40-46](https://user-images.githubusercontent.com/17794391/89972930-b4e41000-dc24-11ea-8272-75d1d94813fe.png)
My personal theme is almost done but im waiting for the opportunity to brighten up the graph text to call it complete. I don't have a name for it cause its my own custom palette but was curious if there was any chance you wanted a copy of it when it's done? (I would need a name for it first ofc)

**Comment by aristocratos** [comment]
> but im waiting for the opportunity to brighten up the graph text to call it complete

I'm working on adding some additional theme color values, will be in an update later this week.

> was curious if there was any chance you wanted a copy of it when it's done?

Absolutely, just come up with a fancy name and I'll add it to the repository :)

**Comment by aristocratos** [comment]
@drazil100 
I've added "graph_text"  and "process_start", "process_mid", "process_end" for custom gradient in the processes box.

 Any more values you would like to see added?

**Comment by drazil100** [comment]
How will the process gradient work with existing themes?

**Comment by drazil100** [comment]
Also I do think that inactive text when you aren't hovering over any processes should be separate from the percentage bars. Can be the same color as graph text but at the very least should probably be configurable without adjusting the bar colors.

**Comment by drazil100** [comment]
That's the only thing I can really think of though. Cant wait to try it :P

**Comment by aristocratos** [comment]
The process gradient will default to the cpu gradient if missing (like it is now). The "graph_text" will default to "inactive_fg" if missing. 

Sure thing, can add "meter_bg" for the percentage meter backgrounds, and default it to "inactive_fg" if missing.

**Comment by drazil100** [comment]
OOOOOH I thought you meant the process gradient was for "Proc gradient" where the processes fade  the further from the selected process they are. Not the secondary color.

**Comment by aristocratos** [comment]
The fade gradient is tied to "main_fg" and "inactive_fg", and would like to keep it that way since when both "proc_colors" and "proc_gradient" is enabled it's using two different gradient arrays to calculate both fade and color which would get pretty messy if both were custom gradients.

**Comment by drazil100** [comment]
I would like you to keep it that way too. I don't really want to have to configure the main proc gradient in my theme. proc color gradient is a nice option though.

**Comment by aristocratos** [comment]
@drazil100 
Added in v1.0.14
