### ISSUE TITLE
[REQUEST] PPA for BPyTOP like BashTOP

### ISSUE THREAD

**Issue by Schykle** [aristocratos/bpytop#58]
Wondering if we could have a PPA for BPyTOP similar to the one available for BashTOP

**Comment by azlux** [comment]
I can. :blush:

**Comment by aristocratos** [comment]
Awesome! Just a notice though, will likely be some directory restructure in a update this week or the next when I setup pypi packaging. I guessing that will interfere with the auto deb packaging?

**Comment by jawz101** [comment]
I'd say snap package or flatpak to be installable by more distro over rpms and debs

**Comment by Schykle** [comment]
@jawz101, there is a Snap for BPyTOP already (https://snapcraft.io/bpytop) and Flatpaks aren't designed to provide CLI runners.

**Comment by kushalpandya** [comment]
I followed snap install instructions but I can run `bpytop` only using sudo, is there a way to run it without sudo?

**Comment by azlux** [comment]
`bpytop` have been added to my apt repo. https://packages.azlux.fr/
Updates are based on GitHub tags. (checked every days)

**Comment by aristocratos** [comment]
@azlux 

Thank you! Will add to the readme.

**Comment by azlux** [comment]
FYI : snap isn't up-to-date, do you know who manage this one ?

**Comment by aristocratos** [comment]
@azlux 
Yeah, @kz6fittycent we are currently discussing the snap in #101 :)

**Comment by kz6fittycent** [comment]
For anyone reading this:

If you want the latest (successful) build - run this: `sudo snap refresh --edge bpytop` or if you're installing it for the first time, `sudo snap install --edge bpytop` - hope this helps.
