### ISSUE TITLE
[BUG] rxvt-unicode compatibility seems broken

### ISSUE THREAD

**Issue by ri0t** [aristocratos/bpytop#6]
**Describe the bug**

rxvt-unicode display is quite broken. Also, mouse support seems to be kind of defect.

**To Reproduce**

* Install rxvt-unicode ( 9.22-1+b1 here)
* run bpytop.py

**Expected behavior**

* Normal display
* mouse handling should work

**Screenshots**

![Bildschirmfoto_2020-08-03_17-33-10](https://user-images.githubusercontent.com/1938065/89201857-672b3000-d5b2-11ea-8b03-9b0caab1a2ef.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.0
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Debian Stretch with a few buster/sid/experimental upgrades
 - Terminal used: rxvt-unicode
 - Font used: Ormaxx
 - Python version, `python3 --version` (version 3.6 or above is required): 3.7.2+

**Additional context**

May be related to additional xressources (although i can't see any related)

**Comment by inkeso** [comment]
This happens because rxvt doesn't handle RGB color codes (ESC[38;2;R;G;Bm) correctly. 
As a workaround, you could run bpytop inside tmux, which will compensate for that.

**Comment by aristocratos** [comment]
See https://github.com/aristocratos/bpytop#prerequisites

Updated with a list of terminals supporting truecolor.

**Comment by aristocratos** [comment]
Will update prerequisites if I find a list of terminals with proper mouse support. But I'm guessing most of the terminals with truecolor support will also have mouse support since they both rely on modern escape sequence standards.
