### ISSUE TITLE
[REQUEST] Similar Layout To BashTOP

### ISSUE THREAD

**Issue by Schykle** [aristocratos/bpytop#62]
I was told by multiple people that BPyTOP is supposed to replace BashTOP, but the struggle I'm having with this is that I love BashTOP _especially_ for its layout. Despite the massive improvements in performance and really cool features, the layout in my opinion has taken an aesthetic hit in BPyTOP over its BashTOP predecessor.

**Describe the solution you'd like**
A 1:1 BPyTOP style/layout that makes switching over from the BASH version essentially no-compromise.

**Describe alternatives you've considered**
I've fiddled about in the options menu to no avail, nothing seems to restore the original BashTOP style.

**Comment by aristocratos** [comment]
Wut? I have no idea what you are talking about.

bashtop left, bpytop right:
![scr-compare](https://user-images.githubusercontent.com/59659483/90269400-daf1f600-de58-11ea-8941-24e0aeb31456.png)

**Comment by drazil100** [comment]
Maybe he is talking about the memory box in which pressing g and s should make it exactly like bashtop.

**Comment by drazil100** [comment]
Either than or he prefers it to say Core1 instead of C1

**Comment by aristocratos** [comment]
I don't know if I would refer to that as layout changes resulting in any "compromise" between the two.

**Comment by drazil100** [comment]
Me neither but those are the only differences I can find.

**Comment by Schykle** [comment]
On my machine, the main graph for CPU is shrunk heavily to the left, leaving me little room for it, and much space taken by the individual core monitors on the right.
![image](https://user-images.githubusercontent.com/58709504/90294509-75dbd780-de3b-11ea-851d-23b5b56111a4.png)

**Comment by aristocratos** [comment]
You are also missing two cores in bashtop in this screenshot because they don't fit. Bpytop will resize the core graphs if they take up more than 3/4 of the cpu box window. You can resize the window until you get a desired layout.

Btw, the all the graphs in bpytop shows double the amount of history compared to what bashtop does by default, so in this screenshot you're actually seeing as much or more cpu history in bpytop.

> And the disk/space monitors are different as well.

The only difference in the disks box is the divider line going through the titles which is barely visible because of the transparent background.

**Comment by Schykle** [comment]
Interesting. Is there any way I can reduce the amount of resizing it does via config, maybe by shrinking the core graph widths?

As for the graphs, I specifically mean the styling and types of graphs shown. I prefer the bar-style with the gradient through it, and none of the themes seem to restore that for me.

**Comment by aristocratos** [comment]
https://github.com/aristocratos/bpytop/issues/62#issuecomment-674158590
> Maybe he is talking about the memory box in which pressing g and s should make it exactly like bashtop.

Did you press "g" as in graph. Also an option called "mem graphs" that toggles this.

> Is there any way I can reduce the amount of resizing it does via config

No, this is fixed to be able to accommodate any number of cores.

You'll have to resize the window to change the scaling.

**Comment by aristocratos** [comment]
Lowered the sizing requirement when it re-scales from 3/4 to 2/3 in v1.0.16

**Comment by Schykle** [comment]
Thank you for looking into this and being so accommodating. I definitely realize it's not a functional request and purely an aesthetic stubbornness of mine. I appreciate your time!
