### ISSUE TITLE
[BUG] Correct Core Numbering

### ISSUE THREAD

**Issue by adrian-enspired** [aristocratos/bpytop#63]
**Describe the bug**

CPU cores are listed as "Core1", "Core2", etc.. 

No (modern, or any, that I'm aware of) AMD or Intel CPU numbers their cores starting from 1; they all start from 0. 
For example, on my system, running `lscpu` displays:
```
CPU(s):                          24
On-line CPU(s) list:             0-23
```
Yet bpytop lists "Core1" .. "Core24".

This misnumbering is unexpected and makes correlating with other monitoring tools difficult and error-prone.

**To Reproduce**

Run bpytop and look at CPU widget.

**Expected behavior**

CPU cores should be listed accurately, as "Core0", "Core1", etc.; or there should at least be a display option for switching between "correct" and "human-friendly" mode or similar.

**Info (please complete the following information):**
 - bpytop version: 1.0.3
 - psutil version: 5.5.1
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - Terminal used: Gnome
 - Font used: monospace regular
 - Python version: 3.8.2

**Additional context**

not applicable

**Comment by aristocratos** [comment]
You should probably make a "bug" report with `htop` also then...

![scr-htop](https://user-images.githubusercontent.com/59659483/90270071-e5f95600-de59-11ea-9077-ef5800e8a381.png)
