### ISSUE TITLE
[BUG] Two color gradients not working

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#64]
In all the theme files there are comments at the top explaining gradients

```
# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient
```
However when I removed some of the mid gradients I noticed some problems. I removed all mid gradients and this is the result.
![Screenshot from 2020-08-14 14-18-50](https://user-images.githubusercontent.com/17794391/90285285-344a2d00-de39-11ea-99c2-556a4b55a5d7.png)

**Comment by aristocratos** [comment]
Whoops, gonna take a look at it.

**Comment by aristocratos** [comment]
@drazil100 
Actually, seems to be working. Did you remove the whole line? In that case it will default to the value from the default theme, the variables need to be present but empty like `theme[cpu_mid]=""`

Should probably have included that in the description.
