### ISSUE TITLE
[BUG] Net upload does nothing

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#65]
Changing net upload does nothing. It just sets itself on the graph to the same thing as Net download.

**Comment by aristocratos** [comment]
Forgot a value when I moved that code block into a iteration loop. Will be fixed in next update.

**Comment by drazil100** [comment]
Its also worth mentioning (in the event it needs it needs to be fixed in a separate place) the fixed color scaling for upload is also tied to download.

**Comment by aristocratos** [comment]
Fixed in v1.0.16
