### ISSUE TITLE
[BUG] Glitching in init on a Linux Mint 20 system

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#66]
I am experiencing a bunch of "glitch" type temporary errors being displayed during the init screen, but it usually goes away so fast I can't even catch a screenshot of what it says. It seems to happen during the "Doing some maths and drawing" phase of the init screen. It throws text all over the bottom half of the terminal window, then almost immediately disappears and the green check mark appears, and then the init process continues. 

This is on a 2007 MacBook with (as far as I know) a fairly clean install of 64-bit Linux Mint 20, so I really want to get to the bottom of whatever I'm seeing. 

If you can briefly tell me where to find the bpytop error log and what log level to set in the menu to hopefully catch these errors, I will try to clear the log and then get a clean log file with a single run of bpytop at the appropriate log level.

**Comment by aristocratos** [comment]
Follow the [bug report template](https://github.com/aristocratos/bpytop/issues/new?assignees=aristocratos&labels=bug&template=bug_report.md&title=%5BBUG%5D) and you will also find the error log.

**Comment by RedBearAK** [comment]
Oh, I thought the template was more generic. Found the error log and ran bpytop with `--debug`, but the error log that was produced doesn't seem to have caught the errors I was seeing during init. This is all it showed after a test run (I saw the errors on screen again). 

```
16/08/20 (17:08:17) | INFO: New instance of bpytop version 1.0.16 started with pid 2848
16/08/20 (17:08:17) | INFO: Loglevel set to DEBUG
16/08/20 (17:08:17) | DEBUG: Using psutil version 5.5.1
16/08/20 (17:08:17) | DEBUG: CMD: /usr/local/bin/bpytop --debug
16/08/20 (17:08:19) | DEBUG: Collect and draw completed in 0.262897 seconds
16/08/20 (17:08:20) | DEBUG: Init completed in 2.499316 seconds
16/08/20 (17:08:21) | INFO: Exiting. Runtime 0:00:04 
```

Suggestions? 

What I'm thinking of at the moment is finding a place in the code to put a "pause" (like a "sleep 60") that would allow me to hopefully catch a screenshot of what's happening.

**Comment by RedBearAK** [comment]
I was unsuccessful in getting a time.sleep(30) command to work for reasons I don't understand (`import time` is there at the top), but at least it did cause the init process to show just long enough to catch a screenshot. 

The issue might be with psutil? Still, the errors should be getting caught by bpytop and sent to the error log, I would think. 

![bpytop_init_bug](https://user-images.githubusercontent.com/64876997/90349757-68635080-dfe7-11ea-8652-78c912f37248.png)

**Comment by RedBearAK** [comment]
If I'm interpreting things correctly it seems to be this line that results in the errors in the screenshot. 

```
if CONFIG.check_temp: CpuCollector.get_sensors()
```

Got the sleep command working with `sleep(30)` instead of `time.sleep(30)`.

**Comment by RedBearAK** [comment]
Looking closely at the CPU temps being reported I notice that the "CPU" temp always matches the "C1" temp, while the "C2" temp is usually a few degrees higher. Like, 2-4 degrees higher, it varies. But CPU and C1 are always the same. 

Maybe something is confused about the sensor layout because this is a MacBook? (A 2007 MacBook3,1 model if that matters.)

**Comment by aristocratos** [comment]
> Using psutil version 5.5.1

That's likely that cause of your troubles since psutil 5.7.0 is required.

**Comment by RedBearAK** [comment]
I'm going to keep looking around, but I'm at a loss so far to understand how I ended up with a version of psutil that is too old, on a relatively recent fresh install of Linux Mint 20. Pretty sure I installed it with `python3 -m pip install psutil` as recommended on the bpytop GitHub home page, and when I try to run the command again it says `Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (5.5.1)`. 

So I don't really understand how I'm supposed to get the correct version installed. I mean, other than installing it manually from the psutil GitHub.

**Comment by aristocratos** [comment]
It's possible you already had installed from your distribution and the distribution package is outdated.

To force upgrade you can run `sudo python3 -m pip install psutil --upgrade`

**Comment by RedBearAK** [comment]
OK, I tried to do it manually before I saw your reply, but I was able to uninstall that and then do the upgrade. 

Seems to have worked. The error during init has disappeared. 

So maybe I didn't install psutil and Linux Mint 20 just came with an old version. Which seems very odd unless you're using bleeding edge new features recently added to psutil. I can't see any releases page for psutil, so I'm not sure how to discover when 5.5.1 might have been released. 

Ah, found the history file. 5.5.1 is from 2019-02-15. Guess Mint was too conservative to keep the package updated. 

Recommendation: Change the command on the home page from `sudo python3 -m pip install psutil` to `sudo python3 -m pip install psutil --upgrade` to avoid this issue on other conservative distros.

**Comment by RedBearAK** [comment]
Another suggestion: Perhaps you should be notifying the user if their psutil is out of date, if 5.7.0 is really a requirement? You are definitely using a very recent version of psutil as a requirement. It only came out in February of this year. 

You could even consider spitting out the relevant update command to help users figure out how to get it updated.

**Comment by aristocratos** [comment]
> Recommendation: Change the command on the home page from sudo python3 -m pip install psutil to sudo python3 -m pip install psutil --upgrade to avoid this issue on other conservative distros.

I'm not sure, since it does break distribution packaging if already installed and there is the risk it gets downgraded by the package manager. It does however run with older versions but not as well. The reason for 5.7.0 requirement is that disk read and write will not work on linux kernel 5 with older psutil versions.

**Comment by aristocratos** [comment]
> Another suggestion: Perhaps you should be notifying the user if their psutil is out of date, if 5.7.0 is really a requirement? You are definitely using a very recent version of psutil as a requirement. It only came out in February of this year.

It does notify in the log file if psutil is outdated and it runs in to an error related to disk stats. And the dependencies clearly states psutil 5.7.0 or later and I don't think it's too much to ask that people read the dependencies.

I even added the psutil version number when running `bpytop -v` just to make it easy to see which version you have.

I could change it so bpytop won't start when using psutil versions below 5.7.0 but I'm pretty sure the issues would be overflowed with people not having checked the dependencies.

**Comment by RedBearAK** [comment]
A simple notification that the psutil is below the required version would be helpful. Perhaps brought up as a dismissable dialog similar to the menu. 

Your menu system is quite nice by the way. The whole app is more usable and understandable than 99% of the terminal apps I've ever seen. Especially the instant discoverability of the relevant keyboard shortcuts. Really top notch work.

**Comment by RedBearAK** [comment]
Many people will be like me and assume that if the program runs successfully then that means all the dependencies must have been met, without looking more closely at the details of version numbers. Until we encounter a bug like I did. 

The `bpytop -v` output that also shows psutil version is a nice feature.

**Comment by aristocratos** [comment]
Thanks :)

Sure could add a notification at start that delays the start for one second to bring home the point, but I can almost guarantee that I will still get bug reports caused by psutil being too old.

**Comment by RedBearAK** [comment]
I see now that it says `DEBUG: Using psutil version 5.5.1` in the error log, but I'm sure I just glossed over that without paying attention because it doesn't say anything about the version being outdated. To someone unfamiliar with the requirements or with debugging messages, it is very easy to assume that line was simply informational, rather than indicating an "error". Think about adding slightly more context about it being outdated, old, not meeting the minimum 5.70 requirement. Something like that. 

>Sure could add a notification at start that delays the start for one second to bring home the point, but I can almost guarantee that I will still get bug reports caused by psutil being too old.

Yes, that's why I suggested a dismissable "dialog" popup that would overlay the graph. You could even do "OK" and "Don't remind me again" choices, since things will mostly work even if psutil is too old. But at least then the user will have taken an active part in noticing the version mismatch and choosing to ignore it. Should drastically reduce bug reports like mine.

**Comment by RedBearAK** [comment]
Anyway, I guess this bug is resolved and you can close this if you want.

**Comment by aristocratos** [comment]
> I see now that it says DEBUG: Using psutil version 5.5.1 in the error log

That is actually just informational, the outdated message will only appear if an exception caused by an outdated version is detected.

> Anyway, I guess this bug is resolved and you can close this if you want.

Sure thing.
