### ISSUE TITLE
[REQUEST] Scale network graph in same unit used for net_download and net_upload while in manual mode.

### ISSUE THREAD

**Issue by drazil100** [aristocratos/bpytop#67]
When I enter values in mebibits the graph scale is still in mebibytes. Also it would be nice if the labels reflect if the unit is in mebibits and not mebibytes if this feature is added.

![Screenshot from 2020-08-16 00-09-21](https://user-images.githubusercontent.com/17794391/90327026-2d184180-df55-11ea-97bb-ea890e92cfee.png)
![Screenshot from 2020-08-16 00-09-37](https://user-images.githubusercontent.com/17794391/90327030-31dcf580-df55-11ea-9c7f-984d218b8a63.png)
![Screenshot from 2020-08-16 00-09-52](https://user-images.githubusercontent.com/17794391/90327034-35707c80-df55-11ea-9c7e-cd872a86ebf5.png)
![Screenshot from 2020-08-16 00-09-56](https://user-images.githubusercontent.com/17794391/90327039-399c9a00-df55-11ea-91ad-83b20ba37789.png)

**Comment by drazil100** [comment]
Thinking about the label thing having mebibit labels would probably take up a lot of space maybe its better. On top of taking more digits to equal the same amount of data adding 3 characters to say bit would hog quite a bit of the top and bottom rows...

**Comment by aristocratos** [comment]
> Maybe it would be best to keep the labels in bytes rather than bits but only change the graph scales?

That's how it's currently working. Only showing bytes in the graph text is deliberate to stay consistent with the rest of the UI, (bit values are only showed in parenthesis) and to keep it short since not only the units would be longer but the values too.

**Comment by drazil100** [comment]
Hmmm. Could still let the graphs be unrounded and only round the labels. But I think I might retract my request since the labels should be reflective of the actual data range...

That said if its relatively easy to do so I think the fixed gradients should not be rounded.

**Comment by aristocratos** [comment]
The graph text are rounded with the floating_humanizer function to be shortened. The actual values are in actual bytes and are never rounded at all.

**Comment by aristocratos** [comment]
Forgot to mention in the descriptions but the entered values can be floats, as in "20.50Mbit".

**Comment by drazil100** [comment]
Oh cool I didn't know that. Anyway thanks. Gonna close this now :P

**Comment by aristocratos** [comment]
No problem :)
