### ISSUE TITLE
[BUG] Very slow and laggy in Arch linux st terminal

### ISSUE THREAD

**Issue by danezmotion** [aristocratos/bpytop#69]
Hello, I have tried both BASHTOP and BPYTOP and they both lack performace. BASHTOP runs and starts ok. But, it crashes. And, BPYTOP is very slow and it has draw problems for me. Not sure whats making it so slow.

Using Arch Linux with st terminal.

**Comment by aristocratos** [comment]
Follow the [bug report template](https://github.com/aristocratos/bpytop/issues/new?assignees=aristocratos&labels=bug&template=bug_report.md&title=%5BBUG%5D).

I'm not clairvoyant and can't debug based on username.
