### ISSUE TITLE
[BUG] Cannot run on FreeBSD 12.1-STABLE

### ISSUE THREAD

**Issue by iron-udjin** [aristocratos/bpytop#7]
bpytop version: 1.0.1
psutil version: 5.7.2
FreeBSD 12.1-STABLE r363784
Terminal: Xshell
locale: ru_RU.UTF-8
Python: 3.7.8

log output:

03/08/20 (22:02:01) | ERROR: Data collection thread failed with exception: 'utf-8' codec can't decode byte 0xff in position 153: invalid start byte
Traceback (most recent call last):
  File "./bpytop.py", line 2313, in _runner
    collector._collect()
  File "./bpytop.py", line 2406, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1879, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/usr/local/lib/python3.7/site-packages/psutil/_psbsd.py", line 454, in cpu_freq
    current, available_freq = cext.cpu_frequency(cpu)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 153: invalid start byte
03/08/20 (22:02:01) | WARNING: Exiting with errorcode (1). Runtime 0:00:03

**Comment by aristocratos** [comment]
I think this should probably be reported to https://github.com/giampaolo/psutil

I can add handling for the exception so it doesn't crash, but can't fix the issue since it's happening in the psutil module.

**Comment by aristocratos** [comment]
Added error handling in v1.0.2

**Comment by iron-udjin** [comment]
Here is issue: https://github.com/giampaolo/psutil/issues/1801

Thank you.
