### ISSUE TITLE
[BUG] Elements clipping in several themes

### ISSUE THREAD

**Issue by mfpx** [aristocratos/bpytop#70]
**Describe the bug**

Graphs get drawn under other elements. They start off fine, but then instead of simply getting drawn to the left as one would expect, they get drawn in both directions clipping other elements.

**To Reproduce**

None. I installed it on a new machine, and the problem appeared. Occurs when using the default, monokai, greyscale, default_black, flat-remix and nord themes

**Expected behavior**

Graphs not to clip other elements of the display

**Screenshots**

Using the default theme:
![image](https://user-images.githubusercontent.com/5671262/90341810-b6358400-dffa-11ea-9a9d-4c1d6107ab7e.png)
Using gruvbox_dark:
![image](https://user-images.githubusercontent.com/5671262/90341821-c8afbd80-dffa-11ea-8fc7-49bc373b25ab.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.16
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Debian 10
 - (OSX/FreeBSD) Os release version: N/A
 - Terminal used: Konsole
 - Font used: Noto Sans 10
 - Python version, `python3 --version` (version 3.6 or above is required): 3.7.3

**Additional context**

contents of `~/.config/bpytop/error.log` - Empty

(try running bpytop with `--debug` flag if error.log is empty)

david@NuttyMcNuts:~$ cat ~/.config/bpytop/error.log
16/08/20 (20:00:50) | INFO: New instance of bpytop version 1.0.16 started with pid 9875
16/08/20 (20:00:50) | INFO: Loglevel set to DEBUG
16/08/20 (20:00:50) | DEBUG: Using psutil version 5.7.2
16/08/20 (20:00:50) | DEBUG: CMD: /usr/local/bin/bpytop --debug
16/08/20 (20:00:51) | DEBUG: Collect and draw completed in 0.037668 seconds
16/08/20 (20:00:52) | DEBUG: Init completed in 2.388011 seconds
16/08/20 (20:01:17) | INFO: Exiting. Runtime 0:00:27

**Comment by aristocratos** [comment]
This is a known bug in certain versions/configurations of konsole, see https://github.com/aristocratos/bashtop/issues/83 for more info.

Sadly nothing I can do about it.

**Comment by aristocratos** [comment]
It might be an issue with konsole defaulting to a font with incorrect widths if the font you are using doesn't have the braille symbols used in the graphs. You could test this by downloading and using for example TerminessTTF font which should have the braille symbols included.
