### ISSUE TITLE
[REQUEST] Don't use env in the script's shebang

### ISSUE THREAD

**Issue by wAuner** [aristocratos/bpytop#73]
**Is your feature request related to a problem? Please describe.**
Currently you are using the python interpreter that is found first in the user's path.
 
https://github.com/aristocratos/bpytop/blob/73eb150abe3150082488acd00f3968f330c2dc89/bpytop.py#L1

As a python developer who often changes (conda) environments, this won't work. So I had to change the shebang to make it use a fixed interpreter (system's interpreter on Ubuntu 18.04).

**Describe the solution you'd like**
I think in this specific case it might be better to hardcode a specific interpreter here, for example `/usr/bin/python3` on newer distros with a python version >= 3.6 or another interpreter. 
If we agree on this, I can add some automation in the Makefile to adapt this during installation and create a PR.

**Comment by binalkaseem** [comment]
Good experience

**Comment by aristocratos** [comment]
Sure, I have no problem with this as long as it doesn't create any unintended consequences. Could you include a psutil check or something along those lines in the automation to make sure the selected interpreter has psutil installed?

**Comment by dehesselle** [comment]
It might be a matter of taste, but I disagree. Looking up the interpreter from the environment is a more universal approach than hardcoding. For example, many versions of macOS come without Python 3 and people install it e.g .via Homebrew to `/usr/local/bin`.

In your case, @wAuner, can't you just define yourself an alias to launch bpytop as you need it?

**Comment by wAuner** [comment]
I don't think it's a matter of taste. It's a system tool and you want your tool to always work the same, there is no reason to change the interpreter for your tool. The way I've implemented it in #74 is that during `make install` you 'll have the option to define that specific interpreter. It defaults to `/usr/local/bin`. I wanted to use env for the inital setup but I haven't found a good way to do that within the Makefile.

Of course it would be possible to create an alias, but that's much more convoluted than chaning the shebang, especially when you're using changing the shell.

**Comment by aristocratos** [comment]
Having looked through #74 I would say no, this isn't a good idea. When you said automation I assumed you were gonna replace the function of `env` and actually search the path for a suitable python interpreter. Not default the path to /usr/bin and make it harder to install for anyone not using that path, for example anybody following the OSX instructions and installing python3 through brew.

You're also modifying files in the local repository making it harder to update since it needs to be reset first. Running `make install` multiple times would also keep adding shebangs to the file if not resetting in between.

All your suggested changes accomplishes is fixing your specific problem while creating new ones for others.

Since the root issue is caused by your own choices I would suggest you either use the shell alias suggestion by @dehesselle or setup a venv, pyenv or similar to fix your issue.

**Comment by wAuner** [comment]
@aristocratos Good point. You are totally right about those two points. I've fixed them with the new commit. The default interpreter is now selected from the user's path at installation time and the original script is left untouched so that it can be updated via git in the future. This way the interpreter is hardcoded but still defaults to a reasonable choice. Those were valid points.
However, the root issue is by no means caused by "my own choices". And a venv does not the address the issue at hand. It's rather part of the problem.
The root issue is that it's not the best idea to make the execution of a system tool dependent on which interpreter is first on the user's path at any time, because this can change and for python developer's it will change constantly.

Take a look at my new PR and let me know what you think. I've tested it but maybe there are other things I've missed.

**Comment by aristocratos** [comment]
I'm having a bit of trouble wrapping my head around this.

> As a python developer who often changes (conda) environments, this won't work

Why not install and run bpytop in your untouched system environment?

Am I missing something here or are you trying to run bpytop from different environments (which I'm not sure what the reason would be) and are having issues with `/usr/bin/env` not picking up the same python interpreter as in a different environment?

**Comment by wAuner** [comment]
The problem is the following:
`/usr/bin/env python` chooses the python interpreter that is currently first in your path. But this changes constantly. If you're terminal is in a project dir with an activated environment and want to run bpytop in its current form, it will try to run it with your activated environment and most likelely fail (because of the missing dependency). So even if you've installed it in your system python, it will not be used. 
So you really want to define a fixed interpreter so that you can run bpytop independent of your current environment.

**Comment by wAuner** [comment]
You can simply test it. Create an incompatible env (without psutil) and activate it. Now you won't be able to run bpytop anymore. My adapted Makefile in #77 fixes this by choosing your python interpreter at installation time and freezing it, so that you can run bpytop at any time.

**Comment by aristocratos** [comment]
I'm not questioning the outcome. I'm questioning why you need to run bpytop from a environment it wasn't installed in?

If I setup a custom python environment my expectation would be that any python script run in that environment would use the environments python interpreter. If I need to run a script a script with dependencies installed in the normal environment I would simply start the script from another terminal not using a custom environment.

> However, the root issue is by no means caused by "my own choices"

Isn't setting up a custom environment and running a script not installed in said environment your own choice?

**Comment by dehesselle** [comment]
I understand your arguments, but I believe that you are the corner case here. If your development work requires you to constantly change your environment (this is what @aristocratos meant with "your own choices"), run bpytop in a new terminal with an untouched environment or setup an alias `alias btop='/usr/bin/python3 <where your bpytop is>'`.

I think even a system tool is allowed to expect an environment with working interpreter lookups.

**Comment by dehesselle** [comment]
One more thing, from the readme:
> PyPi packaging for installation with pip will be setup later.

As soon as this happens, you can install bpytop in your system environment with `pip` and it'll be hardcoded as you want.

**Comment by wAuner** [comment]
ok we're still not on the same page:
> I'm not questioning the outcome. I'm questioning why you need to run bpytop from a environment it wasn't installed in?
That is exactly what I'm trying to prevent here. Just to make sure that bpytop is always run with the interpreter it was installed in, nothing more nothing less.
I really can't think of a reason why a system tool should be run from different interpreters.

@dehesselle 
>I think even a system tool is allowed to expect an environment with working interpreter lookups.
That's my point. Right now this does not happen.

**Comment by aristocratos** [comment]
@wAuner 

> That is exactly what I'm trying to prevent here. Just to make sure that bpytop is always run with the interpreter it was installed in, nothing more nothing less.

Yes, you can prevent it, by opening a new shell and running bpytop. The python interpreter outside of your custom environment should be the same unless you're manually changing your whole system environment, in which case, why would you even do that?

**Comment by aristocratos** [comment]
>  >   I think even a system tool is allowed to expect an environment with working interpreter lookups.

>That's my point. Right now this does not happen.

No, it's accurately finding a interpreter, but since you're starting from an environment where you changed the search paths it's working as intended in finding the interpreter you defined.

**Comment by janxkoci** [comment]
> If I setup a custom python environment my expectation would be that any python script run in that environment would use the environments python interpreter. If I need to run a script with dependencies installed in the normal environment I would simply start the script from another terminal not using a custom environment.

Just imagine he wants to run `htop` instead of `bpytop`. Or plain `top`. Why should `bpytop` break just because it's written in the language he's using for development?

**Comment by aristocratos** [comment]
@janxkoci This issue has been closed for +2 years so don't know how relevant it really is now since this issue doesn't exist if installing with `pip`.

But for the sake of argument:
> Why should bpytop break just because it's written in the language he's using for development?

If you on your own volition change your python interpreter i would expect any python script to respect your choice of python interpreter. If you still want to run a script in some other interpreter you can always specify the full path of the interpreter.
When the "breakage" is intentional, stuff will break...

**Comment by janxkoci** [comment]
Sorry for reviving an old issue - I was searching issues for "conda" to see if it was mentioned, before suggesting to update your installation options with the info about installing with `conda`.

Anyway, I use `conda` for `R`, not python, so if some app suddenly breaks when I change the `conda` environment, I would be quite puzzled. I install your program as an "app", not running it as some script. The name gives away how it was made, but for a user it still should not be affected by stuff like changing dev env, imho.

On the other hand - I installed `bpytop` with `conda` into the base env and it works even in sub-environments (just like other programs I use) so in my case I don't see the issue. I was just trying to "translate" this issue from the point of view of an "app user".
