### ISSUE TITLE
Motherboard sensor entry labelled "CPUTIN" breaks cpu temperature detection

### ISSUE THREAD

**Issue by philipl** [aristocratos/bpytop#84]
My motherboard's sensor chip happens to have a temperature entry labelled "CPUTIN" which gets picked up during temp collection because it looks for labels that start with "CPU". Not only is this sensor not desirable, it actually breaks bpytop completely because the entry isn't connected to a real sensor and always reports -63C. Negative temperatures in turn break the gradient calculation.

I'm working around this by editing bpytop not to match "CPU", but that's presumably too blunt a fix. It could be filtered out later by temperature value, or, perhaps most robustly, by identifying what kind of the cpu is present, and then from there knowing what entry labels to look for. In my case, it's an Intel CPU and we know we need 'Core' labels, AMD has something else, and presumably, only some specific type of cpu actually means looking for a label that starts with "CPU".

**To Reproduce**

Run in an environment with a sensor entry that starts with CPU and returns a negative value

**Expected behavior**

This bogus entry should be ignored.

**Screenshots**

```
CPUTIN:                 -63.0°C  (high = +36.0°C, hyst = +35.0°C)  sensor = thermistor
```

**Info (please complete the following information):**
 - bpytop version: 1.0.18
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - Terminal used: gnome-terminal
 - Font used: Ubuntu Mono
 - Python version: 3.8.2

**Additional context**

```
23/08/20 (11:54:54) | ERROR: Data collection thread failed with exception: list index out of range
Traceback (most recent call last):
  File "./bpytop.py", line 2417, in _runner
    collector._draw()
  File "./bpytop.py", line 2619, in _draw
    CpuBox._draw_fg()
  File "./bpytop.py", line 1617, in _draw_fg
    out += f'{THEME.inactive_fg} ⡀⡀⡀⡀⡀{Mv.l(5)}{THEME.gradient["temp"][100 if cpu.cpu_temp[n][-1] >= cpu.cpu_temp_crit else (cpu.cpu_temp[n][-1] * 100 // cpu.cpu_temp_crit)]}{Graphs.temps[n](None if cls.resized else cpu.cpu_temp[n][-1])}'
IndexError: list index out of range
```

**Comment by aristocratos** [comment]
Fixed in v1.0.19

Added a check for negative values which the graphs can't handle right now anyways. And if someone is cooling there cpu with liquid nitrogen they are hopefully not using bpytop for temp monitoring :)
