### ISSUE TITLE
[REQUEST] A second "auto" network graph mode

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#85]
I like the current auto network graph mode. But I would like to suggest adding a second type of auto mode that auto-adjusts but uses the same maximum value scale on both top and bottom. 

A short story about why this would be helpful. I was looking at the auto network graph for a while one day and it took me quite a while to notice that something peculiar was happening. The system wasn't downloading anything, as far as I knew, but there was about 55K of incoming data. Constantly. Never stopping, and very little variation. 

I had to find the right tool (iftop turned out to be helpful) to try and figure out where the data was coming from, or what process might be receiving it. In the end it turned out to be an old Canon multifunction printer blasting multicast packets all over the network (55K per second, as mentioned above). Once I rebooted the printer, it stopped. That printer has long had a problem where it becomes "unavailable" to print to, and now I have a better understanding why. 

Anyway, because of the "balanced" nature of the current auto network graph, where it adjusts the scale independently for up and down, it took me quite a while to notice there was something really odd happening. If I had instead seen visually represented that the download speed was so much higher than the upload speed, when nothing was supposed to be downloading, I would have been clued into something odd happening much sooner. Instead I saw a graph that was "full" on both sides, even though the traffic on one side (down) was more than ten times the actual traffic on the other side. 

If you added a second "auto" mode that used the same scale for both up and down, it would be much more readily apparent when there is an unusually asynchronous situation happening. For instance, if I'm watching a 1080p YouTube video I should see a lot of down traffic and very little up traffic. So the graph would be very asymmetrical, and that would be correct and reassuring. 

Another way of saying this is that for many situations, a "balanced" auto mode that just tries to fill up both sides of the graph to make it look nice ends up being a too abstract and somewhat confusing representation of what is actually happening on the network. A mode that is allowed to be highly asymmetrical can be a much more concrete and clear representation of network activity. 

I think both types of auto mode have merit. I don't want the current auto mode replaced. Consider adding this as a second auto mode. All you would need to do is copy the current auto mode code and mirror the largest value measured to the other side of the graph, rather than allowing up and down to scale independently. 

Not sure exactly how to show the difference between them besides just displaying something like "auto1" and "auto2", which should be adequate.  You can leave an explanation of the modes in the options menu. Most users should pick up on the difference quickly. 

Nice work on updating the CPU name logic, by the way. Looks great.

**Comment by RedBearAK** [comment]
So that nothing jumps around in the UI too much when changing modes, perhaps something like this would be the best way to represent the three modes: 

```
auto:0   (manual mode, auto off)
auto:1   (balanced/visually symmetrical mode, the "pretty" mode)
auto:2   (unbalanced/visually asymmetrical mode, the "relative activity" mode)
```

**Comment by aristocratos** [comment]
Shouldn't be a problem to implement. But would in that case add a toggle for "network_graph_sync" or something like that in the options to make clear what the toggle does.

Will take a look at it when I got time.

**Comment by RedBearAK** [comment]
Splitting it into two separate settings in the options menu? Hmm. Not exactly what I was envisioning, but it would be a very concise way of presenting what's happening. Auto = on/off, Sync = on/off. I understand the concept. 

But I hope it would still be possible to toggle through the three modes by just hitting the "a" key, without entering the options menu, and display the mode visibly as shown above. 

Because it would be very nice to easily jump between the auto modes to quickly see how different the representations of traffic are. It would be far more cumbersome to have to find and toggle "network_graph_sync = true" in the options every time I wanted to switch auto modes. 

If you don't like the numbers idea I was thinking it could also be done with letters, like so: 

```
auto:M   (manual)
auto:S    (synchronous scaling)
auto:A    (asynchronous scaling)
```

Something like that.

**Comment by aristocratos** [comment]
Added a sync hotkey in v1.0.23

**Comment by RedBearAK** [comment]
You probably noticed this but the "sync" element hides itself at the smallest 80x24 window size. At least in what is now the standard "full" view mode. In that view it doesn't show up until the window is expanded to at least 88 columns wide. 

Seems to be working well.
