### ISSUE TITLE
[BUG] Long pauses / freezing on Linux

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#87]
There are no errors in the error log for this condition, so I'm not sure how to begin troubleshooting it. 

On a newly installed Linux Mint 20 (XFCE) system, MacBook3,1 from 2007 with 6GBs of RAM. 

Symptoms: 

Entire UI just stops updating and is unresponsive. If I press any keys those actions will all be performed after the freeze is over. 

I've counted freeze durations of up to 20 seconds. Many of around 5-10 seconds. 

This is with the refresh rate generally set to 2000ms (2 seconds). 

I manually updated psutil using the instructions you provided, so the versions are: 

```
bpytop version: 1.0.20
psutil version: 5.7.2
```

When this happens there is no sign of the CPU being overwhelmed with activity, nor any sign of unusual disk activity. 

I can only surmise the bpytop (or some subcomponent like psutil) is encountering some sort of race condition in the background. Besides implementing time-based logic in the code that counts how long each function takes to respond and throws errors when it is longer than expected, I'm not sure how to even begin figuring out what is happening. 

I haven't noticed any similar symptoms in any other GUI or terminal application. Only bpytop seems to be behaving this way. And I haven't seen this as far as I know on other systems I have available. 

Starting with an empty error log, I ran `bpytop --debug` just long enough to experience an obvious long freeze, then exited. It didn't take long. This is the resulting log: 

```
23/08/20 (22:40:20) | INFO: New instance of bpytop version 1.0.20 started with pid 33142
23/08/20 (22:40:20) | INFO: Loglevel set to DEBUG
23/08/20 (22:40:20) | DEBUG: Using psutil version 5.7.2
23/08/20 (22:40:20) | DEBUG: CMD: /usr/local/bin/bpytop --debug
23/08/20 (22:40:22) | DEBUG: Collect and draw completed in 0.397569 seconds
23/08/20 (22:40:23) | DEBUG: Init completed in 2.752632 seconds
23/08/20 (22:41:05) | INFO: Exiting. Runtime 0:00:45 
```

Seems to have no information about what is happening.

**Comment by aristocratos** [comment]
You could try the following to test if it is a psutil error.

``` bash
git clone https://github.com/giampaolo/psutil.git
cd psutil
python3 scripts/internal/print_api_speed.py
```

This is my output for reference:
``` console
SYSTEM APIS               SECONDS
----------------------------------
cpu_count                 0.000013
disk_usage                0.000017
sensors_battery           0.000023
cpu_times                 0.000033
cpu_stats                 0.000040
cpu_percent               0.000040
cpu_times_percent         0.000041
boot_time                 0.000041
pid_exists                0.000058
virtual_memory            0.000073
users                     0.000092
swap_memory               0.000097
net_io_counters           0.000124
net_if_stats              0.000154
net_if_addrs              0.000182
disk_partitions           0.000286
disk_io_counters          0.000432
sensors_fans              0.000594
pids                      0.000623
cpu_count (cores)         0.000715
sensors_temperatures      0.004284
process_iter (all)        0.014630
net_connections           0.017292
cpu_freq                  0.078729

PROCESS APIS              SECONDS
----------------------------------
create_time               0.000001
nice                      0.000005
cwd                       0.000009
cpu_affinity              0.000010
ionice                    0.000011
exe                       0.000012
num_fds                   0.000015
memory_info               0.000023
num_threads               0.000023
status                    0.000023
cpu_times                 0.000025
ppid                      0.000027
io_counters               0.000029
num_ctx_switches          0.000031
cpu_num                   0.000031
name                      0.000031
uids                      0.000034
cpu_percent               0.000037
is_running                0.000038
gids                      0.000038
memory_percent            0.000044
open_files                0.000051
threads                   0.000052
cmdline                   0.000052
connections               0.000069
environ                   0.000091
username                  0.000185
terminal                  0.000728
memory_full_info          0.000800
memory_maps               0.002211
children                  0.006912
```

You can also try running this and ```python3 scripts/internal/bench_oneshot.py``` a couple of times to see if the times differ a lot.

**Comment by aristocratos** [comment]
You could also try `glances` and see if there is the same issue since both `glances` and `bpytop` uses psutil for data collection.

**Comment by RedBearAK** [comment]
I tried Glances and it seems to update like clockwork every three seconds. The UI is very plain and utilitarian, lifeless and confusing. 

Can't seem to replicate the issue even in bpytop right now. Which is frustrating because I've been seeing it happening for a long time both before and after reformatting and reinstalling Linux Mint 20 on this same system. 

The test scripts show longer times than in your example, but not by much. A simple script to run them in a loop and spit out the time elapsed in milliseconds yields a reliable average of about 1600-1700ms to run through both scripts. Bpytop at the moment is butter smooth even if I crank the refresh time down to 100ms. Of course, it uses almost 70% CPU time on the Core2 Duo at that speed, but it works fine. 

I'll have to wait and see if the issue recurs. Should have taken a screenshot of what was installed when I used pip3 to install Glances. Can't help but think something got fixed in the background somehow. The only thing I can recall is something called "future".

**Comment by RedBearAK** [comment]
That's a really bizarre date format in the error log, by the way. Day, Month, Year? 

Catbug has a question for you: 

![catbugwhy](https://user-images.githubusercontent.com/64876997/91105282-299f4d00-e61c-11ea-97d9-658e5bec3b2d.gif)

**Comment by aristocratos** [comment]
> The test scripts show longer times than in your example, but not by much.

That's to be expected since I've got an i7 in my test system.

> The only thing I can recall is something called "future".

This is a module for backwards compatibility with python2 and is not used in bpytop.

So haven't got a clue what was causing the issue if it wasn't psutil, it's the only thing I can think of that would be able to slow everything down.

Let me know if it recurs and maybe I have had time to write some tests that could be used to find the issue by then.

> That's a really bizarre date format in the error log, by the way. Day, Month, Year?

You mean the standard date format of Sweden, where I live, which is also used by the majority of the rest of world?

https://en.wikipedia.org/wiki/Date_format_by_country

:)

**Comment by RedBearAK** [comment]
>You mean one the date formats of Sweden, where I live, which is also used by the majority of the rest of world?

Is it really? That's fascinating. But don't you ever find it visually confusing trying to scroll through something like a long log file with the date formatted like that? With the day in front the numbers at the beginning just keep cycling from 1-31 and it's much easier to lose your place. 

I've long rejected my own country's nonsensical Month, Day, Year format in favor of the universally logical descending-size format of YYYYMMDD_HHMMSS. 

If I close this issue myself, would I be able to re-open it myself if/when the issue recurs?

**Comment by aristocratos** [comment]
YYYMMDD is the more commonly used in Sweden as well, but didn't really think about the format when I wrote it, it's just standardized so I can recognize the dates from anyones log files.

Yeah, you should be able to reopen it whenever.

**Comment by RedBearAK** [comment]
Thanks. 

My OCD wants you to think about using the more "orderly" format, but I doubt it will ever be a big deal either way. 

Closing for now.

**Comment by aristocratos** [comment]
> My OCD wants you to think about using the more "orderly" format, but I doubt it will ever be a big deal either way.

Changing it now would certainly be confusing with different versions having different formats, but hopefully people shouldn't even need to reading the error.log if I keep my coding clean :)

**Comment by RedBearAK** [comment]
Finally encountered the long pauses again. Culprit might simply be disk latency caused by a TimeShift backup cycle (backing up to the same physical drive). 

This also may explain why the pauses were common early after reinstalling the OS and then seemed to disappear for a while. After the initial full backups were completed there would be very little data for TimeShift to backup during incremental backups, so the disk latency would normally be too intermittent to notice. 

Probably the only reason this was so noticeable in bpytop is because the UI is constantly updating on a regular basis, and part of the update cycle is reading information about disk usage, which might be slow to return during a TimeShift backup cycle. 

The makeshift psutil speed test shows significant delays while TimeShift was running. Up to almost 6 seconds in this case. 

```
Time elapsed: 2245 milliseconds
Time elapsed: 2261 milliseconds
Time elapsed: 2297 milliseconds
Time elapsed: 2354 milliseconds
Time elapsed: 2090 milliseconds
Time elapsed: 2580 milliseconds
Time elapsed: 2071 milliseconds
Time elapsed: 2646 milliseconds
Time elapsed: 2699 milliseconds
Time elapsed: 2596 milliseconds
Time elapsed: 2536 milliseconds
Time elapsed: 1729 milliseconds
Time elapsed: 2597 milliseconds
Time elapsed: 2310 milliseconds
Time elapsed: 2631 milliseconds
Time elapsed: 3984 milliseconds
Time elapsed: 4052 milliseconds
Time elapsed: 5796 milliseconds
Time elapsed: 5361 milliseconds
Time elapsed: 5044 milliseconds
Time elapsed: 2696 milliseconds
Time elapsed: 1979 milliseconds
Time elapsed: 1867 milliseconds
Time elapsed: 1890 milliseconds
Time elapsed: 1857 milliseconds
Time elapsed: 1946 milliseconds
Time elapsed: 2471 milliseconds
Time elapsed: 2124 milliseconds
Time elapsed: 1935 milliseconds
Time elapsed: 1860 milliseconds
Time elapsed: 1986 milliseconds
Time elapsed: 2084 milliseconds
```

Case closed, I hope.

**Comment by RedBearAK** [comment]
Reminder: The only reason this was ever a real issue is that the bpytop UI really does completely "freeze" and become unresponsive while the disk delay is happening. No menu, won't quit, if the window is resized it may get stuck at the black screen saying "resizing", and so on. And then whatever you attempt to do during the freeze suddenly happens all at once when the freeze is over. Like if you hit "o", "esc", "o", "esc", "o", "esc", "q", while bpytop is frozen, the options menu would then open up three times, go away three times, and bpytop would quit, all immediately after being unfrozen. 

I wonder if the function that reads disk stats (if that is what hangs up and causes the freezing) could be pushed to a background thread so the rest of the UI could remain more responsive. So the disk box content would just fail to update during the delay, which would be far less noticeable. 

This is on a decent SSD drive with no known problems, by the way, so the disk latency could potentially be much worse on a traditional hard drive and/or with a very large backup running.

**Comment by aristocratos** [comment]
> I wonder if the function that reads disk stats (if that is what hangs up and causes the freezing) could be pushed to a background thread so the rest of the UI could remain more responsive. So the disk box content would just fail to update during the delay, which would be far less noticeable.

Spawning new threads to possibly prevent a very uncommon issue in a dependency doesn't feel like a very good solution since it would increase the overall resource use, maybe not much, but still.

I would instead encourage you to post a issue to https://github.com/giampaolo/psutil since there is were the slowdown originates. And he would know better how to properly fix this.

**Comment by RedBearAK** [comment]
@aristocratos 

>I would instead encourage you to post a issue to https://github.com/giampaolo/psutil since there is were the slowdown originates. And he would know better how to properly fix this.

I will do that. 

But, a simpler solution I thought of later, rather than doing something heavy like trying to spawn new threads, was to put a time limit on each draw/update function where it returns an exception if the function doesn't return "on time". Then you can either let that module of the app fail to update temporarily (just let the data be static in that module until the system becomes responsive again), or you can display `[ERROR]` or `[DELAYED]` or something else indicating a temporary problem with the module. 

Hopefully that would be a relatively simple way to at least avoid the total UI lockup. Because that's entirely down to bpytop relying on each function in the update cycle to come back in a reasonable amount of time. Really the only reason I ever noticed this happening at all is because the entire interface including the clock and CPU graph would just .......................... stop. 

While I may have experienced an extreme example of this issue, I'm willing to bet that many users have and will continue to experience shorter "stutters" in the bpytop UI until you adjust for the possibility of delayed function returns. 

After thinking about it, I'm not sure what you would expect the psutil developer(s) to do to "fix" this, other than have psutil throw a time-based error when an attempt to read some type of data takes too long, which bpytop would then have to anticipate and deal with in a very similar way to the suggestion above. But wouldn't it be bpytop that would have a better idea of when a psutil query is taking "too long" to return a value? Because bpytop has the idea of a repeating "update interval" built in, which serves as a natural time limit for the expectation of getting a result back. 

Just something to think about.

**Comment by aristocratos** [comment]
> The makeshift psutil speed test shows significant delays while TimeShift was running. Up to almost 6 seconds in this case.

The output only shows the total time not the individual, `print_api_speed.py` would be better to actually see whats causing the slowdown. 

> But, a simpler solution I thought of later, rather than doing something heavy like trying to spawn new threads, was to put a time limit on each draw/update function where it returns an exception if the function doesn't return "on time". Then you can either let that module of the app fail to update temporarily (just let the data be static in that module until the system becomes responsive again), or you can display [ERROR] or [DELAYED] or something else indicating a temporary problem with the module.

> Hopefully that would be a relatively simple way to at least avoid the total UI lockup.

I don't see how this would work. The time it takes to collect data will be wildly different in all systems so there no good baseline to say what time it should take. And comparing times after the fact would only tell that there has been a slowdown, to know if the slowdown has stopped the collection would still need to be run and again causing a slowdown if not.

> While I may have experienced an extreme example of this issue, I'm willing to bet that many users have and will continue to experience shorter "stutters" in the bpytop UI until you adjust for the possibility of delayed function returns.

I would say that's an bold assumption to make since it's based only one data point and that being your own system.

> After thinking about it, I'm not sure what you would expect the psutil developer(s) to do to "fix" this, other than have psutil throw a time-based error when an attempt to read some type of data takes too long, which bpytop would then have to anticipate and deal with in a very similar way to the suggestion above.

I would expect the psutil developer to be a better fit to diagnose the problem even if there is no "fix" for it.

> Culprit might simply be disk latency caused by a TimeShift backup cycle (backing up to the same physical drive).

If this is caused by timeshift taking up most of all io priority I would look to try to remedy that (maybe lowering priority), instead of creating fixes for the programs that are being affected second hand.

**Comment by RedBearAK** [comment]
I did my best to file an issue report with psutil. 

https://github.com/giampaolo/psutil/issues/1825

Due to the relative lack of activity on issues in the psutil GitHub, I don't really expect to get much of a response since it's unlikely anyone will see this as a major problem to focus on. 

>I would say that's an bold assumption to make since it's based on only one data point and that being your own system.

My logic in thinking that this isn't just me me is that I'm on a 64-bit dual-core CPU with 6GB of RAM and an SSD drive, running bog-standard 64-bit Linux Mint 20, which has not displayed any obvious problems otherwise. This basic description of the system resembles millions of others out there. I therefore have no good reason to think that this issue should affect only me. 

To be clear, I'm not saying that most people would ever **notice** the delays they experience, just that they probably do unknowingly experience minor delays in the BpyTOP UI updating "on time". For instance, if there were a half-second delay every few minutes, how many users would ever notice that, or if they did, care that it was happening? I only noticed and cared that this was happening because I could sometimes count to 5, 10, or 20 while it was happening, and because I've spent so much time having fun playing with BpyTOP over the past couple of months. 

I think I will go ahead and close this again, for now. Thanks for your input.

**Comment by aristocratos** [comment]
@RedBearAK 
We can leave this open for the time being since it isn't solved, and if others experience the same problems they'll hopefully report it here.

Hopefully then we can pinpoint exactly where the slowdown is happening, if it's just one function, could be that most psutil functions are slowed down since most of them read from `/proc`. And since I can't reproduce this myself, it's pretty hard writing and testing fixes for it.

**Comment by RedBearAK** [comment]
Cross posting from issue #110. 

I experienced some very long "pauses" while running [a] cat command in a loop. I am now beginning to wonder if there really is a unique hardware-specific issue happening to me, causing the freezing in BpyTOP from issue #87. In this case I was not even able to Ctrl-C out of a simple terminal command. I've never seen anything like it. So maybe it is unique to me, or a bug in the actual terminal application. And the worst part is that TimeShift wasn't running when the pauses happened. 8-{

So there doesn't seem to be much point in leaving this open, since it's unlikely I'll ever discover the cause, it doesn't seem to have anything to do with BpyTOP or psutil, and probably doesn't affect anyone else. I'm going to close it.

**Comment by Kuurusch** [comment]
Have same issue. Updating neefs way more time than the set 2000ms and select up down hangs for 6 up to 10 seconds. Have a Workstation with a Threadripper 3970x and Ubuntu 18.04
