### ISSUE TITLE
[BUG] Color schema broken

### ISSUE THREAD

**Issue by Veshialle** [aristocratos/bpytop#88]
Color schema is broken while _tmuxed_ on certain os/build.
As show in the screen below using the bpytop inside a tmux it will break colors, default theme.
In my local machine (archlinux in wsl) everything work like a charm.

Whitout tmux the theme and colors are handled fine.
I've also checked the color handled and setted it as 256.

Reading the error.log file it can't reach https://raw.githubusercontent.com/aristocratos/bpytop/master/bpytop.py.
This is probably due to a web-filtering in my organization.
But both with or without tmux so I think it's not the real problem, does it reach for future updates right?

**To Reproduce**
 - Open a terminal on centos-7
 - Open tmux (no configuration provided at all)
 - Open bpytop
 - Get rid of the headache (sorry 😆 )

**Expected behavior**
Third screen below.

**Screenshots**

Broken colors schema with tmux:
![image](https://user-images.githubusercontent.com/15987201/91036124-1635b700-e607-11ea-8baa-cf29779ecc80.png)

Without tmux:
![image](https://user-images.githubusercontent.com/15987201/91037899-197e7200-e60a-11ea-8cf1-1e167d814e6c.png)

Everything working fine:
![image](https://user-images.githubusercontent.com/15987201/91037648-ab39af80-e609-11ea-960d-ede85bbe8295.png)

**Info:**
 - bpytop version: 1.0.20
 - psutil version: 5.7.2
 - Linux distribution and version: centos-release-7-8.2003.0.el7.centos.x86_64 
 - Kernel:  5.8.0-1.el7.elrepo.x86_64
 - Terminal used: /bin/bash + tmux
 - Font used: NA
 - Python version: Python 3.6.8
 - Installation via: `pip3 install bpytop --upgrade`

**Additional context**

contents of `~/.config/bpytop/error.log`
[Readable here](https://pastebin.com/raw/8SV8MspB)

**Comment by aristocratos** [comment]
https://github.com/aristocratos/bpytop#prerequisites :

> 
> #### Linux, Mac Os X and FreeBSD
> 
> For correct display, a terminal with support for:
> 
> * 24-bit truecolor ([See list of terminals with truecolor support](https://gist.github.com/XVilka/8346728))
> * Wide characters (Are sometimes problematic in web-based terminals)

Also:

> Whitout tmux the theme and colors are handled fine.

You don't figure this might be a `tmux` problem then and not a `bpytop` problem?

This will likely help you: https://stackoverflow.com/questions/41783367/tmux-tmux-true-color-is-not-working-properly

**Comment by Veshialle** [comment]
Sorry, my apologize.
Didn't read all the readme and didn't checked tmux version.
Don't know why I thinked there would be no problem using tmux vs directly bash.
I solved it installing newest version of tmux ( that it's not in official centos repositories ).

Thank you very much

**Comment by iandk** [comment]
So, the default macOS terminal is not supported?
Is there some sort of workaround?

**Comment by rodgerhe** [comment]
@iandk U can run it in tmux in Terminal.
