### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jacobq11** [aristocratos/bpytop#89]
**Describe the bug**

Program fails to load. Logs report = PermissionError: [Errno 13] Permission denied: '/proc/partitions'

**To Reproduce**

Run program on Ubuntu 20 with snap install

**Expected behavior**

Program should just start.

**Info (please complete the following information):**
 - bpytop version: 1.0.13
 - psutil version: 5.4.2
 - (Linux) Linux distribution and version: Ubuntu 
 - (OSX/FreeBSD) Os release version: 20.04
 - Terminal used: Putty and Ubuntu for windows
 - Font used:
 - Python version, 3.8.2

**Additional context**

`24/08/20 (16:58:00) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/64/usr/bin/bpytop", line 2366, in _runner
    collector._collect()
  File "/snap/bpytop/64/usr/bin/bpytop", line 2665, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/64/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/64/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/64/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/64/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
24/08/20 (16:58:00) | WARNING: Exiting with errorcode (1). Runtime 0:00:03`

(try running bpytop with `--debug` flag if error.log is empty)

**Comment by aristocratos** [comment]
Read the instructions...

https://snapcraft.io/install/bpytop/ubuntu

**Comment by jacobq11** [comment]
These are the exact instructions I used in the beginning.

I even rebooted the VM and it's still happening.

**Comment by aristocratos** [comment]
These are the errors you get when you haven't run:

``` bash
sudo snap connect bpytop:mount-observe
sudo snap connect bpytop:network-control
sudo snap connect bpytop:hardware-observe
sudo snap connect bpytop:system-observe
sudo snap connect bpytop:process-control
sudo snap connect bpytop:physical-memory-observe
```

Because the snap package does not have permissions to collect any data without them.

**Comment by jacobq11** [comment]
None of those commands were in those instructions you posted...

I ran those manually, and it came right up.

![image](https://user-images.githubusercontent.com/3047639/91075630-3fe4e300-e5f3-11ea-9201-1f7fc84b7097.png)

**Comment by aristocratos** [comment]
![scr33](https://user-images.githubusercontent.com/59659483/91076327-9d068600-e63f-11ea-80a3-4b27d1105403.png)

Also in https://github.com/aristocratos/bpytop#installation

**Comment by jacobq11** [comment]
Gotcha, hidden in a drop down. You should probably put it with the rest of the instructions to prevent stupid issues this these.  

Thanks for the help!

**Comment by aristocratos** [comment]
I didn't create or maintain the snap package and would recommend you to install bpytop with `pip` instead since I do maintain that package and it's always up to date.

**Comment by aristocratos** [comment]
Looking at your error.log psutil is also outdated in your snap install, which will prevent disk read and write speeds from being reported and can cause other issues. This would also be resolved by installing with pip instead.
