### ISSUE TITLE
Feature request: site-wide config file in /etc

### ISSUE THREAD

**Issue by gvegidy** [aristocratos/bpytop#9]
Currently the config is read from "$HOME/.config/bpytop/bashtop.cfg" and if that does not exist, build-in default values are used.

It would be nice if there was a check for a side-wide /etc/bashtop.cfg or /etc/bpytop/bashtop.cfg and if found, that would be used.

If there are a lot of different users on a machine, it would give them the preferred site-wide default config without them having to manually configure it.

**Comment by aristocratos** [comment]
Sure can add "/etc/bpytop.conf" as default seed for config file if it exists and no user config file exists yet.

**Comment by aristocratos** [comment]
Added in v1.0.2

**Comment by gvegidy** [comment]
Thank you very much.

Wow, that was lightning-fast.

**Comment by aristocratos** [comment]
Well, it was only 4 lines of code to add :)
