### ISSUE TITLE
Show all cores

### ISSUE THREAD

**Issue by arunvv90** [aristocratos/bpytop#92]
I have 52 ocres in my server. bpytop shows only 36 of them . How to solve this ?

**Comment by aristocratos** [comment]
Resize your terminal.

**Comment by arunvv90** [comment]
It was running in full window. I have multiple monitors and it works good in another monitor. It has something to do with ubuntu multiple monitor setup. Yor package works like charm now. Thank you

**Comment by aristocratos** [comment]
Maybe something funky with your terminal then? bpytop should always adapt to the size of the terminal.
