### ISSUE TITLE
Uptime location experiment

### ISSUE THREAD

**Issue by RedBearAK** [aristocratos/bpytop#93]
https://github.com/aristocratos/bpytop/blob/59916c9a85f416d1927d2c6b3e3abdee0708a5fe/bpytop.py#L1640

Changed this to:

```
out += f'{Mv.to(y - 1, x + w - 32)}{THEME.graph_text} up {cpu.uptime} '
```

I modified the uptime display location in my copy of bpytop just to see how it would turn out. I haven't gotten sophisticated enough to add the vertical green lines, but I have to say for now I'm just fine with how it looks, after adding a space at the beginning and end. 

It works at all window sizes, and should have enough room at 80x24 even on a system with up to 999 days of uptime. There does seem to be a small glitch when it rolls over from 23:59 hours to 0:00, which leaves two spaces at the end instead of one until the app is restarted (or you get back to 10:00 or more hours of uptime). 

I'm not offering this up as a pull request for now, but I am curious why anyone would not want this to be the default. It actually seems to balance the menu bar out a bit now that the mini mode indicator has been added to the left side. The balance would be even better if " days" was changed to "d" to make it more compact. Then it could be moved over to about `x + w - 29` instead of `x + w - 32`. 

Of course the main point of trying this out was because I didn't like the way the current uptime location interferes with the CPU graph rendering. This fixes that, for me, in a way that I like, and I wonder what others think of doing it this way. 

![Screen Shot 2020-08-26 at 2 07 42 PM](https://user-images.githubusercontent.com/64876997/91362994-17521a00-e7a8-11ea-8993-b15be89bdae8.png)

![Screen Shot 2020-08-26 at 2 07 06 PM](https://user-images.githubusercontent.com/64876997/91363104-51232080-e7a8-11ea-8a68-d3d5d0930b5a.png)

**Comment by RedBearAK** [comment]
The code is not very graceful but I managed to modify the uptime text and here is an example. Now it's just about the same size and in the same general location as the `|Menu|-|mini|` block on the left side. I like it. I think as long as it stays in the darker font it doesn't really make the CPU info area seem any more cluttered than before. 

Thoughts?

![Screen Shot 2020-08-26 at 3 06 16 PM](https://user-images.githubusercontent.com/64876997/91365677-2936bb80-e7ae-11ea-9d13-d9f748861161.png)

**Comment by RedBearAK** [comment]
Looks OK with the vertical bars too. Up to 999 days, 23:59 hours. 

![bpytop_uptime_mod05](https://user-images.githubusercontent.com/64876997/91653311-f0b40d80-ea4b-11ea-87cc-66ea59a81222.png)

Code: 

```
out += f'{Mv.to(y - 1, x + w - 29)}{THEME.cpu_box(Symbol.title_left)}{THEME.graph_text}up {cpu.uptime.replace(" days","d")}{THEME.cpu_box(Symbol.title_right)}'
```

**Comment by aristocratos** [comment]
Since this relates to design choices rather than functionality and is very subjective, I'll leave this open for others to voice opinions before making any changes.

**Comment by RedBearAK** [comment]
Managed to make the position of the uptime auto-adjust to the length of the update interval display. I decided that a single space between the two is probably the right way to do it. 

Also made the uptime display show "0d" when the system has been up for less than 24 hours. Makes the length more consistent when I'm testing on systems that I have to shut down regularly. 

3 digit update interval: 
![bpytop_uptime_self_adjusting1](https://user-images.githubusercontent.com/64876997/92337900-126b5100-f059-11ea-809d-cb057ff594d6.png)

4 digit update interval:
![bpytop_uptime_self_adjusting2](https://user-images.githubusercontent.com/64876997/92337902-14351480-f059-11ea-8f8b-7cf7a6a48f8f.png)

5 digit update interval:
![bpytop_uptime_self_adjusting3](https://user-images.githubusercontent.com/64876997/92337903-14cdab00-f059-11ea-94c2-c016b748d6df.png)

Had to replicate the `update_string` variable under a different name because it was "undefined" whenever I tried to calculate the length. 

```
		update_ms_string: str = f'{CONFIG.update_ms}ms'
		if len(cpu.uptime.replace(" days","d")) == len(cpu.uptime):
			cpu_uptime=f'0d, {cpu.uptime}'
		else:
			cpu_uptime=f'{cpu.uptime.replace(" days","d")}'

		out += f'{Mv.to(y - 1, x + w - 13 - len(cpu_uptime) - len(update_ms_string))}{THEME.cpu_box(Symbol.h_line * 1,Symbol.title_left)}{THEME.graph_text}up {cpu_uptime}{THEME.cpu_box(Symbol.title_right,Symbol.h_line * 0)}' 
```

Also had to make some adjustment to the `update_string` code to keep it from clobbering the uptime when they get too close. 

```
#			f'{Mv.to(CpuBox.y, xpos)}{THEME.cpu_box(Symbol.h_line * 7, Symbol.title_left)}{Fx.b}{THEME.hi_fg("+")} ',
			f'{Mv.to(CpuBox.y, xpos + 6)}{THEME.cpu_box(Symbol.h_line * 1, Symbol.title_left)}{Fx.b}{THEME.hi_fg("+")} ',
```

Problems remain. The symbols and spacing don't completely update until the update interval elapses. This becomes more obvious as the update interval gets longer. So it's not a super smooth adjustment like when you cycle through the network interfaces with "b" or "n".

**Comment by RedBearAK** [comment]
Another example of how nice this can look (dracula theme). With a 4-digit update interval (the default that most users will never change) and 1 or 2 digits of uptime days, this leaves a nearly symmetrical spacing around the clock element, and nicely balances the visual "weight" of the elements on the left side of the title bar. 

The symmetrical nature of the spacing around the clock could be further preserved by auto-adjusting the distance between "cpu" and "Menu" based on the total length of the uptime and update interval elements. 

None of this would have made quite as much sense to focus on before the "mini" mode evolved into "mode:xxxx" on the left, and before the clock was centered, but now there is an opportunity to have a highly symmetrical-feeling title bar balance at all times. 

With the positive side effect of a clean CPU graph. What's not to like? It looks good and groups all the "time" elements (clock, uptime, update interval) together logically. 

![bpytop_uptime_dracula](https://user-images.githubusercontent.com/64876997/92339232-84e02f00-f061-11ea-99c0-1ef22722bd11.png)

**Comment by RedBearAK** [comment]
I'm going to close this since there seems to be little interest in moving the uptime, and the battery info is now inhabiting the top bar.
