### ISSUE TITLE
Ony Terminus font looks good [BUG]

### ISSUE THREAD

**Issue by slalomsk8er** [aristocratos/bpytop#94]
**Describe the bug**

Graphs look off

**To Reproduce**

Debian GNU/Linux 10 (buster)
Konsole

installed via 

pip3 install bpytop --upgrade
Collecting bpytop
  Downloading https://files.pythonhosted.org/packages/c3/f8/fb95cb02015ccaf0773f7bece1d009ce18df223e595c51d86dbff4d53ffc/bpytop-1.0.21-py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 707kB/s 
Collecting psutil<6.0.0,>=5.7.0 (from bpytop)
  Downloading https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz (460kB)
    100% |████████████████████████████████| 460kB 661kB/s 
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... done
  Stored in directory: /root/.cache/pip/wheels/39/a0/f5/c4fa280463e29aea07797acb5312358fefb067c1f4f98e11b1
Successfully built psutil
Installing collected packages: psutil, bpytop
Successfully installed bpytop-1.0.21 psutil-5.7.2

Font: Noto Mono ... all fonts look bad except Terminus

**Expected behavior**

All mono spaced fonts look good

**Screenshots**

[print.pdf](https://github.com/aristocratos/bpytop/files/5136875/print.pdf)
![bpytop-default black](https://user-images.githubusercontent.com/100971/91453859-88fd9700-e880-11ea-8ec0-590d675b5f34.png)
![bpytop-default](https://user-images.githubusercontent.com/100971/91453923-a16db180-e880-11ea-9ad0-614f5a3bf8d8.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.21
 - psutil version: 5.7.2 (version 5.7.0 or above is required)
 - (Linux) Linux distribution and version: Debian GNU/Linux 10 (buster)
 - Terminal used: Konsole 18.04.0
 - Font used: All except Terminus
 - Python version, `python3 --version` (version 3.6 or above is required): 3.7.3

**Comment by AethanFoot** [comment]
This seems to be related to konsole. I've tested it on kitty and is perfect, then tested konsole and the 'lag' to the graphs are apparent with noto mono and saucecodepro nf.

**Comment by aristocratos** [comment]
Not a bug caused by bpytop. See #91
