### ISSUE TITLE
[BUG] Washed Out Colors in Screen Terminal Multiplexer

### ISSUE THREAD

**Issue by odzangba** [aristocratos/bpytop#97]
**Describe the bug**

Bpytop displays washed out colors when opened in a screen (terminal multiplexer) session.

**To Reproduce**

In a screen session, run bpytop

**Expected behavior**

Normal theme colors should be displayed.

**Screenshots**

![bpytop-screen-washed-out-colors](https://user-images.githubusercontent.com/6819630/91612970-d829f180-e97e-11ea-9c23-8e074b6490df.png)

**Info (please complete the following information):**
 - bpytop version: 1.0.21
 - psutil version: 5.7.2
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - (OSX/FreeBSD) Os release version:
 - Terminal used: xterm
 - Font used: Fixed
 - Python version: 3.8.2

**Additional context**

contents of `~/.config/bpytop/error.log`:

28/08/20 (20:56:23) | INFO: New instance of bpytop version 1.0.21 started with pid 310611
28/08/20 (20:56:23) | INFO: Loglevel set to DEBUG
28/08/20 (20:56:23) | DEBUG: Using psutil version 5.7.2
28/08/20 (20:56:23) | DEBUG: CMD: /usr/local/bin/bpytop --debug
28/08/20 (20:56:28) | DEBUG: Collect and draw completed in 3.718318 seconds
28/08/20 (20:56:29) | DEBUG: Init completed in 6.163810 seconds
28/08/20 (20:56:39) | INFO: Exiting. Runtime 0:00:16

**Comment by aristocratos** [comment]
Read the README.md

https://github.com/aristocratos/bpytop#prerequisites
