### ISSUE TITLE
Is there a way to hide process pane entirely?

### ISSUE THREAD

**Issue by gggauravgandhi** [aristocratos/bpytop#98]
Is there a way to hide process pane entirely?

 I am using this as in small side split, if I can hide a process, it will work out for me.
![image](https://user-images.githubusercontent.com/13112509/91627203-75af1080-e9d3-11ea-9249-09234a5c6687.png)

**Comment by RedBearAK** [comment]
If I understand the question correctly, that actually sounds like something I would like to see as well. Sort of the opposite of mini mode. In most cases I'm not actually that interested in the process list unless there's something misbehaving. Letting the user hide the process box and expand the mem, disk and net boxes would be neat. 

The "mini" on the menu bar could morph into "mode" to switch between three display modes, and continue to use the same keyboard shortcut for minimal disruption.

**Comment by aristocratos** [comment]
Sure that would be doable, will take a look at it when I've got time.

**Comment by gggauravgandhi** [comment]
> Sure, that would be doable, will take a look at it when I've got time.

I will love to help you with that if you don't mind. I have gone through code and looks doable for me.

**Comment by aristocratos** [comment]
You're welcome to submit a PR, some overview and what to keep in mind:
* For the "mini" toggle to be converted to a three way "mode" toggle there needs to be a list with acceptable values in the "Config" class and added logic for handling faulty values. See "log_level" for example.
* The "_calc_size" function in "MemBox", "NetBox" and "ProcBox" classes needs there calculations updated for the toggle.
* There needs to be added logic in the "Collector" class or "ProcCollector" class to not spend resources on collection when not showing processes.
* "process_keys" function needs new logic for a three way toggle for "m" key
* Also remember to add type info for any added variables.
* Lastly check your work with both `pylint` and `mypy`

**Comment by aristocratos** [comment]
Added new "view mode" toggle with a preset to hide processes in v1.0.23
